-- ================================================================================
-- FIX #1: Update Detection Thresholds
-- ================================================================================

UPDATE DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES
SET DETECTION_THRESHOLD = 0.55
WHERE CATEGORY_NAME IN ('PII', 'SOX', 'SOC2')
  AND IS_ACTIVE = TRUE;

SELECT 
    CATEGORY_NAME,
    DETECTION_THRESHOLD,
    DESCRIPTION
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES
WHERE CATEGORY_NAME IN ('PII', 'SOX', 'SOC2')
  AND IS_ACTIVE = TRUE;

-- ================================================================================
-- FIX #2: Analyze Pattern Coverage
-- ================================================================================

SELECT 
    c.CATEGORY_NAME,
    COUNT(p.PATTERN_ID) AS PATTERN_COUNT,
    LISTAGG(DISTINCT p.PATTERN_NAME, ', ') 
        WITHIN GROUP (ORDER BY p.PATTERN_NAME) AS SAMPLE_PATTERNS
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES c
LEFT JOIN DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS p
    ON c.CATEGORY_ID = p.CATEGORY_ID
   AND p.IS_ACTIVE = TRUE
WHERE c.IS_ACTIVE = TRUE
  AND c.CATEGORY_NAME IN ('PII', 'SOX', 'SOC2')
GROUP BY c.CATEGORY_NAME
ORDER BY PATTERN_COUNT DESC;

-- ================================================================================
-- FIX #3: Missing PII & SOX Patterns (Corrected Regex)
-- ================================================================================

-- PHONE NUMBER (PII)
INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS
    (CATEGORY_ID, PATTERN_NAME, PATTERN_STRING, PATTERN_REGEX, SENSITIVITY_WEIGHT, IS_ACTIVE)
SELECT 
    c.CATEGORY_ID,
    'Basic Phone Number',
    '\\d{3}[-.]?\\d{3}[-.]?\\d{4}',
    '\\d{3}[-.]?\\d{3}[-.]?\\d{4}',
    1.0,
    TRUE
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES c
WHERE c.CATEGORY_NAME = 'PII'
  AND c.IS_ACTIVE = TRUE
  AND NOT EXISTS (
      SELECT 1 
      FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS p
      WHERE p.CATEGORY_ID = c.CATEGORY_ID
        AND p.PATTERN_NAME = 'Basic Phone Number'
        AND p.IS_ACTIVE = TRUE
  );

-- EMAIL (PII)
INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS
    (CATEGORY_ID, PATTERN_NAME, PATTERN_STRING, PATTERN_REGEX, SENSITIVITY_WEIGHT, IS_ACTIVE)
SELECT 
    c.CATEGORY_ID,
    'Email Address',
    '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}',
    '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}',
    1.2,
    TRUE
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES c
WHERE c.CATEGORY_NAME = 'PII'
  AND c.IS_ACTIVE = TRUE
  AND NOT EXISTS (
      SELECT 1 
      FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS p
      WHERE p.CATEGORY_ID = c.CATEGORY_ID
        AND p.PATTERN_NAME = 'Email Address'
        AND p.IS_ACTIVE = TRUE
  );

-- CURRENCY AMOUNT (SOX) — FIXED REGEX
INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS
    (CATEGORY_ID, PATTERN_NAME, PATTERN_STRING, PATTERN_REGEX, SENSITIVITY_WEIGHT, IS_ACTIVE)
SELECT 
    c.CATEGORY_ID,
    'Currency Amount',
    '^\\$?\\d{1,3}(,\\d{3})*(\\.\\d{2})?$',
    '^\\$?\\d{1,3}(,\\d{3})*(\\.\\d{2})?$',
    0.8,
    TRUE
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES c
WHERE c.CATEGORY_NAME = 'SOX'
  AND c.IS_ACTIVE = TRUE
  AND NOT EXISTS (
      SELECT 1 
      FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS p
      WHERE p.CATEGORY_ID = c.CATEGORY_ID
        AND p.PATTERN_NAME = 'Currency Amount'
        AND p.IS_ACTIVE = TRUE
  );

-- ================================================================================
-- FIX #4: Keyword Coverage
-- ================================================================================

SELECT 
    c.CATEGORY_NAME,
    COUNT(k.KEYWORD_ID) AS KEYWORD_COUNT,
    COUNT(CASE WHEN k.MATCH_TYPE = 'EXACT' THEN 1 END) AS EXACT_MATCHES,
    COUNT(CASE WHEN k.MATCH_TYPE = 'CONTAINS' THEN 1 END) AS CONTAINS_MATCHES
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES c
LEFT JOIN DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS k
    ON c.CATEGORY_ID = k.CATEGORY_ID
   AND k.IS_ACTIVE = TRUE
WHERE c.IS_ACTIVE = TRUE
  AND c.CATEGORY_NAME IN ('PII', 'SOX', 'SOC2')
GROUP BY c.CATEGORY_NAME
ORDER BY KEYWORD_COUNT DESC;

-- ================================================================================
-- FIX #5: Verify Category Descriptions
-- ================================================================================

SELECT 
    CATEGORY_NAME,
    LENGTH(DESCRIPTION) AS DESC_LENGTH,
    DESCRIPTION
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES
WHERE IS_ACTIVE = TRUE
  AND CATEGORY_NAME IN ('PII', 'SOX', 'SOC2')
ORDER BY DESC_LENGTH;

-- ================================================================================
-- FINAL CONFIG VERIFICATION
-- ================================================================================

SELECT 
    'CATEGORIES' AS CONFIG_TYPE,
    COUNT(*) AS COUNT,
    AVG(DETECTION_THRESHOLD) AS AVG_THRESHOLD
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES
WHERE IS_ACTIVE = TRUE 
  AND CATEGORY_NAME IN ('PII', 'SOX', 'SOC2')

UNION ALL

SELECT 
    'KEYWORDS',
    COUNT(*),
    AVG(SENSITIVITY_WEIGHT)
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS
WHERE IS_ACTIVE = TRUE

UNION ALL

SELECT 
    'PATTERNS',
    COUNT(*),
    AVG(SENSITIVITY_WEIGHT)
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS
WHERE IS_ACTIVE = TRUE;
