-- ============================================================================
-- CORRECTED TABLE DESIGN: CLASSIFICATION_AI_RESULTS (NEW SCHEMA)
-- ============================================================================
-- This script creates the updated table structure with proper ASSET_FULL_NAME schema

-- Drop old table if exists
DROP TABLE IF EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS;

-- Create new table with corrected schema
CREATE TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS (
    RESULT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
    
    -- NEW: Single ASSET_FULL_NAME field instead of separate DB/SCHEMA/TABLE
    ASSET_FULL_NAME VARCHAR(16777216) NOT NULL,
    COLUMN_NAME VARCHAR(16777216),
    
    -- Classification fields
    SENSITIVITY_CATEGORY_ID VARCHAR(16777216),
    
    -- Compliance flags (mandatory defaults with proper NULL handling)
    PII_RELEVANT BOOLEAN DEFAULT FALSE NOT NULL,
    SOX_RELEVANT BOOLEAN DEFAULT FALSE NOT NULL,
    SOC2_RELEVANT BOOLEAN DEFAULT FALSE NOT NULL,
    
    -- CIA Levels (optional, can be populated via joins)
    CONFIDENTIALITY_LEVEL VARCHAR(10),
    INTEGRITY_LEVEL VARCHAR(10),
    AVAILABILITY_LEVEL VARCHAR(10),
    
    -- Update tracking
    IS_UPDATED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    
    -- Primary key
    primary key (RESULT_ID)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_CLASSIFICATION_AI_RESULTS_FQN 
ON DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS(ASSET_FULL_NAME);

-- Create index for column-level queries
CREATE INDEX IF NOT EXISTS IDX_CLASSIFICATION_AI_RESULTS_COLUMN 
ON DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS(ASSET_FULL_NAME, COLUMN_NAME);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_admin;

-- ============================================================================
-- DATA VALIDATION QUERIES
-- ============================================================================

-- 1. Unmapped classifications (orphaned sensitivity categories)
SELECT 
    'UNMAPPED_CLASSIFICATIONS' as ISSUE_TYPE,
    COUNT(*) as COUNT,
    'CLASSIFICATION_AI_RESULTS with invalid SENSITIVITY_CATEGORY_ID' as DESCRIPTION
FROM CLASSIFICATION_AI_RESULTS r
LEFT JOIN SENSITIVITY_CATEGORIES m
    ON r.SENSITIVITY_CATEGORY_ID = m.CATEGORY_ID
WHERE m.CATEGORY_ID IS NULL;

-- 2. Missing classification (assets without AI results)
SELECT 
    'MISSING_CLASSIFICATION' as ISSUE_TYPE,
    COUNT(*) as COUNT,
    'ASSETS without any AI classification results' as DESCRIPTION
FROM ASSETS s
LEFT JOIN CLASSIFICATION_AI_RESULTS r
    ON UPPER(TRIM(s.FULLY_QUALIFIED_NAME)) = UPPER(TRIM(r.ASSET_FULL_NAME))
WHERE r.ASSET_FULL_NAME IS NULL
  AND s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW');

-- 3. Invalid ASSET_FULL_NAME format
SELECT 
    'INVALID_FQN_FORMAT' as ISSUE_TYPE,
    COUNT(*) as COUNT,
    'CLASSIFICATION_AI_RESULTS with malformed ASSET_FULL_NAME' as DESCRIPTION
FROM CLASSIFICATION_AI_RESULTS
WHERE ASSET_FULL_NAME NOT REGEXP '^[A-Z0-9_]+\\.[A-Z0-9_]+\\.[A-Z0-9_]+$'
   OR LENGTH(ASSET_FULL_NAME) < 7;

-- 4. NULL compliance flags (data quality issue)
SELECT 
    'NULL_COMPLIANCE_FLAGS' as ISSUE_TYPE,
    COUNT(*) as COUNT,
    'CLASSIFICATION_AI_RESULTS with NULL compliance flags' as DESCRIPTION
FROM CLASSIFICATION_AI_RESULTS
WHERE PII_RELEVANT IS NULL
   OR SOX_RELEVANT IS NULL
   OR SOC2_RELEVANT IS NULL;

-- 5. Duplicate classifications (same asset+column)
SELECT 
    'DUPLICATE_CLASSIFICATIONS' as ISSUE_TYPE,
    COUNT(*) as COUNT,
    'Duplicate CLASSIFICATION_AI_RESULTS for same ASSET_FULL_NAME+COLUMN_NAME' as DESCRIPTION
FROM (
    SELECT ASSET_FULL_NAME, COLUMN_NAME, COUNT(*) as DUPLICATE_COUNT
    FROM CLASSIFICATION_AI_RESULTS
    GROUP BY ASSET_FULL_NAME, COLUMN_NAME
    HAVING COUNT(*) > 1
);

-- 6. Assets without sensitivity mapping
SELECT 
    'NO_SENSITIVITY_MAPPING' as ISSUE_TYPE,
    COUNT(*) as COUNT,
    'CLASSIFICATION_AI_RESULTS without SENSITIVITY_CATEGORY_ID' as DESCRIPTION
FROM CLASSIFICATION_AI_RESULTS
WHERE SENSITIVITY_CATEGORY_ID IS NULL OR SENSITIVITY_CATEGORY_ID = '';

-- ============================================================================
-- CORRECTED AGGREGATION EXAMPLES
-- ============================================================================

-- Example 1: Proper asset-level aggregation
SELECT 
    ASSET_FULL_NAME,
    MAX(COALESCE(PII_RELEVANT, FALSE)) AS PII_RELEVANT,
    MAX(COALESCE(SOX_RELEVANT, FALSE)) AS SOX_RELEVANT,
    MAX(COALESCE(SOC2_RELEVANT, FALSE)) AS SOC2_RELEVANT,
    COUNT(*) as TOTAL_COLUMNS_CLASSIFIED,
    COUNT(CASE WHEN SENSITIVITY_CATEGORY_ID IS NOT NULL THEN 1 END) as COLUMNS_WITH_SENSITIVITY
FROM CLASSIFICATION_AI_RESULTS
WHERE ASSET_FULL_NAME IS NOT NULL
GROUP BY ASSET_FULL_NAME
ORDER BY ASSET_FULL_NAME;

-- Example 2: Join with sensitivity categories for CIA mapping
SELECT 
    r.ASSET_FULL_NAME,
    r.COLUMN_NAME,
    r.SENSITIVITY_CATEGORY_ID,
    m.CATEGORY_NAME,
    m.CONFIDENTIALITY_LEVEL,
    m.INTEGRITY_LEVEL,
    m.AVAILABILITY_LEVEL,
    r.PII_RELEVANT,
    r.SOX_RELEVANT,
    r.SOC2_RELEVANT
FROM CLASSIFICATION_AI_RESULTS r
LEFT JOIN SENSITIVITY_CATEGORIES m
    ON r.SENSITIVITY_CATEGORY_ID = m.CATEGORY_ID
WHERE r.ASSET_FULL_NAME IS NOT NULL
ORDER BY r.ASSET_FULL_NAME, r.COLUMN_NAME;

-- ============================================================================
-- MIGRATION SCRIPT (if needed)
-- ============================================================================

-- Example migration from old schema to new schema
/*
INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS (
    ASSET_FULL_NAME,
    COLUMN_NAME,
    SENSITIVITY_CATEGORY_ID,
    PII_RELEVANT,
    SOX_RELEVANT,
    SOC2_RELEVANT,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    CREATED_AT
)
SELECT 
    UPPER(TRIM(COALESCE(DATABASE_NAME, CURRENT_DATABASE()))) || '.' || 
    UPPER(TRIM(SCHEMA_NAME)) || '.' || 
    UPPER(TRIM(TABLE_NAME)) as ASSET_FULL_NAME,
    COLUMN_NAME,
    SENSITIVITY_CATEGORY_ID,
    COALESCE(PII_RELEVANT, FALSE),
    COALESCE(SOX_RELEVANT, FALSE),
    COALESCE(SOC2_RELEVANT, FALSE),
    NULL as CONFIDENTIALITY_LEVEL,  -- To be populated via join
    NULL as INTEGRITY_LEVEL,       -- To be populated via join
    NULL as AVAILABILITY_LEVEL,   -- To be populated via join
    CREATED_AT
FROM OLD_CLASSIFICATION_AI_RESULTS
WHERE DATABASE_NAME IS NOT NULL 
  AND SCHEMA_NAME IS NOT NULL 
  AND TABLE_NAME IS NOT NULL;
*/
