-- ============================================================================
-- FIXED STORED PROCEDURE: SP_MERGE_ASSETS
-- ============================================================================
-- Fixes: 
-- 1. Reliable FQN-based joins with AI classification results
-- 2. Proper NULL handling and normalization
-- 3. Restricted AI classification to tables only
-- 4. Debug visibility for unmatched joins
-- ============================================================================

CREATE OR REPLACE PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    ts_start TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    run_id STRING DEFAULT UUID_STRING();
    last_watermark TIMESTAMP_NTZ;
    new_watermark TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    db_name STRING;
    rows_inserted INTEGER DEFAULT 0;
    rows_updated INTEGER DEFAULT 0;
    merge_query_id STRING;
BEGIN
    -- 1. Initialize Watermark table if not exists
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK (
        LAST_WATERMARK TIMESTAMP_NTZ,
        LAST_RUN_ID STRING
    );

    SELECT COALESCE(MAX(LAST_WATERMARK), '2000-01-01 00:00:00') INTO :last_watermark 
    FROM DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK;

    -- 2. Cleanup: Remove forbidden system records from ASSETS
    DELETE FROM DATA_CLASSIFICATION_GOVERNANCE.ASSETS
    WHERE 
        UPPER(DATABASE_NAME) IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
        OR UPPER(SCHEMA_NAME) IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
        OR UPPER(FULLY_QUALIFIED_NAME) REGEXP '^(SNOWFLAKE|SNOWFLAKE_SAMPLE_DATA|INFORMATION_SCHEMA|DATA_CLASSIFICATION_GOVERNANCE)\\..*';

    -- 3. Discovery Staging
    CREATE OR REPLACE TEMPORARY TABLE DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (
        DB STRING NOT NULL,
        SCHEMA STRING NOT NULL, 
        NAME STRING NOT NULL,
        ASSET_TYPE STRING NOT NULL,
        FQN STRING,
        DESCRIPTION STRING,
        LAST_ALTERED TIMESTAMP_NTZ
    );

    -- Phase 1: Filtered Database Discovery
    SHOW DATABASES;
    LET rs_databases RESULTSET := (
        SELECT "name" AS DATABASE_NAME 
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) 
        WHERE COALESCE(UPPER("name"), '') NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
    );

    FOR db_row IN rs_databases DO
        db_name := db_row.DATABASE_NAME;
        
        INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
        VALUES (:db_name, '', :db_name, 'DATABASE', :db_name, 'Database Object', CURRENT_TIMESTAMP());
        
        -- Tables & Views discovery
        BEGIN
            EXECUTE IMMEDIATE 'SHOW TABLES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
            SELECT "database_name", "schema_name", "name", "kind", 
                   "database_name" || '.' || "schema_name" || '.' || "name", 
                   'Table/View Asset',
                   COALESCE("last_altered", "created_on")
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE COALESCE(UPPER("schema_name"), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
              AND "database_name" IS NOT NULL AND "schema_name" IS NOT NULL
              AND COALESCE("last_altered", "created_on") > :last_watermark;
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- USER PROCEDURES (Native Exclusion of System SPs)
        BEGIN
            EXECUTE IMMEDIATE 'SHOW USER PROCEDURES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
            SELECT "catalog_name", "schema_name", "name", 'STORED_PROCEDURE', 
                   "catalog_name" || '.' || "schema_name" || '.' || "name" || "arguments", 
                   'Stored Procedure',
                   "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE COALESCE(UPPER("schema_name"), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
              AND "catalog_name" IS NOT NULL AND "schema_name" IS NOT NULL
              AND "created_on" > :last_watermark;
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- USER FUNCTIONS (Native Exclusion of Built-in Functions)
        BEGIN
            EXECUTE IMMEDIATE 'SHOW USER FUNCTIONS IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
            SELECT "catalog_name", "schema_name", "name", 'FUNCTION', 
                   "catalog_name" || '.' || "schema_name" || '.' || "name" || "arguments",
                   'Returns: ' || "returns",
                   "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE COALESCE(UPPER("schema_name"), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
              AND "catalog_name" IS NOT NULL AND "schema_name" IS NOT NULL
              AND "created_on" > :last_watermark;
        EXCEPTION WHEN OTHER THEN NULL;
        END;
    END FOR;

    -- 4. Enriched Merge Source with FIXED AI Join Logic
    CREATE OR REPLACE TEMPORARY TABLE DATA_CLASSIFICATION_GOVERNANCE.TEMP_MERGE_SOURCE AS
    WITH ai_results_agg AS (
        -- FIXED: Use new ASSET_FULL_NAME schema
        SELECT 
            ASSET_FULL_NAME,
            -- Aggregate to Table Level: TRUE if ANY column is TRUE
            MAX(COALESCE(PII_RELEVANT, FALSE)) as PII_RELEVANT,
            MAX(COALESCE(SOX_RELEVANT, FALSE)) as SOX_RELEVANT,
            MAX(COALESCE(SOC2_RELEVANT, FALSE)) as SOC2_RELEVANT
        FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
        WHERE ASSET_FULL_NAME IS NOT NULL
        GROUP BY ASSET_FULL_NAME
    )
    SELECT 
        MD5(UPPER(TRIM(s.FQN))) as ASSET_ID,
        s.NAME as ASSET_NAME,
        s.ASSET_TYPE,
        s.DB as DATABASE_NAME,
        s.SCHEMA as SCHEMA_NAME,
        s.NAME as OBJECT_NAME,
        s.FQN as FULLY_QUALIFIED_NAME,
        'SYSTEM' as DATA_OWNER,
        s.DESCRIPTION as DATA_DESCRIPTION,
        -- FIXED: Apply AI join only for Tables/Views with proper FQN matching
        CASE WHEN s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW') 
             THEN COALESCE(ar.PII_RELEVANT, FALSE) 
             ELSE FALSE 
        END as PII_RELEVANT,
        CASE WHEN s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW') 
             THEN COALESCE(ar.SOX_RELEVANT, FALSE) 
             ELSE FALSE 
        END as SOX_RELEVANT,
        CASE WHEN s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW') 
             THEN COALESCE(ar.SOC2_RELEVANT, FALSE) 
             ELSE FALSE 
        END as SOC2_RELEVANT,
        COALESCE(cd.LABEL, 'Unclassified') as CLASSIFICATION_LABEL,
        COALESCE(CAST(cd.C AS STRING), 'C1') as CONFIDENTIALITY_LEVEL,
        COALESCE(CAST(cd.I AS STRING), 'I1') as INTEGRITY_LEVEL,
        COALESCE(CAST(cd.A AS STRING), 'A1') as AVAILABILITY_LEVEL,
        CASE WHEN cd.LABEL IS NOT NULL THEN 'MANUAL' ELSE 'AUTO_DISCOVERY' END as CLASSIFICATION_METHOD
    FROM DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING s
    LEFT JOIN (
        SELECT ASSET_FULL_NAME, LABEL, CONFIDENTIALITY_LEVEL AS C, INTEGRITY_LEVEL AS I, AVAILABILITY_LEVEL AS A
        FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS
        WHERE STATUS = 'Approved'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(ASSET_FULL_NAME) ORDER BY DECISION_TIMESTAMP DESC) = 1
    ) cd ON UPPER(cd.ASSET_FULL_NAME) = UPPER(s.FQN)
    -- FIXED: FQN-based join with new schema
    LEFT JOIN ai_results_agg ar 
        ON UPPER(TRIM(ar.ASSET_FULL_NAME)) = UPPER(TRIM(s.FQN))
    WHERE COALESCE(UPPER(s.DB), '') NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
      AND COALESCE(UPPER(s.SCHEMA), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');

    -- 5. FIXED: Enhanced Debug Visibility for Unmatched Joins
    CREATE OR REPLACE TABLE DATA_CLASSIFICATION_GOVERNANCE.DEBUG_AI_CLASSIFICATION_MISMATCHES AS
    WITH 
    -- Tables discovered but not classified by AI
    discovered_unmatched AS (
        SELECT 
            UPPER(TRIM(s.FQN)) as ASSET_FULL_NAME,
            s.DB as DATABASE_NAME,
            s.SCHEMA as SCHEMA_NAME,
            s.NAME as TABLE_NAME,
            s.ASSET_TYPE,
            'DISCOVERED_BUT_NOT_CLASSIFIED' as MISMATCH_TYPE
        FROM DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING s
        WHERE s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW')
          AND UPPER(TRIM(s.FQN)) NOT IN (
              SELECT ASSET_FULL_NAME FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
              WHERE ASSET_FULL_NAME IS NOT NULL
          )
    ),
    -- AI classifications not matching discovered tables
    ai_unmatched AS (
        SELECT 
            ASSET_FULL_NAME,
            SPLIT_PART(ASSET_FULL_NAME, '.', 1) as DATABASE_NAME,
            SPLIT_PART(ASSET_FULL_NAME, '.', 2) as SCHEMA_NAME,
            SPLIT_PART(ASSET_FULL_NAME, '.', 3) as TABLE_NAME,
            'CLASSIFIED_BUT_NOT_DISCOVERED' as MISMATCH_TYPE
        FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
        WHERE ASSET_FULL_NAME IS NOT NULL
          AND ASSET_FULL_NAME NOT IN (
              SELECT UPPER(TRIM(FQN)) FROM DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING
              WHERE ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW')
          )
    )
    SELECT * FROM discovered_unmatched
    UNION ALL
    SELECT * FROM ai_unmatched;

    -- 6. Final MERGE with Change Detection
    MERGE INTO DATA_CLASSIFICATION_GOVERNANCE.ASSETS AS t
    USING DATA_CLASSIFICATION_GOVERNANCE.TEMP_MERGE_SOURCE AS s
    ON t.FULLY_QUALIFIED_NAME = s.FULLY_QUALIFIED_NAME
    WHEN MATCHED AND (
        t.ASSET_TYPE != s.ASSET_TYPE OR
        (t.PII_RELEVANT IS DISTINCT FROM s.PII_RELEVANT) OR
        (t.SOX_RELEVANT IS DISTINCT FROM s.SOX_RELEVANT) OR
        (t.SOC2_RELEVANT IS DISTINCT FROM s.SOC2_RELEVANT) OR
        t.CLASSIFICATION_LABEL != s.CLASSIFICATION_LABEL OR
        t.CONFIDENTIALITY_LEVEL != s.CONFIDENTIALITY_LEVEL OR
        t.INTEGRITY_LEVEL != s.INTEGRITY_LEVEL OR
        t.AVAILABILITY_LEVEL != s.AVAILABILITY_LEVEL OR
        COALESCE(t.DATA_DESCRIPTION, '') != COALESCE(s.DATA_DESCRIPTION, '')
    ) THEN
        UPDATE SET 
            t.ASSET_TYPE = s.ASSET_TYPE,
            t.DATA_DESCRIPTION = s.DATA_DESCRIPTION,
            t.PII_RELEVANT = s.PII_RELEVANT,
            t.SOX_RELEVANT = s.SOX_RELEVANT,
            t.SOC2_RELEVANT = s.SOC2_RELEVANT,
            t.CLASSIFICATION_LABEL = s.CLASSIFICATION_LABEL,
            t.CONFIDENTIALITY_LEVEL = s.CONFIDENTIALITY_LEVEL,
            t.INTEGRITY_LEVEL = s.INTEGRITY_LEVEL,
            t.AVAILABILITY_LEVEL = s.AVAILABILITY_LEVEL,
            t.RECORD_VERSION = t.RECORD_VERSION + 1,
            t.LAST_MODIFIED_TIMESTAMP = CURRENT_TIMESTAMP(),
            t.LAST_MODIFIED_BY = CURRENT_USER()
    WHEN NOT MATCHED THEN
        INSERT (
            ASSET_ID, ASSET_NAME, ASSET_TYPE, DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME, 
            FULLY_QUALIFIED_NAME, DATA_OWNER, DATA_DESCRIPTION, PII_RELEVANT, SOX_RELEVANT, SOC2_RELEVANT,
            CLASSIFICATION_LABEL, CONFIDENTIALITY_LEVEL, INTEGRITY_LEVEL, AVAILABILITY_LEVEL,
            CLASSIFICATION_METHOD, CREATED_TIMESTAMP, LAST_MODIFIED_TIMESTAMP, RECORD_VERSION, CREATED_BY, LAST_MODIFIED_BY
        )
        VALUES (
            s.ASSET_ID, s.ASSET_NAME, s.ASSET_TYPE, s.DATABASE_NAME, s.SCHEMA_NAME, s.OBJECT_NAME,
            s.FULLY_QUALIFIED_NAME, s.DATA_OWNER, s.DATA_DESCRIPTION, s.PII_RELEVANT, s.SOX_RELEVANT, s.SOC2_RELEVANT,
            s.CLASSIFICATION_LABEL, s.CONFIDENTIALITY_LEVEL, s.INTEGRITY_LEVEL, s.AVAILABILITY_LEVEL,
            s.CLASSIFICATION_METHOD, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_USER(), CURRENT_USER()
        );

    merge_query_id := LAST_QUERY_ID();
    SELECT "number of rows inserted", "number of rows updated" INTO :rows_inserted, :rows_updated
    FROM TABLE(RESULT_SCAN(:merge_query_id));

    -- 7. Update Watermark
    INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK (LAST_WATERMARK, LAST_RUN_ID)
    VALUES (:new_watermark, :run_id);

    -- 8. Log Summary Statistics
    INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG (USER_ID, ACTION, RESOURCE_TYPE, DETAILS)
    VALUES (
        CURRENT_USER(),
        'SP_MERGE_ASSETS_EXECUTION',
        'STORED_PROCEDURE',
        OBJECT_CONSTRUCT(
            'run_id', run_id,
            'rows_inserted', rows_inserted,
            'rows_updated', rows_updated,
            'execution_time_seconds', DATEDIFF(second, ts_start, CURRENT_TIMESTAMP()),
            'ai_classification_mismatches', (SELECT COUNT(*) FROM DATA_CLASSIFICATION_GOVERNANCE.DEBUG_AI_CLASSIFICATION_MISMATCHES)
        )
    );

    RETURN 'MERGE_COMPLETE: ' || :rows_inserted || ' inserted, ' || :rows_updated || ' updated. ' || 
           'Check DEBUG_AI_CLASSIFICATION_MISMATCHES for unmatched AI classifications.';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'MERGE_FAILED: ' || SQLERRM;
END;
$$;

-- ============================================================================
-- UPDATED TABLE DESIGN: CLASSIFICATION_AI_RESULTS (NEW SCHEMA)
-- ============================================================================
DROP TABLE IF EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS;

CREATE TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS (
    RESULT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
    ASSET_FULL_NAME VARCHAR(16777216) NOT NULL,        -- NEW: Single FQN field
    COLUMN_NAME VARCHAR(16777216),
    
    -- Classification fields
    SENSITIVITY_CATEGORY_ID VARCHAR(16777216),
    
    -- Compliance flags (mandatory defaults with proper NULL handling)
    PII_RELEVANT BOOLEAN DEFAULT FALSE NOT NULL,
    SOX_RELEVANT BOOLEAN DEFAULT FALSE NOT NULL,
    SOC2_RELEVANT BOOLEAN DEFAULT FALSE NOT NULL,
    
    -- CIA Levels (optional, can be populated via joins)
    CONFIDENTIALITY_LEVEL VARCHAR(10),
    INTEGRITY_LEVEL VARCHAR(10),
    AVAILABILITY_LEVEL VARCHAR(10),
    
    -- Update tracking
    IS_UPDATED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    
    -- Primary key
    primary key (RESULT_ID)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_CLASSIFICATION_AI_RESULTS_FQN 
ON DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS(ASSET_FULL_NAME);

-- Create index for column-level queries
CREATE INDEX IF NOT EXISTS IDX_CLASSIFICATION_AI_RESULTS_COLUMN 
ON DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS(ASSET_FULL_NAME, COLUMN_NAME);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_admin;

-- Grant permissions on debug table
GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DEBUG_AI_CLASSIFICATION_MISMATCHES TO APPLICATION ROLE app_public;
GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DEBUG_AI_CLASSIFICATION_MISMATCHES TO APPLICATION ROLE app_admin;

-- Grant usage on stored procedure
GRANT USAGE ON PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS() TO APPLICATION ROLE app_public;
GRANT USAGE ON PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS() TO APPLICATION ROLE app_admin;
