-- ============================================================================
-- SNOWFLAKE NATIVE APP SETUP SCRIPT
-- ============================================================================
-- This script runs inside the Application instance during installation or upgrade.
-- It initializes the application's internal schemas, roles, and objects.

-- ----------------------------------------------------------------------------
-- 1. INTERNAL SCHEMAS & ROLES
-- ----------------------------------------------------------------------------

-- Create the main application versioned schema
CREATE OR ALTER VERSIONED SCHEMA app_schema;

-- The manifest defines 'app_public', we grant it usage on our internal schema
GRANT USAGE ON SCHEMA app_schema TO APPLICATION ROLE app_public;

-- ----------------------------------------------------------------------------
-- 2. APPLICATION OBJECTS (Streamlit)
-- ----------------------------------------------------------------------------

-- Create the Streamlit object pointing to the 'app' directory
CREATE OR REPLACE STREAMLIT app_schema.DATA_GOVERNANCE_APP
  FROM '/app'
  MAIN_FILE = 'streamlit_app.py';

-- Grant access to the app's roles
GRANT USAGE ON STREAMLIT app_schema.DATA_GOVERNANCE_APP TO APPLICATION ROLE app_public;
GRANT USAGE ON STREAMLIT app_schema.DATA_GOVERNANCE_APP TO APPLICATION ROLE app_admin;

-- ----------------------------------------------------------------------------
-- 3. INTERNAL METADATA STORAGE
-- ----------------------------------------------------------------------------
-- This schema stores governance decisions and cached inventory INTERNAL to the app.
CREATE OR ALTER VERSIONED SCHEMA DATA_CLASSIFICATION_GOVERNANCE;
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO APPLICATION ROLE app_public;
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO APPLICATION ROLE app_admin;

-- Initialize internal tables for metadata sharing/caching
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.ASSETS (
    ASSET_ID STRING,
    ASSET_NAME STRING,
    ASSET_TYPE STRING,
    OBJECT_NAME STRING,
    FULLY_QUALIFIED_NAME STRING,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    CLASSIFICATION_LABEL STRING,
    CLASSIFICATION_LABEL_COLOR STRING,
    CONFIDENTIALITY_LEVEL STRING,
    INTEGRITY_LEVEL STRING,
    AVAILABILITY_LEVEL STRING,
    DATA_DESCRIPTION STRING,
    DATA_OWNER STRING,
    DATA_OWNER_EMAIL STRING,
    DATA_CUSTODIAN STRING,
    DATA_CUSTODIAN_EMAIL STRING,
    BUSINESS_UNIT STRING,
    BUSINESS_PURPOSE STRING,
    BUSINESS_DOMAIN STRING,
    LIFECYCLE STRING,
    REVIEW_STATUS STRING,
    PII_RELEVANT BOOLEAN DEFAULT FALSE,
    SOX_RELEVANT BOOLEAN DEFAULT FALSE,
    SOC2_RELEVANT BOOLEAN DEFAULT FALSE,
    CLASSIFICATION_RATIONALE STRING,
    CONFIDENTIALITY_IMPACT_ASSESSMENT STRING,
    INTEGRITY_IMPACT_ASSESSMENT STRING,
    AVAILABILITY_IMPACT_ASSESSMENT STRING,
    CLASSIFICATION_DATE TIMESTAMP_NTZ,
    CLASSIFIED_BY STRING,
    CLASSIFICATION_METHOD STRING,
    LAST_RECLASSIFICATION_DATE TIMESTAMP_NTZ,
    RECLASSIFICATION_TRIGGER STRING,
    RECLASSIFICATION_COUNT NUMBER DEFAULT 0,
    PREVIOUS_CLASSIFICATION_LABEL STRING,
    LAST_REVIEW_DATE TIMESTAMP_NTZ,
    NEXT_REVIEW_DATE TIMESTAMP_NTZ,
    REVIEW_FREQUENCY_DAYS NUMBER DEFAULT 365,
    PEER_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
    PEER_REVIEWER STRING,
    MANAGEMENT_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
    MANAGEMENT_REVIEWER STRING,
    CONSISTENCY_CHECK_DATE TIMESTAMP_NTZ,
    CONSISTENCY_CHECK_STATUS STRING,
    REGULATORY STRING,
    OVERALL_RISK_CLASSIFICATION STRING,
    COMPLIANCE_STATUS STRING DEFAULT 'PENDING',
    NON_COMPLIANCE_REASON STRING,
    HAS_EXCEPTION BOOLEAN DEFAULT FALSE,
    EXCEPTION_TYPE STRING,
    EXCEPTION_JUSTIFICATION STRING,
    EXCEPTION_APPROVED_BY STRING,
    EXCEPTION_APPROVAL_DATE TIMESTAMP_NTZ,
    EXCEPTION_EXPIRY_DATE DATE,
    EXCEPTION_MITIGATION_MEASURES STRING,
    CORRECTIVE_ACTION_REQUIRED BOOLEAN DEFAULT FALSE,
    CORRECTIVE_ACTION_DESCRIPTION STRING,
    CORRECTIVE_ACTION_DUE_DATE TIMESTAMP_NTZ,
    SENSITIVE_DATA_USAGE_COUNT NUMBER DEFAULT 0,
    LAST_ACCESSED_DATE TIMESTAMP_NTZ,
    ACCESS_FREQUENCY STRING,
    NUMBER_OF_CONSUMERS NUMBER,
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_BY STRING DEFAULT CURRENT_USER(),
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_VERSION NUMBER DEFAULT 1,
    ADDITIONAL_NOTES STRING
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ASSETS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ASSETS TO APPLICATION ROLE app_admin;

-- Special Categories & Compliance Coverage View
CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE(
    CATEGORY,
    STATUS,
    RATE,
    ACTION,
    COMPLIANT_COUNT,
    VIOLATION_COUNT
) AS
WITH ai_sensitive_assets AS (
    SELECT DISTINCT
        a.SCHEMA_NAME,
        a.TABLE_NAME,
        CONCAT(CURRENT_DATABASE(), '.', a.SCHEMA_NAME, '.', a.TABLE_NAME) as ASSET_FULL_NAME,
        MAX(CASE WHEN a.AI_CATEGORY IN ('PII', 'PERSONAL_DATA', 'IDENTIFIER') THEN 1 ELSE 0 END) as HAS_PII,
        MAX(CASE WHEN a.AI_CATEGORY IN ('FINANCIAL', 'ACCOUNTING', 'FINANCE') OR
                      UPPER(a.AI_CATEGORY) LIKE '%FINANCIAL%' OR
                      UPPER(a.AI_CATEGORY) LIKE '%SOX%' OR
                      (a.DETAILS IS NOT NULL AND a.DETAILS:"sox_relevant"::BOOLEAN = TRUE) THEN 1 ELSE 0 END) as HAS_SOX,
        MAX(CASE WHEN UPPER(a.AI_CATEGORY) LIKE '%SECURITY%' OR
                      UPPER(a.AI_CATEGORY) LIKE '%CONTROL%' OR
                      UPPER(a.AI_CATEGORY) LIKE '%SOC2%' OR
                      (a.DETAILS IS NOT NULL AND (
                          a.DETAILS:"compliance_frameworks" LIKE '%SOC2%' OR
                          a.DETAILS:"compliance_frameworks" LIKE '%SOC 2%'
                      )) THEN 1 ELSE 0 END) as HAS_SOC2
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS a
    WHERE a.FINAL_CONFIDENCE >= 0.7
    GROUP BY a.SCHEMA_NAME, a.TABLE_NAME
),
asset_classifications AS (
    SELECT
        a.ASSET_ID,
        a.ASSET_NAME,
        a.FULLY_QUALIFIED_NAME,
        a.CLASSIFICATION_LABEL,
        a.CONFIDENTIALITY_LEVEL,
        a.INTEGRITY_LEVEL,
        a.AVAILABILITY_LEVEL,
        a.PII_RELEVANT,
        a.SOX_RELEVANT,
        a.SOC2_RELEVANT
    FROM DATA_CLASSIFICATION_GOVERNANCE.ASSETS a
),
joined_data AS (
    SELECT
        COALESCE(ac.FULLY_QUALIFIED_NAME, ai.ASSET_FULL_NAME) as ASSET_NAME,
        ac.CLASSIFICATION_LABEL,
        ac.CONFIDENTIALITY_LEVEL,
        CASE WHEN (ai.HAS_PII = 1 OR ac.PII_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_PII,
        CASE WHEN (ai.HAS_SOX = 1 OR ac.SOX_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_SOX,
        CASE WHEN (ai.HAS_SOC2 = 1 OR ac.SOC2_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_SOC2,
        CASE
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C1' THEN 1
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C2' THEN 2
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C3' THEN 3
            WHEN ac.CLASSIFICATION_LABEL = 'Unclassified' THEN 1
            WHEN ac.CLASSIFICATION_LABEL = 'Internal' THEN 1
            WHEN ac.CLASSIFICATION_LABEL = 'Restricted' THEN 2
            WHEN ac.CLASSIFICATION_LABEL = 'Confidential' THEN 3
            ELSE 1
        END as CONFIDENTIALITY_NUMERIC
    FROM ai_sensitive_assets ai
    FULL OUTER JOIN asset_classifications ac
        ON ai.ASSET_FULL_NAME = ac.FULLY_QUALIFIED_NAME
    WHERE (ai.HAS_PII = 1 OR ai.HAS_SOX = 1 OR ai.HAS_SOC2 = 1 OR
           ac.PII_RELEVANT = TRUE OR ac.SOX_RELEVANT = TRUE OR ac.SOC2_RELEVANT = TRUE)
),
compliance_calculation AS (
    SELECT
        COUNT(CASE WHEN FINAL_HAS_PII = 1 AND CONFIDENTIALITY_NUMERIC >= 2 THEN 1 END) as PII_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_PII = 1 AND CONFIDENTIALITY_NUMERIC < 2 THEN 1 END) as PII_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_PII = 1 THEN 1 END) as PII_TOTAL,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 AND CONFIDENTIALITY_NUMERIC >= 3 THEN 1 END) as SOC2_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 AND CONFIDENTIALITY_NUMERIC < 3 THEN 1 END) as SOC2_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 THEN 1 END) as SOC2_TOTAL,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 AND CONFIDENTIALITY_NUMERIC >= 3 THEN 1 END) as SOX_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 AND CONFIDENTIALITY_NUMERIC < 3 THEN 1 END) as SOX_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 THEN 1 END) as SOX_TOTAL,
        COUNT(*) as TOTAL_SENSITIVE_ASSETS
    FROM joined_data
)
SELECT
    'PII' as Category,
    CASE
        WHEN PII_TOTAL = 0 THEN '⚠️ Attention'
        WHEN PII_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN PII_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END as Status,
    CASE
        WHEN PII_TOTAL = 0 THEN '0%'
        ELSE ROUND(PII_COMPLIANT * 100.0 / NULLIF(PII_TOTAL, 0), 0) || '%'
    END as Rate,
    CASE
        WHEN PII_TOTAL = 0 OR PII_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END as Action,
    PII_COMPLIANT as COMPLIANT_COUNT,
    PII_NON_COMPLIANT as VIOLATION_COUNT
FROM compliance_calculation

UNION ALL

SELECT
    'SOC 2',
    CASE
        WHEN SOC2_TOTAL = 0 THEN '⚠️ Attention'
        WHEN SOC2_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN SOC2_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END,
    CASE
        WHEN SOC2_TOTAL = 0 THEN '0%'
        ELSE ROUND(SOC2_COMPLIANT * 100.0 / NULLIF(SOC2_TOTAL, 0), 0) || '%'
    END,
    CASE
        WHEN SOC2_TOTAL = 0 OR SOC2_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END,
    SOC2_COMPLIANT,
    SOC2_NON_COMPLIANT
FROM compliance_calculation

UNION ALL

SELECT
    'SOX',
    CASE
        WHEN SOX_TOTAL = 0 THEN '⚠️ Attention'
        WHEN SOX_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN SOX_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END,
    CASE
        WHEN SOX_TOTAL = 0 THEN '0%'
        ELSE ROUND(SOX_COMPLIANT * 100.0 / NULLIF(SOX_TOTAL, 0), 0) || '%'
    END,
    CASE
        WHEN SOX_TOTAL = 0 OR SOX_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END,
    SOX_COMPLIANT,
    SOX_NON_COMPLIANT
FROM compliance_calculation;

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE TO APPLICATION ROLE app_admin;

-- Audit Log for general workflow events
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG (
    AUDIT_ID STRING DEFAULT UUID_STRING(),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_ID STRING,
    ACTION STRING,
    RESOURCE_TYPE STRING,
    RESOURCE_ID STRING,
    DETAILS VARIANT
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG TO APPLICATION ROLE app_admin;

-- Daily Audit Digests for tamper evidence
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS (
    DATE_KEY DATE PRIMARY KEY,
    RECORD_COUNT NUMBER,
    SHA256_HEX STRING,
    PREV_SHA256_HEX STRING,
    CHAIN_SHA256_HEX STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS TO APPLICATION ROLE app_admin;

-- Reclassification Requests
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS (
    REQUEST_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    REQUESTOR_USER STRING,
    REQUEST_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CURRENT_LABEL STRING,
    REQUESTED_LABEL STRING,
    REASON STRING,
    STATUS STRING DEFAULT 'PENDING',
    REVIEWER_USER STRING,
    REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    REVIEWER_NOTES STRING
);

GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_admin;

-- Staging area for bulk classification requests (Quality Review)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW (
    REVIEW_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    PROPOSED_CLASSIFICATION STRING,
    PROPOSED_C NUMBER(38,0),
    PROPOSED_I NUMBER(38,0),
    PROPOSED_A NUMBER(38,0),
    REVIEWER STRING,
    STATUS STRING,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9),
    REVIEW_DUE_DATE TIMESTAMP_TZ(9),
    LAST_COMMENT STRING,
    RISK_SCORE NUMBER(38,2)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW TO APPLICATION ROLE app_admin;

-- Historical record of all classification changes
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY (
    HISTORY_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    PREVIOUS_LABEL STRING,
    NEW_LABEL STRING,
    PREVIOUS_C NUMBER,
    NEW_C NUMBER,
    PREVIOUS_I NUMBER,
    NEW_I NUMBER,
    PREVIOUS_A NUMBER,
    NEW_A NUMBER,
    CHANGE_TYPE STRING, -- BULK, MANUAL, AI
    CHANGED_BY STRING,
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RATIONALE STRING,
    BATCH_ID STRING
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY TO APPLICATION ROLE app_admin;

-- Audit Log for classification decisions (History)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS (
    DECISION_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    DECISION_BY STRING,
    DECISION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS STRING,
    LABEL STRING,
    CONFIDENTIALITY_LEVEL NUMBER,
    INTEGRITY_LEVEL NUMBER,
    AVAILABILITY_LEVEL NUMBER,
    RATIONALE STRING,
    DETAILS VARIANT
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_admin;

-- View for user-specific classification tasks
CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS(
    TASK_ID,
    DATASET_NAME,
    ASSET_FULL_NAME,
    OWNER,
    STATUS,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    DUE_DATE,
    CREATED_AT,
    UPDATED_AT,
    STATUS_LABEL,
    DETAILS
) AS
SELECT
    TASK_ID,
    COALESCE(DATASET_NAME, SPLIT_PART(COALESCE(ASSET_FULL_NAME, ''), '.', 3)) AS DATASET_NAME,
    ASSET_FULL_NAME,
    COALESCE(ASSIGNED_TO, '') AS OWNER,
    COALESCE(STATUS, 'Pending') AS STATUS,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    DUE_DATE,
    CREATED_AT,
    UPDATED_AT,
    CASE 
        WHEN UPPER(COALESCE(STATUS,'')) IN ('COMPLETED', 'APPROVED') THEN 'COMPLETED'
        WHEN UPPER(COALESCE(STATUS,'')) = 'CANCELLED' THEN 'CANCELLED'
        ELSE 'IN_PROGRESS'
    END AS STATUS_LABEL,
    DETAILS
FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS;

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- ============================================================================
    -- These commands should be run ONCE to create the application package before publishing
    --
    -- 1. Create application package:
    -- CREATE APPLICATION PACKAGE IF NOT EXISTS DATA_CLASSIFICATION_APP;
    --
    -- 2. Create initial version:
    -- CREATE VERSION IF NOT EXISTS V1_0 FROM APPLICATION PACKAGE DATA_CLASSIFICATION_APP
    --   USING '@~' AS STAGE;
    --
    -- 3. Grant privileges to the package:
    -- GRANT APPLICATION ROLE DATA_CLASSIFICATION_APP!app_admin TO ROLE SYSADMIN;
    -- GRANT APPLICATION ROLE DATA_CLASSIFICATION_APP!app_public TO ROLE SYSADMIN;
    --
    -- 4. Verify installation:
    -- SHOW APPLICATION PACKAGES LIKE 'DATA_CLASSIFICATION_APP';
    -- SHOW VERSIONS IN APPLICATION PACKAGE DATA_CLASSIFICATION_APP;
    --
    -- 5. Test installation (optional):
    -- CREATE APPLICATION DATA_CLASSIFICATION_APP_TEST FROM APPLICATION PACKAGE DATA_CLASSIFICATION_APP USING VERSION V1_0;
    --
    -- Note: Use the deploy.sh or deploy.ps1 scripts for automated deployment

    -- ============================================================================
    -- MISSING VIEWS FOR DATA CLASSIFICATION APP
    ============================================================================
    -- These views are referenced in the app but were missing from setup.sql

    -- View for Classification Review (Quality Review)
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW AS
    SELECT 
        REVIEW_ID AS ID,
        ASSET_FULL_NAME,
        PROPOSED_CLASSIFICATION AS CLASSIFICATION_LABEL,
        PROPOSED_C AS C,
        PROPOSED_I AS I,
        PROPOSED_A AS A,
        REVIEWER AS ASSIGNED_TO,
        STATUS,
        CREATED_BY,
        CREATED_AT AS CREATED_DATE,
        UPDATED_AT,
        REVIEW_DUE_DATE AS DUE_DATE,
        LAST_COMMENT AS BUSINESS_JUSTIFICATION,
        RISK_SCORE
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW
    ORDER BY CREATED_AT DESC;

    -- View for Classification History
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY AS
    SELECT 
        HISTORY_ID AS ID,
        ASSET_FULL_NAME,
        PREVIOUS_LABEL,
        NEW_LABEL AS CLASSIFICATION_LABEL,
        PREVIOUS_C,
        NEW_C AS C,
        PREVIOUS_I,
        NEW_I AS I,
        PREVIOUS_A,
        NEW_A AS A,
        CHANGE_TYPE,
        CHANGED_BY AS DECISION_MAKER,
        CHANGED_AT AS CREATED_DATE,
        RATIONALE,
        BATCH_ID
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY
    ORDER BY CHANGED_AT DESC;

    -- View for Reclassification Requests
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS AS
    SELECT 
        REQUEST_ID AS ID,
        ASSET_FULL_NAME,
        CURRENT_LABEL,
        REQUESTED_LABEL AS CLASSIFICATION_LABEL,
        REQUESTOR_USER AS REQUESTOR_EMAIL,
        REQUEST_TIMESTAMP AS REQUEST_DATE,
        STATUS,
        REVIEWER_USER AS REVIEWER,
        REVIEW_TIMESTAMP,
        REVIEWER_NOTES,
        REASON AS RATIONALE
    FROM DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS
    ORDER BY REQUEST_TIMESTAMP DESC;

    -- Also create VW_CLASSIFICATION_REVIEWS (plural) which is used in the service
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS(
        REVIEW_ID,
        ASSET_FULL_NAME,
        REQUESTED_LABEL,
        CONFIDENTIALITY_LEVEL,
        INTEGRITY_LEVEL,
        AVAILABILITY_LEVEL,
        REVIEWER,
        STATUS,
        CREATED_AT,
        UPDATED_AT,
        REVIEW_DUE_DATE,
        STATUS_LABEL,
        LAST_COMMENT
    ) AS
    SELECT 
        REVIEW_ID,
        ASSET_FULL_NAME,
        PROPOSED_CLASSIFICATION AS REQUESTED_LABEL,
        PROPOSED_C AS CONFIDENTIALITY_LEVEL,
        PROPOSED_I AS INTEGRITY_LEVEL,
        PROPOSED_A AS AVAILABILITY_LEVEL,
        REVIEWER,
        STATUS,
        CREATED_AT,
        UPDATED_AT,
        REVIEW_DUE_DATE,
        CASE 
            WHEN STATUS = 'Pending' THEN 'Pending Review'
            WHEN STATUS = 'In Review' THEN 'Under Review'
            WHEN STATUS = 'Approved' THEN 'Approved'
            WHEN STATUS = 'Rejected' THEN 'Rejected'
            ELSE STATUS
        END AS STATUS_LABEL,
        LAST_COMMENT 
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW;

    -- Grant permissions on all views
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- SETUP COMPLETE
    -- ============================================================================