-- ============================================================================
-- SNOWFLAKE NATIVE APP SETUP SCRIPT
-- ============================================================================
-- This script runs inside the Application instance during installation or upgrade.
-- It initializes the application's internal schemas, roles, and objects.

-- ----------------------------------------------------------------------------
-- 1. INTERNAL SCHEMAS & ROLES
-- ----------------------------------------------------------------------------

-- Create the main application versioned schema
CREATE OR ALTER VERSIONED SCHEMA app_schema;

-- The manifest defines 'app_public', we grant it usage on our internal schema
GRANT USAGE ON SCHEMA app_schema TO APPLICATION ROLE app_public;

-- ----------------------------------------------------------------------------
-- 2. APPLICATION OBJECTS (Streamlit)
-- ----------------------------------------------------------------------------

-- Create the Streamlit object pointing to the 'app' directory
CREATE OR REPLACE STREAMLIT app_schema.DATA_GOVERNANCE_APP
  FROM '/app'
  MAIN_FILE = 'streamlit_app.py';

-- Grant access to the app's roles
GRANT USAGE ON STREAMLIT app_schema.DATA_GOVERNANCE_APP TO APPLICATION ROLE app_public;
GRANT USAGE ON STREAMLIT app_schema.DATA_GOVERNANCE_APP TO APPLICATION ROLE app_admin;

-- ----------------------------------------------------------------------------
-- 3. INTERNAL METADATA STORAGE
-- ----------------------------------------------------------------------------
-- This schema stores governance decisions and cached inventory INTERNAL to the app.
CREATE OR ALTER VERSIONED SCHEMA DATA_CLASSIFICATION_GOVERNANCE;
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO APPLICATION ROLE app_public;
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO APPLICATION ROLE app_admin;

-- Initialize internal tables for metadata sharing/caching
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.ASSETS (
    ASSET_ID STRING,
    ASSET_NAME STRING,
    ASSET_TYPE STRING,
    OBJECT_NAME STRING,
    FULLY_QUALIFIED_NAME STRING,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    CLASSIFICATION_LABEL STRING,
    CLASSIFICATION_LABEL_COLOR STRING,
    CONFIDENTIALITY_LEVEL STRING,
    INTEGRITY_LEVEL STRING,
    AVAILABILITY_LEVEL STRING,
    DATA_DESCRIPTION STRING,
    DATA_OWNER STRING,
    DATA_OWNER_EMAIL STRING,
    DATA_CUSTODIAN STRING,
    DATA_CUSTODIAN_EMAIL STRING,
    BUSINESS_UNIT STRING,
    BUSINESS_PURPOSE STRING,
    BUSINESS_DOMAIN STRING,
    LIFECYCLE STRING,
    REVIEW_STATUS STRING,
    PII_RELEVANT BOOLEAN DEFAULT FALSE,
    SOX_RELEVANT BOOLEAN DEFAULT FALSE,
    SOC2_RELEVANT BOOLEAN DEFAULT FALSE,
    CLASSIFICATION_RATIONALE STRING,
    CONFIDENTIALITY_IMPACT_ASSESSMENT STRING,
    INTEGRITY_IMPACT_ASSESSMENT STRING,
    AVAILABILITY_IMPACT_ASSESSMENT STRING,
    CLASSIFICATION_DATE TIMESTAMP_NTZ,
    CLASSIFIED_BY STRING,
    CLASSIFICATION_METHOD STRING,
    LAST_RECLASSIFICATION_DATE TIMESTAMP_NTZ,
    RECLASSIFICATION_TRIGGER STRING,
    RECLASSIFICATION_COUNT NUMBER DEFAULT 0,
    PREVIOUS_CLASSIFICATION_LABEL STRING,
    LAST_REVIEW_DATE TIMESTAMP_NTZ,
    NEXT_REVIEW_DATE TIMESTAMP_NTZ,
    REVIEW_FREQUENCY_DAYS NUMBER DEFAULT 365,
    PEER_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
    PEER_REVIEWER STRING,
    MANAGEMENT_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
    MANAGEMENT_REVIEWER STRING,
    CONSISTENCY_CHECK_DATE TIMESTAMP_NTZ,
    CONSISTENCY_CHECK_STATUS STRING,
    REGULATORY STRING,
    OVERALL_RISK_CLASSIFICATION STRING,
    COMPLIANCE_STATUS STRING DEFAULT 'PENDING',
    NON_COMPLIANCE_REASON STRING,
    HAS_EXCEPTION BOOLEAN DEFAULT FALSE,
    EXCEPTION_TYPE STRING,
    EXCEPTION_JUSTIFICATION STRING,
    EXCEPTION_APPROVED_BY STRING,
    EXCEPTION_APPROVAL_DATE TIMESTAMP_NTZ,
    EXCEPTION_EXPIRY_DATE DATE,
    EXCEPTION_MITIGATION_MEASURES STRING,
    CORRECTIVE_ACTION_REQUIRED BOOLEAN DEFAULT FALSE,
    CORRECTIVE_ACTION_DESCRIPTION STRING,
    CORRECTIVE_ACTION_DUE_DATE TIMESTAMP_NTZ,
    SENSITIVE_DATA_USAGE_COUNT NUMBER DEFAULT 0,
    LAST_ACCESSED_DATE TIMESTAMP_NTZ,
    ACCESS_FREQUENCY STRING,
    NUMBER_OF_CONSUMERS NUMBER,
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_BY STRING DEFAULT CURRENT_USER(),
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_VERSION NUMBER DEFAULT 1,
    ADDITIONAL_NOTES STRING
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ASSETS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ASSETS TO APPLICATION ROLE app_admin;

-- Special Categories & Compliance Coverage View
CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE(
    CATEGORY,
    STATUS,
    RATE,
    ACTION,
    COMPLIANT_COUNT,
    VIOLATION_COUNT
) AS
WITH ai_sensitive_assets AS (
    SELECT DISTINCT
        a.ASSET_FULL_NAME,
        -- Aggregate to table level using new schema
        MAX(COALESCE(a.PII_RELEVANT, FALSE)) as HAS_PII,
        MAX(COALESCE(a.SOX_RELEVANT, FALSE)) as HAS_SOX,
        MAX(COALESCE(a.SOC2_RELEVANT, FALSE)) as HAS_SOC2
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS a
    -- Filter for table assets only
    WHERE a.ASSET_FULL_NAME IS NOT NULL
    GROUP BY a.ASSET_FULL_NAME
),
asset_classifications AS (
    SELECT
        a.ASSET_ID,
        a.ASSET_NAME,
        a.FULLY_QUALIFIED_NAME,
        a.CLASSIFICATION_LABEL,
        a.CONFIDENTIALITY_LEVEL,
        a.INTEGRITY_LEVEL,
        a.AVAILABILITY_LEVEL,
        a.PII_RELEVANT,
        a.SOX_RELEVANT,
        a.SOC2_RELEVANT
    FROM DATA_CLASSIFICATION_GOVERNANCE.ASSETS a
),
joined_data AS (
    SELECT
        COALESCE(ac.FULLY_QUALIFIED_NAME, ai.ASSET_FULL_NAME) as ASSET_NAME,
        ac.CLASSIFICATION_LABEL,
        ac.CONFIDENTIALITY_LEVEL,
        CASE WHEN (ai.HAS_PII = 1 OR ac.PII_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_PII,
        CASE WHEN (ai.HAS_SOX = 1 OR ac.SOX_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_SOX,
        CASE WHEN (ai.HAS_SOC2 = 1 OR ac.SOC2_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_SOC2,
        CASE
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C1' THEN 1
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C2' THEN 2
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C3' THEN 3
            WHEN ac.CLASSIFICATION_LABEL = 'Unclassified' THEN 1
            WHEN ac.CLASSIFICATION_LABEL = 'Internal' THEN 1
            WHEN ac.CLASSIFICATION_LABEL = 'Restricted' THEN 2
            WHEN ac.CLASSIFICATION_LABEL = 'Confidential' THEN 3
            ELSE 1
        END as CONFIDENTIALITY_NUMERIC
    FROM ai_sensitive_assets ai
    FULL OUTER JOIN asset_classifications ac
        ON ai.ASSET_FULL_NAME = ac.FULLY_QUALIFIED_NAME
    WHERE (ai.HAS_PII = 1 OR ai.HAS_SOX = 1 OR ai.HAS_SOC2 = 1 OR
           ac.PII_RELEVANT = TRUE OR ac.SOX_RELEVANT = TRUE OR ac.SOC2_RELEVANT = TRUE)
),
compliance_calculation AS (
    SELECT
        COUNT(CASE WHEN FINAL_HAS_PII = 1 AND CONFIDENTIALITY_NUMERIC >= 2 THEN 1 END) as PII_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_PII = 1 AND CONFIDENTIALITY_NUMERIC < 2 THEN 1 END) as PII_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_PII = 1 THEN 1 END) as PII_TOTAL,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 AND CONFIDENTIALITY_NUMERIC >= 3 THEN 1 END) as SOC2_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 AND CONFIDENTIALITY_NUMERIC < 3 THEN 1 END) as SOC2_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 THEN 1 END) as SOC2_TOTAL,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 AND CONFIDENTIALITY_NUMERIC >= 3 THEN 1 END) as SOX_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 AND CONFIDENTIALITY_NUMERIC < 3 THEN 1 END) as SOX_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 THEN 1 END) as SOX_TOTAL,
        COUNT(*) as TOTAL_SENSITIVE_ASSETS
    FROM joined_data
)
SELECT
    'PII' as Category,
    CASE
        WHEN PII_TOTAL = 0 THEN '⚠️ Attention'
        WHEN PII_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN PII_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END as Status,
    CASE
        WHEN PII_TOTAL = 0 THEN '0%'
        ELSE ROUND(PII_COMPLIANT * 100.0 / NULLIF(PII_TOTAL, 0), 0) || '%'
    END as Rate,
    CASE
        WHEN PII_TOTAL = 0 OR PII_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END as Action,
    PII_COMPLIANT as COMPLIANT_COUNT,
    PII_NON_COMPLIANT as VIOLATION_COUNT
FROM compliance_calculation

UNION ALL

SELECT
    'SOC 2',
    CASE
        WHEN SOC2_TOTAL = 0 THEN '⚠️ Attention'
        WHEN SOC2_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN SOC2_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END,
    CASE
        WHEN SOC2_TOTAL = 0 THEN '0%'
        ELSE ROUND(SOC2_COMPLIANT * 100.0 / NULLIF(SOC2_TOTAL, 0), 0) || '%'
    END,
    CASE
        WHEN SOC2_TOTAL = 0 OR SOC2_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END,
    SOC2_COMPLIANT,
    SOC2_NON_COMPLIANT
FROM compliance_calculation

UNION ALL

SELECT
    'SOX',
    CASE
        WHEN SOX_TOTAL = 0 THEN '⚠️ Attention'
        WHEN SOX_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN SOX_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END,
    CASE
        WHEN SOX_TOTAL = 0 THEN '0%'
        ELSE ROUND(SOX_COMPLIANT * 100.0 / NULLIF(SOX_TOTAL, 0), 0) || '%'
    END,
    CASE
        WHEN SOX_TOTAL = 0 OR SOX_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END,
    SOX_COMPLIANT,
    SOX_NON_COMPLIANT
FROM compliance_calculation;

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE TO APPLICATION ROLE app_admin;

-- Audit Log for general workflow events
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG (
    AUDIT_ID STRING DEFAULT UUID_STRING(),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_ID STRING,
    ACTION STRING,
    RESOURCE_TYPE STRING,
    RESOURCE_ID STRING,
    DETAILS VARIANT
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG TO APPLICATION ROLE app_admin;

-- Table: CLASSIFICATION_AUDIT
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT (
    ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    RESOURCE_ID VARCHAR(16777216),
    ACTION VARCHAR(16777216),
    ACTION_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    USER_ID VARCHAR(16777216),
    PREVIOUS_STATE VARIANT,
    NEW_STATE VARIANT,
    REASON VARCHAR(1000),
    DECISION_MAKER VARCHAR(16777216),
    APPROVAL_REQUIRED BOOLEAN,
    APPROVED_BY VARCHAR(16777216),
    APPROVAL_TIMESTAMP TIMESTAMP_NTZ(9),
    COMPLIANCE_FLAGS VARCHAR(16777216)
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT TO APPLICATION ROLE app_admin;

-- Daily Audit Digests for tamper evidence
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS (
    DATE_KEY DATE PRIMARY KEY,
    RECORD_COUNT NUMBER,
    SHA256_HEX STRING,
    PREV_SHA256_HEX STRING,
    CHAIN_SHA256_HEX STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS TO APPLICATION ROLE app_admin;

-- Application Roles Management
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.ROLES (
    ROLE_NAME STRING PRIMARY KEY,
    DESCRIPTION STRING
);

CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.ROLE_ASSIGNMENTS (
    USER_EMAIL STRING,
    ROLE_NAME STRING,
    ASSIGNED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_EMAIL, ROLE_NAME)
);

CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.IDP_GROUP_MAP (
    GROUP_NAME STRING,
    ROLE_NAME STRING,
    ASSIGNED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (GROUP_NAME, ROLE_NAME)
);

-- Ensure correct columns in legacy tables
ALTER TABLE IF EXISTS DATA_CLASSIFICATION_GOVERNANCE.ROLE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS USER_EMAIL STRING;
ALTER TABLE IF EXISTS DATA_CLASSIFICATION_GOVERNANCE.ROLE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS ASSIGNED_AT TIMESTAMP_NTZ;

-- Governance Engine Configuration
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS (
    KEY STRING PRIMARY KEY,
    VALUE STRING
);

CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.IA_RULES (
    TYPE STRING,
    PATTERN STRING,
    I_LEVEL NUMBER,
    A_LEVEL NUMBER,
    PRIORITY NUMBER,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Initial Business Units and Settings (Seeding)
INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.ROLES (ROLE_NAME, DESCRIPTION)
SELECT 'ADMIN', 'Full system administration' WHERE NOT EXISTS (SELECT 1 FROM DATA_CLASSIFICATION_GOVERNANCE.ROLES WHERE ROLE_NAME = 'ADMIN');
INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.ROLES (ROLE_NAME, DESCRIPTION)
SELECT 'CUSTODIAN', 'Data governance steward' WHERE NOT EXISTS (SELECT 1 FROM DATA_CLASSIFICATION_GOVERNANCE.ROLES WHERE ROLE_NAME = 'CUSTODIAN');

INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS (KEY, VALUE)
SELECT 'enable_discovery', 'true' WHERE NOT EXISTS (SELECT 1 FROM DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS WHERE KEY = 'enable_discovery');
INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS (KEY, VALUE)
SELECT 'enable_workflow', 'true' WHERE NOT EXISTS (SELECT 1 FROM DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS WHERE KEY = 'enable_workflow');

GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ROLES TO APPLICATION ROLE app_public;
GRANT ALL ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ROLES TO APPLICATION ROLE app_admin;

GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ROLE_ASSIGNMENTS TO APPLICATION ROLE app_public;
GRANT ALL ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ROLE_ASSIGNMENTS TO APPLICATION ROLE app_admin;

GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.IDP_GROUP_MAP TO APPLICATION ROLE app_public;
GRANT ALL ON TABLE DATA_CLASSIFICATION_GOVERNANCE.IDP_GROUP_MAP TO APPLICATION ROLE app_admin;

GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS TO APPLICATION ROLE app_public;
GRANT ALL ON TABLE DATA_CLASSIFICATION_GOVERNANCE.APP_SETTINGS TO APPLICATION ROLE app_admin;

GRANT SELECT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.IA_RULES TO APPLICATION ROLE app_public;
GRANT ALL ON TABLE DATA_CLASSIFICATION_GOVERNANCE.IA_RULES TO APPLICATION ROLE app_admin;

-- Reclassification Requests
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS (
    REQUEST_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    REQUESTOR_USER STRING,
    REQUEST_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CURRENT_LABEL STRING,
    REQUESTED_LABEL STRING,
    REASON STRING,
    STATUS STRING DEFAULT 'PENDING',
    REVIEWER_USER STRING,
    REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    REVIEWER_NOTES STRING
);

GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_admin;

-- Staging area for bulk classification requests (Quality Review)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW (
    REVIEW_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    PROPOSED_CLASSIFICATION STRING,
    PROPOSED_C NUMBER(38,0),
    PROPOSED_I NUMBER(38,0),
    PROPOSED_A NUMBER(38,0),
    REVIEWER STRING,
    STATUS STRING,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9),
    REVIEW_DUE_DATE TIMESTAMP_TZ(9),
    LAST_COMMENT STRING,
    RISK_SCORE NUMBER(38,2)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW TO APPLICATION ROLE app_admin;

-- Historical record of all classification changes
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY (
    HISTORY_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    PREVIOUS_LABEL STRING,
    NEW_LABEL STRING,
    PREVIOUS_C NUMBER,
    NEW_C NUMBER,
    PREVIOUS_I NUMBER,
    NEW_I NUMBER,
    PREVIOUS_A NUMBER,
    NEW_A NUMBER,
    CHANGE_TYPE STRING, -- BULK, MANUAL, AI
    CHANGED_BY STRING,
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RATIONALE STRING,
    BATCH_ID STRING
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY TO APPLICATION ROLE app_admin;

-- Audit Log for classification decisions (History)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS (
    DECISION_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    DECISION_BY STRING,
    DECISION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS STRING,
    LABEL STRING,
    CONFIDENTIALITY_LEVEL NUMBER,
    INTEGRITY_LEVEL NUMBER,
    AVAILABILITY_LEVEL NUMBER,
    RATIONALE STRING,
    DETAILS VARIANT
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_admin;

    -- CLASSIFICATION_TASKS table
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS (
        TASK_ID STRING DEFAULT UUID_STRING(),
        DATASET_NAME STRING,
        ASSET_FULL_NAME STRING,
        ASSIGNED_TO STRING,
        STATUS STRING,
        CONFIDENTIALITY_LEVEL NUMBER,
        INTEGRITY_LEVEL NUMBER,
        AVAILABILITY_LEVEL NUMBER,
        DUE_DATE TIMESTAMP_NTZ,
        CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        DETAILS VARIANT
    );
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- CLASSIFICATION_AI_RESULTS table
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS (
        RESULT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
        ASSET_FULL_NAME STRING,
        PII_RELEVANT BOOLEAN DEFAULT FALSE,
        SOX_RELEVANT BOOLEAN DEFAULT FALSE,
        SOC2_RELEVANT BOOLEAN DEFAULT FALSE,
        CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
        primary key (RESULT_ID)
    );
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_public;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_admin;

    -- System Audit Log for general events (Syncs, Config changes)
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT (
        ID STRING DEFAULT UUID_STRING(),
        RESOURCE_ID STRING,
        ACTION STRING,
        ACTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        USER_ID STRING,
        NEW_STATE VARIANT
    );
    GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT TO APPLICATION ROLE app_public;
    GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT TO APPLICATION ROLE app_admin;

    -- View for user-specific classification tasks
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS(
    TASK_ID,
    DATASET_NAME,
    ASSET_FULL_NAME,
    OWNER,
    STATUS,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    DUE_DATE,
    CREATED_AT,
    UPDATED_AT,
    STATUS_LABEL,
    DETAILS
) AS
SELECT
    TASK_ID,
    COALESCE(DATASET_NAME, SPLIT_PART(COALESCE(ASSET_FULL_NAME, ''), '.', 3)) AS DATASET_NAME,
    ASSET_FULL_NAME,
    COALESCE(ASSIGNED_TO, '') AS OWNER,
    COALESCE(STATUS, 'Pending') AS STATUS,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    DUE_DATE,
    CREATED_AT,
    UPDATED_AT,
    CASE 
        WHEN UPPER(COALESCE(STATUS,'')) IN ('COMPLETED', 'APPROVED') THEN 'COMPLETED'
        WHEN UPPER(COALESCE(STATUS,'')) = 'CANCELLED' THEN 'CANCELLED'
        ELSE 'IN_PROGRESS'
    END AS STATUS_LABEL,
    DETAILS
FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS;

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- ============================================================================
    -- These commands should be run ONCE to create the application package before publishing
    --
    -- 1. Create application package:
    -- CREATE APPLICATION PACKAGE IF NOT EXISTS DATA_CLASSIFICATION_APP;
    --
    -- 2. Create initial version:
    -- CREATE VERSION IF NOT EXISTS V1_0 FROM APPLICATION PACKAGE DATA_CLASSIFICATION_APP
    --   USING '@~' AS STAGE;
    --
    -- 3. Grant privileges to the package:
    -- GRANT APPLICATION ROLE DATA_CLASSIFICATION_APP!app_admin TO ROLE SYSADMIN;
    -- GRANT APPLICATION ROLE DATA_CLASSIFICATION_APP!app_public TO ROLE SYSADMIN;
    --
    -- 4. Verify installation:
    -- SHOW APPLICATION PACKAGES LIKE 'DATA_CLASSIFICATION_APP';
    -- SHOW VERSIONS IN APPLICATION PACKAGE DATA_CLASSIFICATION_APP;
    --
    -- 5. Test installation (optional):
    -- CREATE APPLICATION DATA_CLASSIFICATION_APP_TEST FROM APPLICATION PACKAGE DATA_CLASSIFICATION_APP USING VERSION V1_0;
    --
    -- Note: Use the deploy.sh or deploy.ps1 scripts for automated deployment

    -- ============================================================================
    -- MISSING VIEWS FOR DATA CLASSIFICATION APP
    -- ============================================================================
    -- These views are referenced in the app but were missing from setup.sql

    -- View for Classification Review (Quality Review)
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW AS
    SELECT 
        REVIEW_ID AS ID,
        ASSET_FULL_NAME,
        PROPOSED_CLASSIFICATION AS CLASSIFICATION_LABEL,
        PROPOSED_C AS C,
        PROPOSED_I AS I,
        PROPOSED_A AS A,
        REVIEWER AS ASSIGNED_TO,
        STATUS,
        CREATED_BY,
        CREATED_AT AS CREATED_DATE,
        UPDATED_AT,
        REVIEW_DUE_DATE AS DUE_DATE,
        LAST_COMMENT AS BUSINESS_JUSTIFICATION,
        RISK_SCORE
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW
    ORDER BY CREATED_AT DESC;

    -- View for Classification History
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY AS
    SELECT 
        HISTORY_ID AS ID,
        ASSET_FULL_NAME,
        PREVIOUS_LABEL,
        NEW_LABEL AS CLASSIFICATION_LABEL,
        PREVIOUS_C,
        NEW_C AS C,
        PREVIOUS_I,
        NEW_I AS I,
        PREVIOUS_A,
        NEW_A AS A,
        CHANGE_TYPE,
        CHANGED_BY AS DECISION_MAKER,
        CHANGED_AT AS CREATED_DATE,
        RATIONALE,
        BATCH_ID
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY
    ORDER BY CHANGED_AT DESC;

    -- View for Reclassification Requests
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS AS
    SELECT 
        REQUEST_ID AS ID,
        ASSET_FULL_NAME,
        CURRENT_LABEL,
        REQUESTED_LABEL AS CLASSIFICATION_LABEL,
        REQUESTOR_USER AS REQUESTOR_EMAIL,
        REQUEST_TIMESTAMP AS REQUEST_DATE,
        STATUS,
        REVIEWER_USER AS REVIEWER,
        REVIEW_TIMESTAMP,
        REVIEWER_NOTES,
        REASON AS RATIONALE
    FROM DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS
    ORDER BY REQUEST_TIMESTAMP DESC;

    -- Also create VW_CLASSIFICATION_REVIEWS (plural) which is used in the service
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS(
        REVIEW_ID,
        ASSET_FULL_NAME,
        REQUESTED_LABEL,
        CONFIDENTIALITY_LEVEL,
        INTEGRITY_LEVEL,
        AVAILABILITY_LEVEL,
        REVIEWER,
        STATUS,
        CREATED_AT,
        UPDATED_AT,
        REVIEW_DUE_DATE,
        STATUS_LABEL,
        LAST_COMMENT
    ) AS
    SELECT 
        REVIEW_ID,
        ASSET_FULL_NAME,
        PROPOSED_CLASSIFICATION AS REQUESTED_LABEL,
        PROPOSED_C AS CONFIDENTIALITY_LEVEL,
        PROPOSED_I AS INTEGRITY_LEVEL,
        PROPOSED_A AS AVAILABILITY_LEVEL,
        REVIEWER,
        STATUS,
        CREATED_AT,
        UPDATED_AT,
        REVIEW_DUE_DATE,
        CASE 
            WHEN STATUS = 'Pending' THEN 'Pending Review'
            WHEN STATUS = 'In Review' THEN 'Under Review'
            WHEN STATUS = 'Approved' THEN 'Approved'
            WHEN STATUS = 'Rejected' THEN 'Rejected'
            ELSE STATUS
        END AS STATUS_LABEL,
        LAST_COMMENT 
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW;

    -- Grant permissions on all views
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- 4. AUTOMATED ASSET DISCOVERY & MERGE
    -- ============================================================================

    -- Stored Procedure for Automated Asset Discovery and Merge
    CREATE OR REPLACE PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS()
    RETURNS STRING
    LANGUAGE SQL
    EXECUTE AS CALLER
AS
$$
DECLARE
    ts_start TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    run_id STRING DEFAULT UUID_STRING();
    last_watermark TIMESTAMP_NTZ;
    new_watermark TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    db_name STRING;
    rows_inserted INTEGER DEFAULT 0;
    rows_updated INTEGER DEFAULT 0;
    merge_query_id STRING;
BEGIN
    -- 1. Initialize Watermark table if not exists
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK (
        LAST_WATERMARK TIMESTAMP_NTZ,
        LAST_RUN_ID STRING
    );

    SELECT COALESCE(MAX(LAST_WATERMARK), '2000-01-01 00:00:00') INTO :last_watermark 
    FROM DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK;

    -- 2. Cleanup: Remove forbidden system records from ASSETS
    DELETE FROM DATA_CLASSIFICATION_GOVERNANCE.ASSETS
    WHERE 
        UPPER(DATABASE_NAME) IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
        OR UPPER(SCHEMA_NAME) IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
        OR UPPER(FULLY_QUALIFIED_NAME) REGEXP '^(SNOWFLAKE|SNOWFLAKE_SAMPLE_DATA|INFORMATION_SCHEMA|DATA_CLASSIFICATION_GOVERNANCE)\\..*';

    -- 3. Discovery Staging
    CREATE OR REPLACE TEMPORARY TABLE DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (
        DB STRING NOT NULL,
        SCHEMA STRING NOT NULL, 
        NAME STRING NOT NULL,
        ASSET_TYPE STRING NOT NULL,
        FQN STRING,
        DESCRIPTION STRING,
        LAST_ALTERED TIMESTAMP_NTZ
    );

    -- Phase 1: Filtered Database Discovery
    SHOW DATABASES;
    LET rs_databases RESULTSET := (
        SELECT "name" AS DATABASE_NAME 
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) 
        WHERE COALESCE(UPPER("name"), '') NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
    );

    FOR db_row IN rs_databases DO
        db_name := db_row.DATABASE_NAME;
        
        INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
        VALUES (:db_name, '', :db_name, 'DATABASE', :db_name, 'Database Object', CURRENT_TIMESTAMP());
        
        -- Tables & Views discovery
        BEGIN
            EXECUTE IMMEDIATE 'SHOW TABLES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
            SELECT "database_name", "schema_name", "name", "kind", 
                   "database_name" || '.' || "schema_name" || '.' || "name", 
                   'Table/View Asset',
                   COALESCE("last_altered", "created_on")
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE COALESCE(UPPER("schema_name"), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
              AND "database_name" IS NOT NULL AND "schema_name" IS NOT NULL
              AND COALESCE("last_altered", "created_on") > :last_watermark;
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- USER PROCEDURES (Native Exclusion of System SPs)
        BEGIN
            EXECUTE IMMEDIATE 'SHOW USER PROCEDURES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
            SELECT "catalog_name", "schema_name", "name", 'STORED_PROCEDURE', 
                   "catalog_name" || '.' || "schema_name" || '.' || "name" || COALESCE("arguments", ''), 
                   'Stored Procedure',
                   "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE COALESCE(UPPER("schema_name"), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
              AND "catalog_name" IS NOT NULL AND "schema_name" IS NOT NULL
              AND "created_on" > :last_watermark;
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- USER FUNCTIONS (Native Exclusion of Built-in Functions)
        BEGIN
            EXECUTE IMMEDIATE 'SHOW USER FUNCTIONS IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, DESCRIPTION, LAST_ALTERED)
            SELECT "catalog_name", "schema_name", "name", 'FUNCTION', 
                   "catalog_name" || '.' || "schema_name" || '.' || "name" || COALESCE("arguments", ''),
                   'Returns: ' || "returns",
                   "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE COALESCE(UPPER("schema_name"), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
              AND "catalog_name" IS NOT NULL AND "schema_name" IS NOT NULL
              AND "created_on" > :last_watermark;
        EXCEPTION WHEN OTHER THEN NULL;
        END;
    END FOR;

    -- 4. Enriched Merge Source
    CREATE OR REPLACE TEMPORARY TABLE DATA_CLASSIFICATION_GOVERNANCE.TEMP_MERGE_SOURCE AS
    WITH ai_results_agg AS (
        -- Fixed: Use new ASSET_FULL_NAME schema
        SELECT 
            ASSET_FULL_NAME,
            -- Aggregate to Table Level: TRUE if ANY column is TRUE
            MAX(COALESCE(PII_RELEVANT, FALSE)) as PII_RELEVANT,
            MAX(COALESCE(SOX_RELEVANT, FALSE)) as SOX_RELEVANT,
            MAX(COALESCE(SOC2_RELEVANT, FALSE)) as SOC2_RELEVANT
        FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
        WHERE ASSET_FULL_NAME IS NOT NULL
        GROUP BY ASSET_FULL_NAME
    )
    SELECT 
        MD5(UPPER(TRIM(s.FQN))) as ASSET_ID,
        s.NAME as ASSET_NAME,
        s.ASSET_TYPE,
        s.DB as DATABASE_NAME,
        s.SCHEMA as SCHEMA_NAME,
        s.NAME as OBJECT_NAME,
        s.FQN as FULLY_QUALIFIED_NAME,
        'SYSTEM' as DATA_OWNER,
        s.DESCRIPTION as DATA_DESCRIPTION,
        -- Apply AI join only for Tables/Views
        CASE WHEN s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW') THEN ar.PII_RELEVANT ELSE NULL END as PII_RELEVANT, -- Use AI result if available, else existing
        CASE WHEN s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW') THEN ar.SOX_RELEVANT ELSE NULL END as SOX_RELEVANT, -- Use AI result if available, else existing
        CASE WHEN s.ASSET_TYPE IN ('TABLE', 'BASE TABLE', 'VIEW') THEN ar.SOC2_RELEVANT ELSE NULL END as SOC2_RELEVANT, -- Use AI result if available, else existing
        COALESCE(cd.LABEL, 'Unclassified') as CLASSIFICATION_LABEL,
        COALESCE(CAST(cd.C AS STRING), 'C1') as CONFIDENTIALITY_LEVEL,
        COALESCE(CAST(cd.I AS STRING), 'I1') as INTEGRITY_LEVEL,
        COALESCE(CAST(cd.A AS STRING), 'A1') as AVAILABILITY_LEVEL,
        CASE WHEN cd.LABEL IS NOT NULL THEN 'MANUAL' ELSE 'AUTO_DISCOVERY' END as CLASSIFICATION_METHOD
    FROM DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING s
    LEFT JOIN (
        SELECT ASSET_FULL_NAME, LABEL, CONFIDENTIALITY_LEVEL AS C, INTEGRITY_LEVEL AS I, AVAILABILITY_LEVEL AS A
        FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS
        WHERE STATUS = 'Approved'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(ASSET_FULL_NAME) ORDER BY DECISION_TIMESTAMP DESC) = 1
    ) cd ON UPPER(cd.ASSET_FULL_NAME) = UPPER(s.FQN)
    -- Fixed: FQN-based join with new schema
    LEFT JOIN ai_results_agg ar 
        ON UPPER(TRIM(ar.ASSET_FULL_NAME)) = UPPER(TRIM(s.FQN))
    WHERE COALESCE(UPPER(s.DB), '') NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE')
      AND COALESCE(UPPER(s.SCHEMA), '') NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');

    -- 5. Optional Debug Table for unmatched joins
    CREATE OR REPLACE TABLE DATA_CLASSIFICATION_GOVERNANCE.DEBUG_UNMATCHED_AI_RESULTS AS
    SELECT ar.*
    FROM (
        SELECT DISTINCT 
            ASSET_FULL_NAME
        FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
        WHERE ASSET_FULL_NAME IS NOT NULL
    ) ar
    LEFT JOIN DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING s
        ON UPPER(TRIM(ar.ASSET_FULL_NAME)) = UPPER(TRIM(s.FQN))
    WHERE s.FQN IS NULL;

    -- 6. Final MERGE with Change Detection
    MERGE INTO DATA_CLASSIFICATION_GOVERNANCE.ASSETS AS t
    USING DATA_CLASSIFICATION_GOVERNANCE.TEMP_MERGE_SOURCE AS s
    ON t.FULLY_QUALIFIED_NAME = s.FULLY_QUALIFIED_NAME
    WHEN MATCHED AND (
        t.ASSET_TYPE != s.ASSET_TYPE OR
        (t.PII_RELEVANT IS DISTINCT FROM s.PII_RELEVANT) OR
        (t.SOX_RELEVANT IS DISTINCT FROM s.SOX_RELEVANT) OR
        (t.SOC2_RELEVANT IS DISTINCT FROM s.SOC2_RELEVANT) OR
        t.CLASSIFICATION_LABEL != s.CLASSIFICATION_LABEL OR
        t.CONFIDENTIALITY_LEVEL != s.CONFIDENTIALITY_LEVEL OR
        t.INTEGRITY_LEVEL != s.INTEGRITY_LEVEL OR
        t.AVAILABILITY_LEVEL != s.AVAILABILITY_LEVEL OR
        COALESCE(t.DATA_DESCRIPTION, '') != COALESCE(s.DATA_DESCRIPTION, '')
    ) THEN
        UPDATE SET 
            t.ASSET_TYPE = s.ASSET_TYPE,
            t.DATA_DESCRIPTION = s.DATA_DESCRIPTION,
            t.PII_RELEVANT = s.PII_RELEVANT,
            t.SOX_RELEVANT = s.SOX_RELEVANT,
            t.SOC2_RELEVANT = s.SOC2_RELEVANT,
            t.CLASSIFICATION_LABEL = s.CLASSIFICATION_LABEL,
            t.CONFIDENTIALITY_LEVEL = s.CONFIDENTIALITY_LEVEL,
            t.INTEGRITY_LEVEL = s.INTEGRITY_LEVEL,
            t.AVAILABILITY_LEVEL = s.AVAILABILITY_LEVEL,
            t.RECORD_VERSION = t.RECORD_VERSION + 1,
            t.LAST_MODIFIED_TIMESTAMP = CURRENT_TIMESTAMP(),
            t.LAST_MODIFIED_BY = CURRENT_USER()
    WHEN NOT MATCHED THEN
        INSERT (
            ASSET_ID, ASSET_NAME, ASSET_TYPE, DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME, 
            FULLY_QUALIFIED_NAME, DATA_OWNER, DATA_DESCRIPTION, PII_RELEVANT, SOX_RELEVANT, SOC2_RELEVANT,
            CLASSIFICATION_LABEL, CONFIDENTIALITY_LEVEL, INTEGRITY_LEVEL, AVAILABILITY_LEVEL,
            CLASSIFICATION_METHOD, CREATED_TIMESTAMP, LAST_MODIFIED_TIMESTAMP, RECORD_VERSION, CREATED_BY, LAST_MODIFIED_BY
        )
        VALUES (
            s.ASSET_ID, s.ASSET_NAME, s.ASSET_TYPE, s.DATABASE_NAME, s.SCHEMA_NAME, s.OBJECT_NAME,
            s.FULLY_QUALIFIED_NAME, s.DATA_OWNER, s.DATA_DESCRIPTION, s.PII_RELEVANT, s.SOX_RELEVANT, s.SOC2_RELEVANT,
            s.CLASSIFICATION_LABEL, s.CONFIDENTIALITY_LEVEL, s.INTEGRITY_LEVEL, s.AVAILABILITY_LEVEL,
            s.CLASSIFICATION_METHOD, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_USER(), CURRENT_USER()
        );

    merge_query_id := LAST_QUERY_ID();
    SELECT "number of rows inserted", "number of rows updated" INTO :rows_inserted, :rows_updated
    FROM TABLE(RESULT_SCAN(:merge_query_id));

    -- 7. Update Watermark
    INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK (LAST_WATERMARK, LAST_RUN_ID)
    VALUES (:new_watermark, :run_id);

    RETURN 'MERGE_COMPLETE: ' || :rows_inserted || ' inserted, ' || :rows_updated || ' updated.';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'MERGE_FAILED: ' || SQLERRM;
END;
$$;

    -- Inventory All Levels View (Consolidated for Dashboard and Inventory pages)
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_ASSET_INVENTORY_ALL_LEVELS (
        LEVEL,
        "Database",
        "Schema",
        "Asset_Name",
        "Asset_Type",
        "Business_Unit",
        "Business_Domain",
        "Lifecycle",
        "Total_Assets",
        "Classified",
        "Has_Classification_Date",
        "Classification_Coverage",
        "Accuracy_Percent",
        "Timeliness_Percent",
        "Compliance_Status",
        "Owner_Coverage",
        "SLA_Breach_Assets",
        "New_Pending_Assets",
        "Column_Stats",
        "Column_Classification_Percent",
        "Data_Types",
        "Masking_Status",
        "Column_Tags",
        "Sensitive_Columns",
        "Avg_Days_To_Classify"
    ) AS
    WITH asset_metrics AS (
        SELECT 
            COALESCE(DATABASE_NAME, 'DATA_CLASSIFICATION_DB') as DATABASE_NAME,
            SCHEMA_NAME,
            ASSET_NAME,
            ASSET_TYPE,
            
            -- FIXED: Classification check matching dashboard logic
            -- An asset is classified if CLASSIFICATION_LABEL is not null and not in unclassified values
            CASE 
                WHEN CLASSIFICATION_LABEL IS NOT NULL 
                     AND UPPER(TRIM(CLASSIFICATION_LABEL)) NOT IN (
                         '', 'UNCLASSIFIED', 'UNKNOWN', 'PENDING', 'NONE', 
                         'NULL', 'N/A', 'TBD', 'ACTION REQUIRED', 'PENDING REVIEW'
                     )
                THEN 1 
                ELSE 0 
            END as IS_CLASSIFIED,
            
            -- Also track if there's a classification date for SLA calculation
            CASE WHEN CLASSIFICATION_DATE IS NOT NULL THEN 1 ELSE 0 END as HAS_CLASSIFICATION_DATE,
            
            -- Check for SLA compliance (classified within 5 days)
            CASE 
                WHEN CLASSIFICATION_DATE IS NOT NULL 
                     AND DATEDIFF(day, COALESCE(DATA_CREATION_DATE, CREATED_TIMESTAMP), CLASSIFICATION_DATE) <= 5 
                THEN 1
                ELSE 0
            END as IS_CLASSIFIED_WITHIN_SLA,
            
            -- Owner check
            CASE WHEN DATA_OWNER IS NOT NULL AND DATA_OWNER != '' THEN 1 ELSE 0 END as HAS_OWNER,
            
            -- Compliance flags enriched with native Snowflake PII discovery (EXTRACT_SEMANTIC_CATEGORIES results)
            CASE 
                WHEN PII_RELEVANT = TRUE THEN 1
                ELSE 0
            END as IS_PII,
            COALESCE(SOX_RELEVANT, FALSE) as IS_SOX,
            COALESCE(SOC2_RELEVANT, FALSE) as IS_SOC2,
            
            -- Classification details
            CLASSIFICATION_LABEL,
            CONFIDENTIALITY_LEVEL,
            INTEGRITY_LEVEL,
            AVAILABILITY_LEVEL,
            OVERALL_RISK_CLASSIFICATION,
            
            -- Review status (matching dashboard logic)
            CASE 
                WHEN UPPER(TRIM(COMPLIANCE_STATUS)) = 'COMPLIANT' THEN 'Compliant'
                WHEN REVIEW_STATUS IN ('Approved', 'Validated') THEN 'Reviewed'
                WHEN LAST_REVIEW_DATE IS NOT NULL 
                     AND DATEDIFF(day, LAST_REVIEW_DATE, CURRENT_DATE()) <= REVIEW_FREQUENCY_DAYS 
                THEN 'Compliant'
                WHEN NEXT_REVIEW_DATE < CURRENT_DATE() THEN 'Overdue'
                ELSE 'Pending'
            END as REVIEW_STATUS,
            
            HAS_EXCEPTION,
            
            -- Classification accuracy (from dashboard logic)
            CASE 
                WHEN CLASSIFICATION_LABEL IS NOT NULL 
                     AND UPPER(TRIM(CLASSIFICATION_LABEL)) NOT IN (
                         '', 'UNCLASSIFIED', 'UNKNOWN', 'PENDING', 'NONE', 
                         'NULL', 'N/A', 'TBD', 'ACTION REQUIRED', 'PENDING REVIEW'
                     )
                     AND REVIEW_STATUS IN ('Approved', 'Validated') 
                THEN 1 
                ELSE 0 
            END as IS_ACCURATE_CLASSIFICATION,
            
            -- Days since creation for SLA tracking
            DATEDIFF(day, COALESCE(DATA_CREATION_DATE, CREATED_TIMESTAMP), CURRENT_DATE()) as DAYS_SINCE_CREATION,
            
            -- Days to classify (if classified)
            CASE 
                WHEN CLASSIFICATION_DATE IS NOT NULL 
                THEN DATEDIFF(day, COALESCE(DATA_CREATION_DATE, CREATED_TIMESTAMP), CLASSIFICATION_DATE)
                ELSE NULL
            END as DAYS_TO_CLASSIFY,
            
            BUSINESS_UNIT,
            BUSINESS_DOMAIN,
            LIFECYCLE
            
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.ASSETS
        WHERE UPPER(TRIM(ASSET_TYPE)) IN ('TABLE', 'VIEW', 'BASE TABLE', 'DATABASE', 'STORED_PROCEDURE', 'FUNCTION')
    ),
    column_metrics AS (
        SELECT 
            -- Extract database, schema, and table from ASSET_FULL_NAME
            SPLIT_PART(ASSET_FULL_NAME, '.', 1) as DATABASE_NAME,
            SPLIT_PART(ASSET_FULL_NAME, '.', 2) as SCHEMA_NAME,
            SPLIT_PART(ASSET_FULL_NAME, '.', 3) as ASSET_NAME,
            
            -- Column counts
            COUNT(*) as TOTAL_COLUMNS,
            COUNT(CASE WHEN SENSITIVITY_CATEGORY_ID IS NOT NULL THEN 1 END) as CLASSIFIED_COLUMNS,
            COUNT(CASE WHEN PII_RELEVANT = TRUE THEN 1 END) as PII_COLUMNS,
            
            -- Data types (if available in the table, otherwise NULL)
            NULL as DATA_TYPES,
            
            -- Masking status (if available in the table, otherwise 0)
            0 as MASKED_COLUMNS,
            
            -- Tags (if available in the table, otherwise NULL)
            NULL as COLUMN_TAGS
            
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
        WHERE ASSET_FULL_NAME IS NOT NULL
          AND COLUMN_NAME IS NOT NULL
        GROUP BY 
            SPLIT_PART(ASSET_FULL_NAME, '.', 1),
            SPLIT_PART(ASSET_FULL_NAME, '.', 2),
            SPLIT_PART(ASSET_FULL_NAME, '.', 3)
    )
    SELECT 
        'DATABASE' as LEVEL,
        am.DATABASE_NAME as "Database",
        NULL as "Schema",
        NULL as "Asset_Name",
        'DATABASE' as "Asset_Type",
        NULL as "Business_Unit",
        NULL as "Business_Domain",
        NULL as "Lifecycle",
        COUNT(*) as "Total_Assets",
        SUM(am.IS_CLASSIFIED) as "Classified",
        SUM(am.HAS_CLASSIFICATION_DATE) as "Has_Classification_Date",
        
        -- FIXED: Classification percentage with emoji
        CASE 
            WHEN COUNT(*) > 0 THEN
                CONCAT(
                    ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0), '% ',
                    CASE 
                        WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0) >= 90 THEN '✅'
                        WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0) >= 70 THEN '☑️'
                        WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0) >= 50 THEN '⚠️'
                        ELSE '❌'
                    END
                )
            ELSE '0% ❌'
        END as "Classification_Coverage",
        
        -- Additional metrics from dashboard
        CONCAT(ROUND(SUM(am.IS_ACCURATE_CLASSIFICATION) * 100.0 / NULLIF(COUNT(*), 0), 0), '%') as "Accuracy_Percent",
        CONCAT(ROUND(SUM(am.IS_CLASSIFIED_WITHIN_SLA) * 100.0 / NULLIF(COUNT(*), 0), 0), '%') as "Timeliness_Percent",
        
        -- Compliance Status - using combined score like dashboard
        CASE 
            WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 90 THEN '✅ Excellent'
            WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 70 THEN '☑️ Good'
            WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 50 THEN '⚠️ Fair'
            ELSE '❌ Poor'
        END as "Compliance_Status",
        
        CONCAT(ROUND(SUM(am.HAS_OWNER) * 100.0 / NULLIF(COUNT(*), 0), 0), '%') as "Owner_Coverage",
        
        -- SLA Status
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION > 5 AND am.IS_CLASSIFIED = 0 THEN 1 END) as "SLA_Breach_Assets",
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION <= 5 AND am.IS_CLASSIFIED = 0 THEN 1 END) as "New_Pending_Assets",
        
        NULL as "Column_Stats",
        NULL as "Column_Classification_Percent",
        NULL as "Data_Types",
        NULL as "Masking_Status",
        NULL as "Column_Tags",
        CONCAT(SUM(am.IS_PII::INT), ' PII, ', SUM(am.IS_SOX::INT), ' SOX, ', SUM(am.IS_SOC2::INT), ' SOC2') as "Sensitive_Columns",
        
        -- Average days to classify (for classified assets)
        ROUND(AVG(am.DAYS_TO_CLASSIFY), 1) as "Avg_Days_To_Classify"
        
    FROM asset_metrics am
    GROUP BY am.DATABASE_NAME

    UNION ALL

    SELECT 
        'SCHEMA' as LEVEL,
        am.DATABASE_NAME,
        am.SCHEMA_NAME,
        NULL,
        'SCHEMA',
        NULL,
        NULL,
        NULL,
        COUNT(*),
        SUM(am.IS_CLASSIFIED),
        SUM(am.HAS_CLASSIFICATION_DATE),
        
        -- Schema Classification Coverage with emoji
        CASE 
            WHEN COUNT(*) > 0 THEN
                CONCAT(
                    ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0), '% ',
                    CASE 
                        WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0) >= 90 THEN '✅'
                        WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0) >= 70 THEN '☑️'
                        WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0) >= 50 THEN '⚠️'
                        ELSE '❌'
                    END
                )
            ELSE '0% ❌'
        END,
        
        CONCAT(ROUND(SUM(am.IS_ACCURATE_CLASSIFICATION) * 100.0 / NULLIF(COUNT(*), 0), 0), '%'),
        CONCAT(ROUND(SUM(am.IS_CLASSIFIED_WITHIN_SLA) * 100.0 / NULLIF(COUNT(*), 0), 0), '%'),
        
        CASE 
            WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 90 THEN '✅ Excellent'
            WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 70 THEN '☑️ Good'
            WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 50 THEN '⚠️ Fair'
            ELSE '❌ Poor'
        END,
        
        CONCAT(ROUND(SUM(am.HAS_OWNER) * 100.0 / NULLIF(COUNT(*), 0), 0), '%'),
        
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION > 5 AND am.IS_CLASSIFIED = 0 THEN 1 END),
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION <= 5 AND am.IS_CLASSIFIED = 0 THEN 1 END),
        
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        CONCAT(SUM(am.IS_PII::INT), ' PII, ', SUM(am.IS_SOX::INT), ' SOX, ', SUM(am.IS_SOC2::INT), ' SOC2'),
        
        ROUND(AVG(am.DAYS_TO_CLASSIFY), 1)
        
    FROM asset_metrics am
    WHERE am.SCHEMA_NAME IS NOT NULL
    GROUP BY am.DATABASE_NAME, am.SCHEMA_NAME

    UNION ALL

    SELECT 
        'ASSET' as LEVEL,
        am.DATABASE_NAME,
        am.SCHEMA_NAME,
        am.ASSET_NAME,
        am.ASSET_TYPE,
        am.BUSINESS_UNIT,
        am.BUSINESS_DOMAIN,
        am.LIFECYCLE,
        1,
        am.IS_CLASSIFIED,
        am.HAS_CLASSIFICATION_DATE,
        
        -- Asset Classification Coverage with emoji
        CONCAT(
            am.IS_CLASSIFIED * 100, '% ',
            CASE 
                WHEN am.IS_CLASSIFIED = 1 THEN '✅'
                ELSE '❌'
            END
        ),
        
        CONCAT(am.IS_ACCURATE_CLASSIFICATION * 100, '%'),
        CONCAT(am.IS_CLASSIFIED_WITHIN_SLA * 100, '%'),
        
        -- Asset-level compliance status
        CASE 
            WHEN am.IS_CLASSIFIED = 1 AND am.HAS_OWNER = 1 AND am.REVIEW_STATUS IN ('Compliant', 'Reviewed') AND COALESCE(am.HAS_EXCEPTION, FALSE) = FALSE
            THEN '✅ Excellent'
            WHEN am.IS_CLASSIFIED = 1 AND am.HAS_OWNER = 1 AND am.REVIEW_STATUS NOT IN ('Overdue')
            THEN '☑️ Good'
            WHEN am.IS_CLASSIFIED = 1 OR am.HAS_OWNER = 1
            THEN '⚠️ Fair'
            ELSE '❌ Poor'
        END,
        
        CONCAT(am.HAS_OWNER * 100, '%'),
        
        -- Asset SLA status
        CASE 
            WHEN am.DAYS_SINCE_CREATION > 5 AND am.IS_CLASSIFIED = 0 THEN 1
            ELSE 0
        END as "SLA_Breach_Assets",
        
        CASE 
            WHEN am.DAYS_SINCE_CREATION <= 5 AND am.IS_CLASSIFIED = 0 THEN 1
            ELSE 0
        END as "New_Pending_Assets",
        
        -- Column metrics
        CASE 
            WHEN cm.TOTAL_COLUMNS IS NOT NULL 
            THEN CONCAT(cm.CLASSIFIED_COLUMNS, '/', cm.TOTAL_COLUMNS, ' cols')
            ELSE NULL
        END as "Column_Stats",
        
        CASE 
            WHEN cm.TOTAL_COLUMNS IS NOT NULL 
            THEN CONCAT(ROUND(cm.CLASSIFIED_COLUMNS * 100.0 / NULLIF(cm.TOTAL_COLUMNS, 0), 0), '%')
            ELSE NULL
        END as "Column_Classification_Percent",
        
        cm.DATA_TYPES,
        
        CASE 
            WHEN cm.TOTAL_COLUMNS IS NOT NULL 
            THEN CONCAT(cm.MASKED_COLUMNS, '/', cm.TOTAL_COLUMNS, ' masked')
            ELSE NULL
        END as "Masking_Status",
        
        cm.COLUMN_TAGS,
        
        CONCAT(
            COALESCE(am.IS_PII::INT, 0), ' PII, ',
            COALESCE(am.IS_SOX::INT, 0), ' SOX, ',
            COALESCE(am.IS_SOC2::INT, 0), ' SOC2'
        ) as "Sensitive_Columns",
        
        am.DAYS_TO_CLASSIFY as "Avg_Days_To_Classify"
        
    FROM asset_metrics am
    LEFT JOIN column_metrics cm 
        ON am.DATABASE_NAME = cm.DATABASE_NAME 
        AND am.SCHEMA_NAME = cm.SCHEMA_NAME 
        AND am.ASSET_NAME = cm.ASSET_NAME
    WHERE am.ASSET_NAME IS NOT NULL
      AND UPPER(TRIM(am.ASSET_TYPE)) IN ('TABLE', 'VIEW', 'BASE TABLE', 'STORED_PROCEDURE', 'FUNCTION', 'STAGE');

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_ASSET_INVENTORY_ALL_LEVELS TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_ASSET_INVENTORY_ALL_LEVELS TO APPLICATION ROLE app_admin;
GRANT USAGE ON PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS() TO APPLICATION ROLE app_admin;

    -- ... (rest of the code remains the same)
    -- Snowflake Task to trigger the merge automatically (Daily at 2 AM)
    CREATE OR REPLACE TASK DATA_CLASSIFICATION_GOVERNANCE.TASK_DISCOVERY_SYNC
      WAREHOUSE = (SELECT CURRENT_WAREHOUSE())
      SCHEDULE = 'USING CRON 0 2 * * * UTC'
    AS
      CALL DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS();

    -- Stream for tracking new classification decisions
    CREATE OR REPLACE STREAM DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS 
      ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS;

    -- Task to trigger merge when new decisions are made (Near Real-Time)
    CREATE OR REPLACE TASK DATA_CLASSIFICATION_GOVERNANCE.TSK_MERGE_ASSETS_ON_DECISION
      WAREHOUSE = (SELECT CURRENT_WAREHOUSE())
      SCHEDULE = '1 MINUTE'
      WHEN SYSTEM$STREAM_HAS_DATA('DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS')
    AS
      CALL DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS();

    -- Resume tasks
    ALTER TASK DATA_CLASSIFICATION_GOVERNANCE.TASK_DISCOVERY_SYNC RESUME;
    ALTER TASK DATA_CLASSIFICATION_GOVERNANCE.TSK_MERGE_ASSETS_ON_DECISION RESUME;

    GRANT SELECT ON STREAM DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_public;
    GRANT SELECT ON STREAM DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- SETUP COMPLETE
    -- ============================================================================