-- ============================================================================
-- SNOWFLAKE NATIVE APP SETUP SCRIPT
-- ============================================================================
-- This script runs inside the Application instance during installation or upgrade.
-- It initializes the application's internal schemas, roles, and objects.

-- ----------------------------------------------------------------------------
-- 1. INTERNAL SCHEMAS & ROLES
-- ----------------------------------------------------------------------------

-- Create the main application versioned schema
CREATE OR ALTER VERSIONED SCHEMA app_schema;

-- The manifest defines 'app_public', we grant it usage on our internal schema
GRANT USAGE ON SCHEMA app_schema TO APPLICATION ROLE app_public;

-- ----------------------------------------------------------------------------
-- 2. APPLICATION OBJECTS (Streamlit)
-- ----------------------------------------------------------------------------

-- Create the Streamlit object pointing to the 'app' directory
CREATE OR REPLACE STREAMLIT app_schema.DATA_GOVERNANCE_APP
  FROM '/app'
  MAIN_FILE = 'streamlit_app.py';

-- Grant access to the app's roles
GRANT USAGE ON STREAMLIT app_schema.DATA_GOVERNANCE_APP TO APPLICATION ROLE app_public;
GRANT USAGE ON STREAMLIT app_schema.DATA_GOVERNANCE_APP TO APPLICATION ROLE app_admin;

-- ----------------------------------------------------------------------------
-- 3. INTERNAL METADATA STORAGE
-- ----------------------------------------------------------------------------
-- This schema stores governance decisions and cached inventory INTERNAL to the app.
CREATE OR ALTER VERSIONED SCHEMA DATA_CLASSIFICATION_GOVERNANCE;
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO APPLICATION ROLE app_public;
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO APPLICATION ROLE app_admin;

-- Initialize internal tables for metadata sharing/caching
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.ASSETS (
    ASSET_ID STRING,
    ASSET_NAME STRING,
    ASSET_TYPE STRING,
    OBJECT_NAME STRING,
    FULLY_QUALIFIED_NAME STRING,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    CLASSIFICATION_LABEL STRING,
    CLASSIFICATION_LABEL_COLOR STRING,
    CONFIDENTIALITY_LEVEL STRING,
    INTEGRITY_LEVEL STRING,
    AVAILABILITY_LEVEL STRING,
    DATA_DESCRIPTION STRING,
    DATA_OWNER STRING,
    DATA_OWNER_EMAIL STRING,
    DATA_CUSTODIAN STRING,
    DATA_CUSTODIAN_EMAIL STRING,
    BUSINESS_UNIT STRING,
    BUSINESS_PURPOSE STRING,
    BUSINESS_DOMAIN STRING,
    LIFECYCLE STRING,
    REVIEW_STATUS STRING,
    PII_RELEVANT BOOLEAN DEFAULT FALSE,
    SOX_RELEVANT BOOLEAN DEFAULT FALSE,
    SOC2_RELEVANT BOOLEAN DEFAULT FALSE,
    CLASSIFICATION_RATIONALE STRING,
    CONFIDENTIALITY_IMPACT_ASSESSMENT STRING,
    INTEGRITY_IMPACT_ASSESSMENT STRING,
    AVAILABILITY_IMPACT_ASSESSMENT STRING,
    CLASSIFICATION_DATE TIMESTAMP_NTZ,
    CLASSIFIED_BY STRING,
    CLASSIFICATION_METHOD STRING,
    LAST_RECLASSIFICATION_DATE TIMESTAMP_NTZ,
    RECLASSIFICATION_TRIGGER STRING,
    RECLASSIFICATION_COUNT NUMBER DEFAULT 0,
    PREVIOUS_CLASSIFICATION_LABEL STRING,
    LAST_REVIEW_DATE TIMESTAMP_NTZ,
    NEXT_REVIEW_DATE TIMESTAMP_NTZ,
    REVIEW_FREQUENCY_DAYS NUMBER DEFAULT 365,
    PEER_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
    PEER_REVIEWER STRING,
    MANAGEMENT_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
    MANAGEMENT_REVIEWER STRING,
    CONSISTENCY_CHECK_DATE TIMESTAMP_NTZ,
    CONSISTENCY_CHECK_STATUS STRING,
    REGULATORY STRING,
    OVERALL_RISK_CLASSIFICATION STRING,
    COMPLIANCE_STATUS STRING DEFAULT 'PENDING',
    NON_COMPLIANCE_REASON STRING,
    HAS_EXCEPTION BOOLEAN DEFAULT FALSE,
    EXCEPTION_TYPE STRING,
    EXCEPTION_JUSTIFICATION STRING,
    EXCEPTION_APPROVED_BY STRING,
    EXCEPTION_APPROVAL_DATE TIMESTAMP_NTZ,
    EXCEPTION_EXPIRY_DATE DATE,
    EXCEPTION_MITIGATION_MEASURES STRING,
    CORRECTIVE_ACTION_REQUIRED BOOLEAN DEFAULT FALSE,
    CORRECTIVE_ACTION_DESCRIPTION STRING,
    CORRECTIVE_ACTION_DUE_DATE TIMESTAMP_NTZ,
    SENSITIVE_DATA_USAGE_COUNT NUMBER DEFAULT 0,
    LAST_ACCESSED_DATE TIMESTAMP_NTZ,
    ACCESS_FREQUENCY STRING,
    NUMBER_OF_CONSUMERS NUMBER,
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED_BY STRING DEFAULT CURRENT_USER(),
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_VERSION NUMBER DEFAULT 1,
    ADDITIONAL_NOTES STRING
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ASSETS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.ASSETS TO APPLICATION ROLE app_admin;

-- Special Categories & Compliance Coverage View
CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE(
    CATEGORY,
    STATUS,
    RATE,
    ACTION,
    COMPLIANT_COUNT,
    VIOLATION_COUNT
) AS
WITH ai_sensitive_assets AS (
    SELECT DISTINCT
        a.SCHEMA_NAME,
        a.TABLE_NAME,
        CONCAT(CURRENT_DATABASE(), '.', a.SCHEMA_NAME, '.', a.TABLE_NAME) as ASSET_FULL_NAME,
        MAX(CASE WHEN a.AI_CATEGORY IN ('PII', 'PERSONAL_DATA', 'IDENTIFIER') THEN 1 ELSE 0 END) as HAS_PII,
        MAX(CASE WHEN a.AI_CATEGORY IN ('FINANCIAL', 'ACCOUNTING', 'FINANCE') OR
                      UPPER(a.AI_CATEGORY) LIKE '%FINANCIAL%' OR
                      UPPER(a.AI_CATEGORY) LIKE '%SOX%' OR
                      (a.DETAILS IS NOT NULL AND a.DETAILS:"sox_relevant"::BOOLEAN = TRUE) THEN 1 ELSE 0 END) as HAS_SOX,
        MAX(CASE WHEN UPPER(a.AI_CATEGORY) LIKE '%SECURITY%' OR
                      UPPER(a.AI_CATEGORY) LIKE '%CONTROL%' OR
                      UPPER(a.AI_CATEGORY) LIKE '%SOC2%' OR
                      (a.DETAILS IS NOT NULL AND (
                          a.DETAILS:"compliance_frameworks" LIKE '%SOC2%' OR
                          a.DETAILS:"compliance_frameworks" LIKE '%SOC 2%'
                      )) THEN 1 ELSE 0 END) as HAS_SOC2
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS a
    WHERE a.FINAL_CONFIDENCE >= 0.7
    GROUP BY a.SCHEMA_NAME, a.TABLE_NAME
),
asset_classifications AS (
    SELECT
        a.ASSET_ID,
        a.ASSET_NAME,
        a.FULLY_QUALIFIED_NAME,
        a.CLASSIFICATION_LABEL,
        a.CONFIDENTIALITY_LEVEL,
        a.INTEGRITY_LEVEL,
        a.AVAILABILITY_LEVEL,
        a.PII_RELEVANT,
        a.SOX_RELEVANT,
        a.SOC2_RELEVANT
    FROM DATA_CLASSIFICATION_GOVERNANCE.ASSETS a
),
joined_data AS (
    SELECT
        COALESCE(ac.FULLY_QUALIFIED_NAME, ai.ASSET_FULL_NAME) as ASSET_NAME,
        ac.CLASSIFICATION_LABEL,
        ac.CONFIDENTIALITY_LEVEL,
        CASE WHEN (ai.HAS_PII = 1 OR ac.PII_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_PII,
        CASE WHEN (ai.HAS_SOX = 1 OR ac.SOX_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_SOX,
        CASE WHEN (ai.HAS_SOC2 = 1 OR ac.SOC2_RELEVANT = TRUE) THEN 1 ELSE 0 END as FINAL_HAS_SOC2,
        CASE
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C1' THEN 1
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C2' THEN 2
            WHEN ac.CONFIDENTIALITY_LEVEL LIKE 'C3' THEN 3
            WHEN ac.CLASSIFICATION_LABEL = 'Unclassified' THEN 1
            WHEN ac.CLASSIFICATION_LABEL = 'Internal' THEN 1
            WHEN ac.CLASSIFICATION_LABEL = 'Restricted' THEN 2
            WHEN ac.CLASSIFICATION_LABEL = 'Confidential' THEN 3
            ELSE 1
        END as CONFIDENTIALITY_NUMERIC
    FROM ai_sensitive_assets ai
    FULL OUTER JOIN asset_classifications ac
        ON ai.ASSET_FULL_NAME = ac.FULLY_QUALIFIED_NAME
    WHERE (ai.HAS_PII = 1 OR ai.HAS_SOX = 1 OR ai.HAS_SOC2 = 1 OR
           ac.PII_RELEVANT = TRUE OR ac.SOX_RELEVANT = TRUE OR ac.SOC2_RELEVANT = TRUE)
),
compliance_calculation AS (
    SELECT
        COUNT(CASE WHEN FINAL_HAS_PII = 1 AND CONFIDENTIALITY_NUMERIC >= 2 THEN 1 END) as PII_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_PII = 1 AND CONFIDENTIALITY_NUMERIC < 2 THEN 1 END) as PII_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_PII = 1 THEN 1 END) as PII_TOTAL,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 AND CONFIDENTIALITY_NUMERIC >= 3 THEN 1 END) as SOC2_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 AND CONFIDENTIALITY_NUMERIC < 3 THEN 1 END) as SOC2_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOC2 = 1 THEN 1 END) as SOC2_TOTAL,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 AND CONFIDENTIALITY_NUMERIC >= 3 THEN 1 END) as SOX_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 AND CONFIDENTIALITY_NUMERIC < 3 THEN 1 END) as SOX_NON_COMPLIANT,
        COUNT(CASE WHEN FINAL_HAS_SOX = 1 THEN 1 END) as SOX_TOTAL,
        COUNT(*) as TOTAL_SENSITIVE_ASSETS
    FROM joined_data
)
SELECT
    'PII' as Category,
    CASE
        WHEN PII_TOTAL = 0 THEN '⚠️ Attention'
        WHEN PII_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN PII_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END as Status,
    CASE
        WHEN PII_TOTAL = 0 THEN '0%'
        ELSE ROUND(PII_COMPLIANT * 100.0 / NULLIF(PII_TOTAL, 0), 0) || '%'
    END as Rate,
    CASE
        WHEN PII_TOTAL = 0 OR PII_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END as Action,
    PII_COMPLIANT as COMPLIANT_COUNT,
    PII_NON_COMPLIANT as VIOLATION_COUNT
FROM compliance_calculation

UNION ALL

SELECT
    'SOC 2',
    CASE
        WHEN SOC2_TOTAL = 0 THEN '⚠️ Attention'
        WHEN SOC2_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN SOC2_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END,
    CASE
        WHEN SOC2_TOTAL = 0 THEN '0%'
        ELSE ROUND(SOC2_COMPLIANT * 100.0 / NULLIF(SOC2_TOTAL, 0), 0) || '%'
    END,
    CASE
        WHEN SOC2_TOTAL = 0 OR SOC2_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END,
    SOC2_COMPLIANT,
    SOC2_NON_COMPLIANT
FROM compliance_calculation

UNION ALL

SELECT
    'SOX',
    CASE
        WHEN SOX_TOTAL = 0 THEN '⚠️ Attention'
        WHEN SOX_NON_COMPLIANT = 0 THEN '✅ Compliant'
        WHEN SOX_COMPLIANT = 0 THEN '❌ Non-Compliant'
        ELSE '⚠️ Attention'
    END,
    CASE
        WHEN SOX_TOTAL = 0 THEN '0%'
        ELSE ROUND(SOX_COMPLIANT * 100.0 / NULLIF(SOX_TOTAL, 0), 0) || '%'
    END,
    CASE
        WHEN SOX_TOTAL = 0 OR SOX_NON_COMPLIANT > 0 THEN 'Review assets'
        ELSE 'None'
    END,
    SOX_COMPLIANT,
    SOX_NON_COMPLIANT
FROM compliance_calculation;

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_SPECIAL_CATEGORIES_COMPLIANCE TO APPLICATION ROLE app_admin;

-- Audit Log for general workflow events
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG (
    AUDIT_ID STRING DEFAULT UUID_STRING(),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_ID STRING,
    ACTION STRING,
    RESOURCE_TYPE STRING,
    RESOURCE_ID STRING,
    DETAILS VARIANT
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.AUDIT_LOG TO APPLICATION ROLE app_admin;

-- Table: CLASSIFICATION_AUDIT
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT (
    ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    RESOURCE_ID VARCHAR(16777216),
    ACTION VARCHAR(16777216),
    ACTION_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    USER_ID VARCHAR(16777216),
    PREVIOUS_STATE VARIANT,
    NEW_STATE VARIANT,
    REASON VARCHAR(1000),
    DECISION_MAKER VARCHAR(16777216),
    APPROVAL_REQUIRED BOOLEAN,
    APPROVED_BY VARCHAR(16777216),
    APPROVAL_TIMESTAMP TIMESTAMP_NTZ(9),
    COMPLIANCE_FLAGS VARCHAR(16777216)
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AUDIT TO APPLICATION ROLE app_admin;

-- Daily Audit Digests for tamper evidence
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS (
    DATE_KEY DATE PRIMARY KEY,
    RECORD_COUNT NUMBER,
    SHA256_HEX STRING,
    PREV_SHA256_HEX STRING,
    CHAIN_SHA256_HEX STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.DAILY_AUDIT_DIGESTS TO APPLICATION ROLE app_admin;

-- Reclassification Requests
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS (
    REQUEST_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    REQUESTOR_USER STRING,
    REQUEST_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CURRENT_LABEL STRING,
    REQUESTED_LABEL STRING,
    REASON STRING,
    STATUS STRING DEFAULT 'PENDING',
    REVIEWER_USER STRING,
    REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    REVIEWER_NOTES STRING
);

GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_admin;

-- Staging area for bulk classification requests (Quality Review)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW (
    REVIEW_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    PROPOSED_CLASSIFICATION STRING,
    PROPOSED_C NUMBER(38,0),
    PROPOSED_I NUMBER(38,0),
    PROPOSED_A NUMBER(38,0),
    REVIEWER STRING,
    STATUS STRING,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9),
    REVIEW_DUE_DATE TIMESTAMP_TZ(9),
    LAST_COMMENT STRING,
    RISK_SCORE NUMBER(38,2)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW TO APPLICATION ROLE app_admin;

-- Historical record of all classification changes
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY (
    HISTORY_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    PREVIOUS_LABEL STRING,
    NEW_LABEL STRING,
    PREVIOUS_C NUMBER,
    NEW_C NUMBER,
    PREVIOUS_I NUMBER,
    NEW_I NUMBER,
    PREVIOUS_A NUMBER,
    NEW_A NUMBER,
    CHANGE_TYPE STRING, -- BULK, MANUAL, AI
    CHANGED_BY STRING,
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RATIONALE STRING,
    BATCH_ID STRING
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY TO APPLICATION ROLE app_admin;

-- Audit Log for classification decisions (History)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS (
    DECISION_ID STRING DEFAULT UUID_STRING(),
    ASSET_FULL_NAME STRING,
    DECISION_BY STRING,
    DECISION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS STRING,
    LABEL STRING,
    CONFIDENTIALITY_LEVEL NUMBER,
    INTEGRITY_LEVEL NUMBER,
    AVAILABILITY_LEVEL NUMBER,
    RATIONALE STRING,
    DETAILS VARIANT
);

GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_public;
GRANT SELECT, INSERT ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS TO APPLICATION ROLE app_admin;

    -- CLASSIFICATION_TASKS table
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS (
        TASK_ID STRING DEFAULT UUID_STRING(),
        DATASET_NAME STRING,
        ASSET_FULL_NAME STRING,
        ASSIGNED_TO STRING,
        STATUS STRING,
        CONFIDENTIALITY_LEVEL NUMBER,
        INTEGRITY_LEVEL NUMBER,
        AVAILABILITY_LEVEL NUMBER,
        DUE_DATE TIMESTAMP_NTZ,
        CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        DETAILS VARIANT
    );
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- CLASSIFICATION_AI_RESULTS table
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS (
        RESULT_ID NUMBER IDENTITY(1,1),
        DATABASE_NAME STRING,
        SCHEMA_NAME STRING,
        TABLE_NAME STRING,
        COLUMN_NAME STRING,
        AI_CATEGORY STRING,
        SENSITIVITY_CATEGORY_ID STRING,
        SEMANTIC_CATEGORY STRING,
        FINAL_CONFIDENCE FLOAT,
        PII_RELEVANT BOOLEAN DEFAULT FALSE,
        SOX_RELEVANT BOOLEAN DEFAULT FALSE,
        SOC2_RELEVANT BOOLEAN DEFAULT FALSE,
        DETAILS VARIANT,
        CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_public;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS TO APPLICATION ROLE app_admin;

    -- View for user-specific classification tasks
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS(
    TASK_ID,
    DATASET_NAME,
    ASSET_FULL_NAME,
    OWNER,
    STATUS,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    DUE_DATE,
    CREATED_AT,
    UPDATED_AT,
    STATUS_LABEL,
    DETAILS
) AS
SELECT
    TASK_ID,
    COALESCE(DATASET_NAME, SPLIT_PART(COALESCE(ASSET_FULL_NAME, ''), '.', 3)) AS DATASET_NAME,
    ASSET_FULL_NAME,
    COALESCE(ASSIGNED_TO, '') AS OWNER,
    COALESCE(STATUS, 'Pending') AS STATUS,
    CONFIDENTIALITY_LEVEL,
    INTEGRITY_LEVEL,
    AVAILABILITY_LEVEL,
    DUE_DATE,
    CREATED_AT,
    UPDATED_AT,
    CASE 
        WHEN UPPER(COALESCE(STATUS,'')) IN ('COMPLETED', 'APPROVED') THEN 'COMPLETED'
        WHEN UPPER(COALESCE(STATUS,'')) = 'CANCELLED' THEN 'CANCELLED'
        ELSE 'IN_PROGRESS'
    END AS STATUS_LABEL,
    DETAILS
FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_TASKS;

GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- ============================================================================
    -- These commands should be run ONCE to create the application package before publishing
    --
    -- 1. Create application package:
    -- CREATE APPLICATION PACKAGE IF NOT EXISTS DATA_CLASSIFICATION_APP;
    --
    -- 2. Create initial version:
    -- CREATE VERSION IF NOT EXISTS V1_0 FROM APPLICATION PACKAGE DATA_CLASSIFICATION_APP
    --   USING '@~' AS STAGE;
    --
    -- 3. Grant privileges to the package:
    -- GRANT APPLICATION ROLE DATA_CLASSIFICATION_APP!app_admin TO ROLE SYSADMIN;
    -- GRANT APPLICATION ROLE DATA_CLASSIFICATION_APP!app_public TO ROLE SYSADMIN;
    --
    -- 4. Verify installation:
    -- SHOW APPLICATION PACKAGES LIKE 'DATA_CLASSIFICATION_APP';
    -- SHOW VERSIONS IN APPLICATION PACKAGE DATA_CLASSIFICATION_APP;
    --
    -- 5. Test installation (optional):
    -- CREATE APPLICATION DATA_CLASSIFICATION_APP_TEST FROM APPLICATION PACKAGE DATA_CLASSIFICATION_APP USING VERSION V1_0;
    --
    -- Note: Use the deploy.sh or deploy.ps1 scripts for automated deployment

    -- ============================================================================
    -- MISSING VIEWS FOR DATA CLASSIFICATION APP
    -- ============================================================================
    -- These views are referenced in the app but were missing from setup.sql

    -- View for Classification Review (Quality Review)
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW AS
    SELECT 
        REVIEW_ID AS ID,
        ASSET_FULL_NAME,
        PROPOSED_CLASSIFICATION AS CLASSIFICATION_LABEL,
        PROPOSED_C AS C,
        PROPOSED_I AS I,
        PROPOSED_A AS A,
        REVIEWER AS ASSIGNED_TO,
        STATUS,
        CREATED_BY,
        CREATED_AT AS CREATED_DATE,
        UPDATED_AT,
        REVIEW_DUE_DATE AS DUE_DATE,
        LAST_COMMENT AS BUSINESS_JUSTIFICATION,
        RISK_SCORE
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW
    ORDER BY CREATED_AT DESC;

    -- View for Classification History
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY AS
    SELECT 
        HISTORY_ID AS ID,
        ASSET_FULL_NAME,
        PREVIOUS_LABEL,
        NEW_LABEL AS CLASSIFICATION_LABEL,
        PREVIOUS_C,
        NEW_C AS C,
        PREVIOUS_I,
        NEW_I AS I,
        PREVIOUS_A,
        NEW_A AS A,
        CHANGE_TYPE,
        CHANGED_BY AS DECISION_MAKER,
        CHANGED_AT AS CREATED_DATE,
        RATIONALE,
        BATCH_ID
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY
    ORDER BY CHANGED_AT DESC;

    -- View for Reclassification Requests
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS AS
    SELECT 
        REQUEST_ID AS ID,
        ASSET_FULL_NAME,
        CURRENT_LABEL,
        REQUESTED_LABEL AS CLASSIFICATION_LABEL,
        REQUESTOR_USER AS REQUESTOR_EMAIL,
        REQUEST_TIMESTAMP AS REQUEST_DATE,
        STATUS,
        REVIEWER_USER AS REVIEWER,
        REVIEW_TIMESTAMP,
        REVIEWER_NOTES,
        REASON AS RATIONALE
    FROM DATA_CLASSIFICATION_GOVERNANCE.RECLASSIFICATION_REQUESTS
    ORDER BY REQUEST_TIMESTAMP DESC;

    -- Also create VW_CLASSIFICATION_REVIEWS (plural) which is used in the service
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS(
        REVIEW_ID,
        ASSET_FULL_NAME,
        REQUESTED_LABEL,
        CONFIDENTIALITY_LEVEL,
        INTEGRITY_LEVEL,
        AVAILABILITY_LEVEL,
        REVIEWER,
        STATUS,
        CREATED_AT,
        UPDATED_AT,
        REVIEW_DUE_DATE,
        STATUS_LABEL,
        LAST_COMMENT
    ) AS
    SELECT 
        REVIEW_ID,
        ASSET_FULL_NAME,
        PROPOSED_CLASSIFICATION AS REQUESTED_LABEL,
        PROPOSED_C AS CONFIDENTIALITY_LEVEL,
        PROPOSED_I AS INTEGRITY_LEVEL,
        PROPOSED_A AS AVAILABILITY_LEVEL,
        REVIEWER,
        STATUS,
        CREATED_AT,
        UPDATED_AT,
        REVIEW_DUE_DATE,
        CASE 
            WHEN STATUS = 'Pending' THEN 'Pending Review'
            WHEN STATUS = 'In Review' THEN 'Under Review'
            WHEN STATUS = 'Approved' THEN 'Approved'
            WHEN STATUS = 'Rejected' THEN 'Rejected'
            ELSE STATUS
        END AS STATUS_LABEL,
        LAST_COMMENT 
    FROM DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_REVIEW;

    -- Grant permissions on all views
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEW TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_HISTORY TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_RECLASSIFICATION_REQUESTS TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_CLASSIFICATION_REVIEWS TO APPLICATION ROLE app_admin;

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_MY_CLASSIFICATION_TASKS TO APPLICATION ROLE app_admin;

    -- ============================================================================
    -- 4. AUTOMATED ASSET DISCOVERY & MERGE
    -- ============================================================================

    -- Stored Procedure for Automated Asset Discovery and Merge
    CREATE OR REPLACE PROCEDURE DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS()
    RETURNS STRING
    LANGUAGE SQL
    EXECUTE AS CALLER
AS
$$
DECLARE
    ts_start TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    run_id STRING DEFAULT UUID_STRING();
    last_watermark TIMESTAMP_NTZ;
    new_watermark TIMESTAMP_NTZ;
    db_name STRING;
BEGIN
    -- Initialize Watermark table if not exists (Fully Qualified)
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK (
        LAST_WATERMARK TIMESTAMP_NTZ,
        LAST_RUN_ID STRING
    );

    SELECT COALESCE(MAX(LAST_WATERMARK), '2000-01-01 00:00:00') INTO :last_watermark 
    FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK;

    -- Discovery Staging (Fully Qualified)
    CREATE OR REPLACE TEMPORARY TABLE DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (
        DB STRING, SCHEMA STRING, NAME STRING, ASSET_TYPE STRING, FQN STRING, LAST_ALTERED TIMESTAMP_NTZ
    );

    -- Phase 1: Database Discovery
    SHOW DATABASES;
    LET rs_databases RESULTSET := (
        SELECT "name" AS DATABASE_NAME 
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) 
        WHERE "name" NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'INFORMATION_SCHEMA')
    );

    FOR db_row IN rs_databases DO
        db_name := db_row.DATABASE_NAME;
        
        -- Record Database as Asset
        INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, LAST_ALTERED)
        VALUES (:db_name, '', :db_name, 'DATABASE', :db_name, CURRENT_TIMESTAMP());
        
        -- 1. Tables
        BEGIN
            EXECUTE IMMEDIATE 'SHOW TABLES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, LAST_ALTERED)
            SELECT "database_name", "schema_name", "name", "kind", 
                   "database_name" || '.' || "schema_name" || '.' || "name", "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE "schema_name" NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- 2. Views
        BEGIN
            EXECUTE IMMEDIATE 'SHOW VIEWS IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, LAST_ALTERED)
            SELECT "database_name", "schema_name", "name", 'VIEW', 
                   "database_name" || '.' || "schema_name" || '.' || "name", "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE "schema_name" NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- 3. Stored Procedures
        BEGIN
            EXECUTE IMMEDIATE 'SHOW PROCEDURES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, LAST_ALTERED)
            SELECT "catalog_name", "schema_name", "name", 'STORED_PROCEDURE', 
                   "catalog_name" || '.' || "schema_name" || '.' || "name", "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE "schema_name" NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- 4. Functions
        BEGIN
            EXECUTE IMMEDIATE 'SHOW FUNCTIONS IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, LAST_ALTERED)
            SELECT "catalog_name", "schema_name", "name", 'FUNCTION', 
                   "catalog_name" || '.' || "schema_name" || '.' || "name", "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE "schema_name" NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');
        EXCEPTION WHEN OTHER THEN NULL;
        END;

        -- 5. Stages
        BEGIN
            EXECUTE IMMEDIATE 'SHOW STAGES IN DATABASE "' || db_name || '"';
            INSERT INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING (DB, SCHEMA, NAME, ASSET_TYPE, FQN, LAST_ALTERED)
            SELECT "database_name", "schema_name", "name", 'STAGE', 
                   "database_name" || '.' || "schema_name" || '.' || "name", "created_on"
            FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
            WHERE "schema_name" NOT IN ('INFORMATION_SCHEMA', 'DATA_CLASSIFICATION_GOVERNANCE');
        EXCEPTION WHEN OTHER THEN NULL;
        END;
    END FOR;

    -- Prepare Enriched Merge Source
    CREATE OR REPLACE TEMPORARY TABLE DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_MERGE_SOURCE AS
    SELECT 
        MD5(UPPER(TRIM(s.FQN))) as ASSET_ID,
        s.NAME as ASSET_NAME,
        s.ASSET_TYPE,
        s.DB as DATABASE_NAME,
        s.SCHEMA as SCHEMA_NAME,
        s.NAME as OBJECT_NAME,
        s.FQN as FULLY_QUALIFIED_NAME,
        'SYSTEM' as DATA_OWNER,
        COALESCE(ar.PII_RELEVANT, FALSE) as PII_RELEVANT,
        COALESCE(ar.SOX_RELEVANT, FALSE) as SOX_RELEVANT,
        COALESCE(ar.SOC2_RELEVANT, FALSE) as SOC2_RELEVANT,
        COALESCE(cd.LABEL, 'Unclassified') as CLASSIFICATION_LABEL,
        COALESCE(CAST(cd.C AS STRING), 'C1') as CONFIDENTIALITY_LEVEL,
        COALESCE(CAST(cd.I AS STRING), 'I1') as INTEGRITY_LEVEL,
        COALESCE(CAST(cd.A AS STRING), 'A1') as AVAILABILITY_LEVEL,
        CASE WHEN cd.LABEL IS NOT NULL THEN 'MANUAL' ELSE 'AUTO_DISCOVERY' END as CLASSIFICATION_METHOD
    FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING s
    LEFT JOIN (
        SELECT ASSET_FULL_NAME, LABEL, C, I, A
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS
        WHERE STATUS = 'APPROVED'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_FULL_NAME ORDER BY COALESCE(DECISION_TIMESTAMP, CREATED_AT) DESC) = 1
    ) cd ON cd.ASSET_FULL_NAME = s.FQN
    LEFT JOIN (
        SELECT DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, PII_RELEVANT, SOX_RELEVANT, SOC2_RELEVANT
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_AI_RESULTS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY DATABASE_NAME, SCHEMA_NAME, TABLE_NAME ORDER BY COALESCE(CREATED_TIMESTAMP, UPDATED_AT) DESC) = 1
    ) ar ON ar.DATABASE_NAME = s.DB AND ar.SCHEMA_NAME = s.SCHEMA AND ar.TABLE_NAME = s.NAME;


    -- Merge Logic
    MERGE INTO DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.ASSETS AS t
    USING DATA_CLASSIFICATION_GOVERNANCE.TEMP_MERGE_SOURCE AS s
    ON t.FULLY_QUALIFIED_NAME = s.FULLY_QUALIFIED_NAME
    WHEN MATCHED AND (
        t.ASSET_TYPE != s.ASSET_TYPE OR
        COALESCE(t.CLASSIFICATION_LABEL, '') != COALESCE(s.CLASSIFICATION_LABEL, '') OR
        COALESCE(t.PII_RELEVANT, FALSE) != COALESCE(s.PII_RELEVANT, FALSE) OR
        COALESCE(t.SOX_RELEVANT, FALSE) != COALESCE(s.SOX_RELEVANT, FALSE) OR 
        COALESCE(t.SOC2_RELEVANT, FALSE) != COALESCE(s.SOC2_RELEVANT, FALSE)
    ) THEN
        UPDATE SET 
            t.ASSET_TYPE = s.ASSET_TYPE,
            t.PII_RELEVANT = s.PII_RELEVANT,
            t.SOX_RELEVANT = s.SOX_RELEVANT,
            t.SOC2_RELEVANT = s.SOC2_RELEVANT,
            t.CLASSIFICATION_LABEL = s.CLASSIFICATION_LABEL,
            t.CONFIDENTIALITY_LEVEL = s.CONFIDENTIALITY_LEVEL,
            t.INTEGRITY_LEVEL = s.INTEGRITY_LEVEL,
            t.AVAILABILITY_LEVEL = s.AVAILABILITY_LEVEL,
            t.RECORD_VERSION = t.RECORD_VERSION + 1,
            t.LAST_MODIFIED_TIMESTAMP = CURRENT_TIMESTAMP(),
            t.LAST_MODIFIED_BY = CURRENT_USER()
    WHEN NOT MATCHED THEN
        INSERT (
            ASSET_ID, ASSET_NAME, ASSET_TYPE, DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME, 
            FULLY_QUALIFIED_NAME, DATA_OWNER, PII_RELEVANT, SOX_RELEVANT, SOC2_RELEVANT,
            CLASSIFICATION_LABEL, CONFIDENTIALITY_LEVEL, INTEGRITY_LEVEL, AVAILABILITY_LEVEL,
            CLASSIFICATION_METHOD, CREATED_TIMESTAMP, LAST_MODIFIED_TIMESTAMP, RECORD_VERSION, CREATED_BY, LAST_MODIFIED_BY
        )
        VALUES (
            s.ASSET_ID, s.ASSET_NAME, s.ASSET_TYPE, s.DATABASE_NAME, s.SCHEMA_NAME, s.OBJECT_NAME,
            s.FULLY_QUALIFIED_NAME, s.DATA_OWNER, s.PII_RELEVANT, s.SOX_RELEVANT, s.SOC2_RELEVANT,
            s.CLASSIFICATION_LABEL, s.CONFIDENTIALITY_LEVEL, s.INTEGRITY_LEVEL, s.AVAILABILITY_LEVEL,
            s.CLASSIFICATION_METHOD, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, CURRENT_USER(), CURRENT_USER()
        );

    -- Update Watermark
    SELECT MAX(LAST_ALTERED) INTO :new_watermark FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.TEMP_DISCOVERY_STAGING;
    IF (new_watermark IS NOT NULL) THEN
        INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.DISCOVERY_WATERMARK (LAST_WATERMARK, LAST_RUN_ID)
        VALUES (:new_watermark, :run_id);
    END IF;

    RETURN 'Success: Discovered objects across account.';
END;
$$;

    -- Inventory All Levels View (Consolidated for Dashboard and Inventory pages)
    CREATE OR REPLACE VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_ASSET_INVENTORY_ALL_LEVELS AS
    WITH asset_metrics AS (
        SELECT 
            DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME as ASSET_NAME, ASSET_TYPE,
            CASE 
                WHEN CLASSIFICATION_LABEL IS NOT NULL 
                     AND UPPER(TRIM(CLASSIFICATION_LABEL)) NOT IN ('', 'UNCLASSIFIED', 'UNKNOWN', 'PENDING', 'NONE', 'NULL', 'N/A', 'TBD', 'ACTION REQUIRED', 'PENDING REVIEW')
                THEN 1 ELSE 0 
            END as IS_CLASSIFIED,
            CASE WHEN CLASSIFICATION_DATE IS NOT NULL THEN 1 ELSE 0 END as HAS_CLASSIFICATION_DATE,
            CASE WHEN CLASSIFICATION_DATE IS NOT NULL AND DATEDIFF(day, COALESCE(DATA_CREATION_DATE, CREATED_TIMESTAMP), CLASSIFICATION_DATE) <= 5 THEN 1 ELSE 0 END as IS_CLASSIFIED_WITHIN_SLA,
            CASE WHEN DATA_OWNER IS NOT NULL AND DATA_OWNER != '' THEN 1 ELSE 0 END as HAS_OWNER,
            CASE WHEN PII_RELEVANT = TRUE THEN 1 ELSE 0 END as IS_PII,
            CASE WHEN SOX_RELEVANT = TRUE THEN 1 ELSE 0 END as IS_SOX,
            CASE WHEN SOC2_RELEVANT = TRUE THEN 1 ELSE 0 END as IS_SOC2,
            CASE WHEN REVIEW_STATUS IN ('Approved', 'Validated', 'Compliant') THEN 1 ELSE 0 END as IS_ACCURATE_CLASSIFICATION,
            DATEDIFF(day, CREATED_TIMESTAMP, CURRENT_DATE()) as DAYS_SINCE_CREATION,
            CASE WHEN CLASSIFICATION_DATE IS NOT NULL THEN DATEDIFF(day, CREATED_TIMESTAMP, CLASSIFICATION_DATE) ELSE NULL END as DAYS_TO_CLASSIFY
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.ASSETS
        WHERE UPPER(ASSET_TYPE) IN ('TABLE', 'VIEW', 'BASE TABLE', 'DATABASE', 'STORED_PROCEDURE', 'FUNCTION', 'STAGE')
    ),
    column_stats AS (
        SELECT 
            DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME,
            CONCAT(COUNT(*), ' columns') as COLUMN_STATS,
            CONCAT(SUM(CASE WHEN PII_RELEVANT THEN 1 ELSE 0 END), ' PII, ',
                   SUM(CASE WHEN SOX_RELEVANT THEN 1 ELSE 0 END), ' SOX, ',
                   SUM(CASE WHEN SOC2_RELEVANT THEN 1 ELSE 0 END), ' SOC2') as SENSITIVE_COLUMNS
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.ASSETS
        WHERE UPPER(ASSET_TYPE) IN ('TABLE', 'VIEW', 'BASE TABLE')
        GROUP BY 1, 2, 3
    )
    SELECT 
        'DATABASE' as LEVEL, am.DATABASE_NAME as "Database", NULL as "Schema", NULL as "Asset_Name", 'DATABASE' as "Asset_Type",
        COUNT(*) as "Total_Assets", SUM(am.IS_CLASSIFIED) as "Classified", SUM(am.HAS_CLASSIFICATION_DATE) as "Has_Classification_Date",
        CASE WHEN COUNT(*) > 0 THEN CONCAT(ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0), '%') ELSE '0%' END as "Classification_Coverage",
        CONCAT(ROUND(SUM(am.IS_ACCURATE_CLASSIFICATION) * 100.0 / NULLIF(COUNT(*), 0), 0), '%') as "Accuracy_Percent",
        CONCAT(ROUND(SUM(am.IS_CLASSIFIED_WITHIN_SLA) * 100.0 / NULLIF(COUNT(*), 0), 0), '%') as "Timeliness_Percent",
        CASE WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 90 THEN '✅ Excellent' ELSE '❌ Poor' END as "Compliance_Status",
        CONCAT(ROUND(SUM(am.HAS_OWNER) * 100.0 / NULLIF(COUNT(*), 0), 0), '%') as "Owner_Coverage",
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION > 5 AND am.IS_CLASSIFIED = 0 THEN 1 END) as "SLA_Breach_Assets",
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION <= 5 AND am.IS_CLASSIFIED = 0 THEN 1 END) as "New_Pending_Assets",
        CONCAT(SUM(am.IS_PII), ' PII, ', SUM(am.IS_SOX), ' SOX, ', SUM(am.IS_SOC2), ' SOC2') as "Sensitive_Columns",
        ROUND(AVG(am.DAYS_TO_CLASSIFY), 1) as "Avg_Days_To_Classify",
        NULL as "Column_Stats"
    FROM asset_metrics am GROUP BY am.DATABASE_NAME
    UNION ALL
    SELECT 
        'SCHEMA' as LEVEL, am.DATABASE_NAME, am.SCHEMA_NAME, NULL, 'SCHEMA',
        COUNT(*), SUM(am.IS_CLASSIFIED), SUM(am.HAS_CLASSIFICATION_DATE),
        CASE WHEN COUNT(*) > 0 THEN CONCAT(ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / COUNT(*), 0), '%') ELSE '0%' END,
        CONCAT(ROUND(SUM(am.IS_ACCURATE_CLASSIFICATION) * 100.0 / NULLIF(COUNT(*), 0), 0), '%'),
        CONCAT(ROUND(SUM(am.IS_CLASSIFIED_WITHIN_SLA) * 100.0 / NULLIF(COUNT(*), 0), 0), '%'),
        CASE WHEN ROUND(SUM(am.IS_CLASSIFIED) * 100.0 / NULLIF(COUNT(*), 0), 0) >= 90 THEN '✅ Excellent' ELSE '❌ Poor' END,
        CONCAT(ROUND(SUM(am.HAS_OWNER) * 100.0 / NULLIF(COUNT(*), 0), 0), '%'),
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION > 5 AND am.IS_CLASSIFIED = 0 THEN 1 END),
        COUNT(CASE WHEN am.DAYS_SINCE_CREATION <= 5 AND am.IS_CLASSIFIED = 0 THEN 1 END),
        CONCAT(SUM(am.IS_PII), ' PII, ', SUM(am.IS_SOX), ' SOX, ', SUM(am.IS_SOC2), ' SOC2'),
        ROUND(AVG(am.DAYS_TO_CLASSIFY), 1),
        NULL
    FROM asset_metrics am WHERE am.SCHEMA_NAME IS NOT NULL AND am.SCHEMA_NAME != '' GROUP BY am.DATABASE_NAME, am.SCHEMA_NAME
    UNION ALL
    SELECT 
        'ASSET' as LEVEL, am.DATABASE_NAME, am.SCHEMA_NAME, am.ASSET_NAME, am.ASSET_TYPE,
        1, am.IS_CLASSIFIED, am.HAS_CLASSIFICATION_DATE,
        CASE WHEN am.IS_CLASSIFIED = 1 THEN '100%' ELSE '0%' END,
        CASE WHEN am.IS_ACCURATE_CLASSIFICATION = 1 THEN '100%' ELSE '0%' END,
        CASE WHEN am.IS_CLASSIFIED_WITHIN_SLA = 1 THEN '100%' ELSE '0%' END,
        CASE WHEN am.IS_CLASSIFIED = 1 THEN '✅ Compliant' ELSE '❌ Pending' END,
        CASE WHEN am.HAS_OWNER = 1 THEN '100%' ELSE '0%' END,
        CASE WHEN am.DAYS_SINCE_CREATION > 5 AND am.IS_CLASSIFIED = 0 THEN 1 ELSE 0 END,
        CASE WHEN am.DAYS_SINCE_CREATION <= 5 AND am.IS_CLASSIFIED = 0 THEN 1 ELSE 0 END,
        COALESCE(cs.SENSITIVE_COLUMNS, CONCAT(am.IS_PII, ' PII, ', am.IS_SOX, ' SOX, ', am.IS_SOC2, ' SOC2')),
        am.DAYS_TO_CLASSIFY,
        cs.COLUMN_STATS
    FROM asset_metrics am
    LEFT JOIN column_stats cs ON am.DATABASE_NAME = cs.DATABASE_NAME AND am.SCHEMA_NAME = cs.SCHEMA_NAME AND am.ASSET_NAME = cs.OBJECT_NAME
    WHERE am.ASSET_NAME IS NOT NULL AND am.ASSET_NAME != '';

    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_ASSET_INVENTORY_ALL_LEVELS TO APPLICATION ROLE app_public;
    GRANT SELECT ON VIEW DATA_CLASSIFICATION_GOVERNANCE.VW_ASSET_INVENTORY_ALL_LEVELS TO APPLICATION ROLE app_admin;

    GRANT USAGE ON PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS() TO APPLICATION ROLE app_public;
    GRANT USAGE ON PROCEDURE DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS() TO APPLICATION ROLE app_admin;

    -- Snowflake Task to trigger the merge automatically (Daily at 2 AM)
    CREATE OR REPLACE TASK DATA_CLASSIFICATION_GOVERNANCE.TASK_DISCOVERY_SYNC
      WAREHOUSE = (SELECT CURRENT_WAREHOUSE())
      SCHEDULE = 'USING CRON 0 2 * * * UTC'
    AS
      CALL DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS();

    -- Stream on CLASSIFICATION_DECISIONS to track new decisions
    CREATE OR REPLACE STREAM DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS
      ON TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS
      APPEND_ONLY = TRUE;

    -- Dummy sink to advance the stream
    CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS_SINK (
      DECISION_ID STRING
    );

    -- Task triggered by stream to immediately run discovery & merge
    CREATE OR REPLACE TASK DATA_CLASSIFICATION_GOVERNANCE.TSK_MERGE_ASSETS_ON_DECISION
      WAREHOUSE = (SELECT CURRENT_WAREHOUSE())
      SCHEDULE = '1 MINUTE'
      WHEN SYSTEM$STREAM_HAS_DATA('DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS')
    AS
    BEGIN
      INSERT INTO DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_DECISIONS_SINK
      SELECT DECISION_ID FROM DATA_CLASSIFICATION_GOVERNANCE.STR_CLASSIFICATION_DECISIONS;

      CALL DATA_CLASSIFICATION_GOVERNANCE.SP_MERGE_ASSETS();
    END;

    -- ============================================================================
    -- SETUP COMPLETE
    -- ============================================================================