-- ============================================================================
-- FINAL COMPREHENSIVE SCHEMA FIX
-- Adds ALL missing columns based on actual schema requirements
-- ============================================================================

USE DATABASE DATA_CLASSIFICATION_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- ============================================================================
-- PART 1: FIX SENSITIVITY_CATEGORIES - Add missing columns
-- ============================================================================

-- Add COLOR_CODE column (CRITICAL - referenced in Python code)
ALTER TABLE SENSITIVITY_CATEGORIES 
ADD COLUMN IF NOT EXISTS COLOR_CODE VARCHAR(16) DEFAULT '#808080' 
COMMENT 'Hex color code for UI display (e.g., #FF5733)';

-- Add DEFAULT_THRESHOLD column (referenced in Python code)
ALTER TABLE SENSITIVITY_CATEGORIES
ADD COLUMN IF NOT EXISTS DEFAULT_THRESHOLD FLOAT DEFAULT 0.45
COMMENT 'Default detection threshold (same as DETECTION_THRESHOLD)';

-- Update COLOR_CODE with policy-based colors
UPDATE SENSITIVITY_CATEGORIES
SET COLOR_CODE = CASE 
    WHEN UPPER(POLICY_GROUP) = 'PII' THEN '#FF5733'      -- Red for PII
    WHEN UPPER(POLICY_GROUP) = 'SOX' THEN '#FFA500'      -- Orange for SOX
    WHEN UPPER(POLICY_GROUP) = 'SOC2' THEN '#4169E1'     -- Blue for SOC2
    WHEN CONFIDENTIALITY_LEVEL >= 3 THEN '#DC143C'       -- Crimson for high
    WHEN CONFIDENTIALITY_LEVEL = 2 THEN '#FF8C00'        -- Dark orange for medium
    WHEN CONFIDENTIALITY_LEVEL = 1 THEN '#FFD700'        -- Gold for low
    ELSE '#808080'                                        -- Gray default
END
WHERE COLOR_CODE IS NULL OR COLOR_CODE = '#808080';

-- Sync DEFAULT_THRESHOLD with DETECTION_THRESHOLD
UPDATE SENSITIVITY_CATEGORIES
SET DEFAULT_THRESHOLD = COALESCE(DETECTION_THRESHOLD, 0.45)
WHERE DEFAULT_THRESHOLD IS NULL;

-- ============================================================================
-- PART 2: FIX SENSITIVE_PATTERNS - Add PATTERN_STRING column
-- ============================================================================

-- Add PATTERN_STRING as alias/copy of PATTERN_REGEX (Python code references both)
ALTER TABLE SENSITIVE_PATTERNS
ADD COLUMN IF NOT EXISTS PATTERN_STRING VARCHAR(16777216)
COMMENT 'Alias for PATTERN_REGEX for backward compatibility';

-- Copy PATTERN_REGEX to PATTERN_STRING where null
UPDATE SENSITIVE_PATTERNS
SET PATTERN_STRING = PATTERN_REGEX
WHERE PATTERN_STRING IS NULL AND PATTERN_REGEX IS NOT NULL;

-- ============================================================================
-- PART 3: CREATE CLASSIFICATION_AI_RESULTS if it doesn't exist
-- ============================================================================

CREATE TABLE IF NOT EXISTS CLASSIFICATION_AI_RESULTS (
    RESULT_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    DATABASE_NAME VARCHAR(16777216) COMMENT 'Database name',
    SCHEMA_NAME VARCHAR(16777216) COMMENT 'Schema name',
    TABLE_NAME VARCHAR(16777216) COMMENT 'Table name',
    COLUMN_NAME VARCHAR(16777216) COMMENT 'Column name',
    AI_CATEGORY VARCHAR(16777216) COMMENT 'Detected category',
    SENSITIVITY_CATEGORY_ID VARCHAR(16777216) COMMENT 'FK to SENSITIVITY_CATEGORIES',
    REGEX_CONFIDENCE FLOAT COMMENT 'Pattern match confidence',
    KEYWORD_CONFIDENCE FLOAT COMMENT 'Keyword match confidence',
    ML_CONFIDENCE FLOAT COMMENT 'ML model confidence',
    SEMANTIC_CONFIDENCE FLOAT COMMENT 'Semantic similarity confidence',
    FINAL_CONFIDENCE FLOAT COMMENT 'Combined confidence score',
    SEMANTIC_CATEGORY VARCHAR(16777216) COMMENT 'Semantic category detected',
    MODEL_VERSION VARCHAR(16777216) COMMENT 'Model version used',
    DETAILS VARIANT COMMENT 'Additional detection details',
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RESULT_ID)
);

-- Add missing columns to existing CLASSIFICATION_AI_RESULTS table
ALTER TABLE CLASSIFICATION_AI_RESULTS
ADD COLUMN IF NOT EXISTS DATABASE_NAME VARCHAR(16777216) 
COMMENT 'Database name for the classified table';

ALTER TABLE CLASSIFICATION_AI_RESULTS
ADD COLUMN IF NOT EXISTS SCHEMA_NAME VARCHAR(16777216) 
COMMENT 'Schema name for the classified table';

ALTER TABLE CLASSIFICATION_AI_RESULTS
ADD COLUMN IF NOT EXISTS SENSITIVITY_CATEGORY_ID VARCHAR(16777216)
COMMENT 'Foreign key to SENSITIVITY_CATEGORIES.CATEGORY_ID';

-- ============================================================================
-- PART 4: FIX BROKEN REGEX PATTERNS
-- ============================================================================

-- Fix the specific malformed account pattern
UPDATE SENSITIVE_PATTERNS
SET PATTERN_REGEX = '(?:account|acct).*?\\d{4,12}',
    PATTERN_STRING = '(?:account|acct).*?\\d{4,12}',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE (PATTERN_REGEX LIKE '%y(?:account|acct)%'
   OR PATTERN_REGEX LIKE '%d{4,12}y%'
   OR PATTERN_STRING LIKE '%y(?:account|acct)%'
   OR PATTERN_STRING LIKE '%d{4,12}y%');

-- Fix unescaped \d patterns in PATTERN_REGEX
UPDATE SENSITIVE_PATTERNS
SET PATTERN_REGEX = REPLACE(PATTERN_REGEX, 'd{', '\\d{'),
    PATTERN_STRING = REPLACE(COALESCE(PATTERN_STRING, PATTERN_REGEX), 'd{', '\\d{'),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE PATTERN_REGEX LIKE '%d{%' 
  AND PATTERN_REGEX NOT LIKE '%\\d{%'
  AND IS_ACTIVE = TRUE;

-- Fix unescaped \w patterns
UPDATE SENSITIVE_PATTERNS
SET PATTERN_REGEX = REPLACE(PATTERN_REGEX, 'w+', '\\w+'),
    PATTERN_STRING = REPLACE(COALESCE(PATTERN_STRING, PATTERN_REGEX), 'w+', '\\w+'),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE PATTERN_REGEX LIKE '%w+%' 
  AND PATTERN_REGEX NOT LIKE '%\\w+%'
  AND IS_ACTIVE = TRUE;

-- Fix unescaped \s patterns
UPDATE SENSITIVE_PATTERNS
SET PATTERN_REGEX = REPLACE(PATTERN_REGEX, 's+', '\\s+'),
    PATTERN_STRING = REPLACE(COALESCE(PATTERN_STRING, PATTERN_REGEX), 's+', '\\s+'),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE PATTERN_REGEX LIKE '%s+%' 
  AND PATTERN_REGEX NOT LIKE '%\\s+%'
  AND IS_ACTIVE = TRUE;

-- ============================================================================
-- PART 5: GRANT PERMISSIONS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO ROLE SYSADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO ROLE ACCOUNTADMIN;

-- ============================================================================
-- PART 6: VERIFICATION QUERIES
-- ============================================================================

-- Verify SENSITIVITY_CATEGORIES has all required columns
SELECT '✓ SENSITIVITY_CATEGORIES Columns:' AS CHECK_TYPE;
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVITY_CATEGORIES'
  AND COLUMN_NAME IN ('COLOR_CODE', 'DEFAULT_THRESHOLD', 'POLICY_GROUP', 
                      'WEIGHT_EMBEDDING', 'WEIGHT_KEYWORD', 'WEIGHT_PATTERN',
                      'CATEGORY_ID', 'CATEGORY_NAME', 'DESCRIPTION')
ORDER BY COLUMN_NAME;

-- Verify SENSITIVE_PATTERNS has both PATTERN_REGEX and PATTERN_STRING
SELECT '✓ SENSITIVE_PATTERNS Columns:' AS CHECK_TYPE;
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_PATTERNS'
  AND COLUMN_NAME IN ('PATTERN_REGEX', 'PATTERN_STRING', 'CATEGORY_ID', 'SENSITIVITY_WEIGHT')
ORDER BY COLUMN_NAME;

-- Verify CLASSIFICATION_AI_RESULTS has all required columns
SELECT '✓ CLASSIFICATION_AI_RESULTS Columns:' AS CHECK_TYPE;
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'CLASSIFICATION_AI_RESULTS'
  AND COLUMN_NAME IN ('DATABASE_NAME', 'SCHEMA_NAME', 'TABLE_NAME', 'COLUMN_NAME',
                      'SENSITIVITY_CATEGORY_ID', 'FINAL_CONFIDENCE', 'DETAILS')
ORDER BY COLUMN_NAME;

-- Check for broken regex patterns
SELECT '✓ Regex Pattern Validation:' AS CHECK_TYPE;
SELECT 
    PATTERN_ID,
    PATTERN_NAME,
    PATTERN_REGEX,
    PATTERN_STRING,
    CASE 
        WHEN PATTERN_REGEX LIKE '%y(?:%' THEN '❌ NEEDS FIX'
        WHEN PATTERN_REGEX LIKE '%d{%' AND PATTERN_REGEX NOT LIKE '%\\d{%' THEN '❌ NEEDS FIX'
        ELSE '✅ OK'
    END AS STATUS
FROM SENSITIVE_PATTERNS
WHERE IS_ACTIVE = TRUE
ORDER BY STATUS DESC, PATTERN_NAME
LIMIT 10;

-- Verify COLOR_CODE distribution
SELECT '✓ COLOR_CODE Distribution:' AS CHECK_TYPE;
SELECT 
    POLICY_GROUP,
    COLOR_CODE,
    COUNT(*) AS COUNT
FROM SENSITIVITY_CATEGORIES
WHERE IS_ACTIVE = TRUE
GROUP BY POLICY_GROUP, COLOR_CODE
ORDER BY POLICY_GROUP;

SELECT '✅ SCHEMA FIX COMPLETED!' AS STATUS;
