-- ============================================================================
-- REFERENCE SCHEMA DDL
-- Provided by User on 2025-11-30
-- ============================================================================

USE DATABASE DATA_CLASSIFICATION_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

create or replace TABLE SENSITIVITY_CATEGORIES (
	CATEGORY_ID VARCHAR(16777216) NOT NULL,
	CATEGORY_NAME VARCHAR(16777216) NOT NULL,
	DESCRIPTION VARCHAR(16777216),
	CONFIDENTIALITY_LEVEL NUMBER(1,0) DEFAULT 1,
	INTEGRITY_LEVEL NUMBER(1,0) DEFAULT 1,
	AVAILABILITY_LEVEL NUMBER(1,0) DEFAULT 1,
	DETECTION_THRESHOLD FLOAT DEFAULT 0.5,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_BY VARCHAR(16777216) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9),
	VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	POLICY_GROUP VARCHAR(50) COMMENT 'High-level policy group (PII, SOX, SOC2, etc.)',
	WEIGHT_EMBEDDING FLOAT DEFAULT 0.6 COMMENT 'Weight for semantic embedding score (0.0-1.0)',
	WEIGHT_KEYWORD FLOAT DEFAULT 0.25 COMMENT 'Weight for keyword match score (0.0-1.0)',
	WEIGHT_PATTERN FLOAT DEFAULT 0.15 COMMENT 'Weight for regex pattern match score (0.0-1.0)',
	MULTI_LABEL BOOLEAN DEFAULT TRUE COMMENT 'Whether this category can be detected alongside others',
	primary key (CATEGORY_ID)
);

create or replace TABLE SENSITIVE_PATTERNS (
	PATTERN_ID VARCHAR(16777216) NOT NULL,
	CATEGORY_ID VARCHAR(16777216) NOT NULL,
	PATTERN_NAME VARCHAR(16777216) NOT NULL,
	DESCRIPTION VARCHAR(16777216),
	SENSITIVITY_WEIGHT FLOAT DEFAULT 0.5,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	PATTERN_REGEX VARCHAR(16777216),
	SENSITIVITY_TYPE VARCHAR(16777216),
	EXAMPLE VARCHAR(16777216),
	primary key (PATTERN_ID),
	foreign key (CATEGORY_ID) references SENSITIVITY_CATEGORIES(CATEGORY_ID)
);

create or replace TABLE SENSITIVE_KEYWORDS (
	KEYWORD_ID VARCHAR(16777216),
	CATEGORY_ID VARCHAR(16777216),
	KEYWORD_STRING VARCHAR(16777216),
	MATCH_TYPE VARCHAR(16777216),
	SENSITIVITY_WEIGHT FLOAT,
	IS_ACTIVE BOOLEAN,
	CREATED_BY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9),
	VERSION_NUMBER NUMBER(38,0)
);

create or replace TABLE SENSITIVE_AUDIT (
	AUDIT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TABLE_NAME VARCHAR(16777216),
	COLUMN_NAME VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	CONFIDENCE NUMBER(38,0),
	CIA VARCHAR(16777216),
	BUNDLE_DETECTED BOOLEAN,
	SCANNED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (AUDIT_ID)
);

create or replace TABLE RECLASSIFICATION_REQUESTS (
	ID VARCHAR(16777216),
	ASSET_FULL_NAME VARCHAR(16777216),
	TRIGGER_TYPE VARCHAR(16777216),
	CURRENT_CLASSIFICATION VARCHAR(16777216),
	CURRENT_C NUMBER(38,0),
	CURRENT_I NUMBER(38,0),
	CURRENT_A NUMBER(38,0),
	PROPOSED_CLASSIFICATION VARCHAR(16777216),
	PROPOSED_C NUMBER(38,0),
	PROPOSED_I NUMBER(38,0),
	PROPOSED_A NUMBER(38,0),
	STATUS VARCHAR(16777216),
	VERSION NUMBER(38,0),
	JUSTIFICATION VARCHAR(16777216),
	CREATED_BY VARCHAR(16777216),
	APPROVED_BY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE COMPLIANCE_MAPPING (
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	CATEGORY_ID VARCHAR(16777216) NOT NULL,
	COMPLIANCE_STANDARD VARCHAR(16777216) NOT NULL,
	REQUIREMENT_IDS VARIANT,
	DESCRIPTION VARCHAR(16777216),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	VERSION_NUMBER NUMBER(38,0) DEFAULT 1,
	SENSITIVITY_TYPE VARCHAR(16777216),
	COMPLIANCE_FRAMEWORK VARCHAR(16777216),
	REQUIRED_ACTIONS VARCHAR(16777216),
	primary key (MAPPING_ID),
	foreign key (CATEGORY_ID) references SENSITIVITY_CATEGORIES(CATEGORY_ID)
);

create or replace TABLE CLASSIFICATION_TASKS (
	TASK_ID VARCHAR(16777216),
	DATASET_NAME VARCHAR(16777216),
	ASSET_FULL_NAME VARCHAR(16777216),
	ASSIGNED_TO VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CONFIDENTIALITY_LEVEL VARCHAR(16777216),
	INTEGRITY_LEVEL VARCHAR(16777216),
	AVAILABILITY_LEVEL VARCHAR(16777216),
	DUE_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DETAILS VARIANT
);

create or replace TABLE CLASSIFICATION_REVIEW (
	REVIEW_ID VARCHAR(16777216) NOT NULL DEFAULT UUID_STRING(),
	ASSET_FULL_NAME VARCHAR(16777216),
	PROPOSED_CLASSIFICATION VARCHAR(16777216),
	PROPOSED_C NUMBER(38,0),
	PROPOSED_I NUMBER(38,0),
	PROPOSED_A NUMBER(38,0),
	REVIEWER VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CREATED_BY VARCHAR(16777216),
	CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_TZ(9),
	REVIEW_DUE_DATE TIMESTAMP_TZ(9),
	LAST_COMMENT VARCHAR(16777216),
	RISK_SCORE NUMBER(38,2),
	primary key (REVIEW_ID)
);

create or replace TABLE ASSETS (
	ASSET_ID VARCHAR(100) NOT NULL,
	ASSET_NAME VARCHAR(500) NOT NULL,
	ASSET_TYPE VARCHAR(50) NOT NULL,
	DATABASE_NAME VARCHAR(255),
	SCHEMA_NAME VARCHAR(255),
	OBJECT_NAME VARCHAR(255),
	FULLY_QUALIFIED_NAME VARCHAR(1000),
	BUSINESS_UNIT VARCHAR(100),
	DATA_OWNER VARCHAR(100) NOT NULL,
	DATA_OWNER_EMAIL VARCHAR(255),
	DATA_CUSTODIAN VARCHAR(100),
	DATA_CUSTODIAN_EMAIL VARCHAR(255),
	BUSINESS_PURPOSE VARCHAR(2000),
	DATA_DESCRIPTION VARCHAR(4000),
	CLASSIFICATION_LABEL VARCHAR(20),
	CLASSIFICATION_LABEL_COLOR VARCHAR(20),
	CONFIDENTIALITY_LEVEL VARCHAR(2),
	INTEGRITY_LEVEL VARCHAR(2),
	AVAILABILITY_LEVEL VARCHAR(2),
	OVERALL_RISK_CLASSIFICATION VARCHAR(20),
	CONTAINS_PII BOOLEAN DEFAULT FALSE,
	CONTAINS_FINANCIAL_DATA BOOLEAN DEFAULT FALSE,
	SOX_RELEVANT BOOLEAN DEFAULT FALSE,
	SOC_RELEVANT BOOLEAN DEFAULT FALSE,
	REGULATORY_DATA BOOLEAN DEFAULT FALSE,
	CLASSIFICATION_RATIONALE VARCHAR(4000),
	CONFIDENTIALITY_IMPACT_ASSESSMENT VARCHAR(2000),
	INTEGRITY_IMPACT_ASSESSMENT VARCHAR(2000),
	AVAILABILITY_IMPACT_ASSESSMENT VARCHAR(2000),
	CLASSIFICATION_DATE TIMESTAMP_NTZ(9),
	CLASSIFIED_BY VARCHAR(100),
	CLASSIFICATION_METHOD VARCHAR(50),
	CLASSIFICATION_REVIEWED_BY VARCHAR(100),
	CLASSIFICATION_REVIEW_DATE TIMESTAMP_NTZ(9),
	CLASSIFICATION_APPROVED_BY VARCHAR(100),
	CLASSIFICATION_APPROVAL_DATE TIMESTAMP_NTZ(9),
	LAST_RECLASSIFICATION_DATE TIMESTAMP_NTZ(9),
	RECLASSIFICATION_TRIGGER VARCHAR(500),
	RECLASSIFICATION_COUNT NUMBER(10,0) DEFAULT 0,
	PREVIOUS_CLASSIFICATION_LABEL VARCHAR(20),
	LAST_REVIEW_DATE TIMESTAMP_NTZ(9),
	NEXT_REVIEW_DATE TIMESTAMP_NTZ(9),
	REVIEW_FREQUENCY_DAYS NUMBER(10,0) DEFAULT 365,
	REVIEW_STATUS VARCHAR(20),
	PEER_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
	PEER_REVIEWER VARCHAR(100),
	MANAGEMENT_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
	MANAGEMENT_REVIEWER VARCHAR(100),
	TECHNICAL_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
	TECHNICAL_REVIEWER VARCHAR(100),
	CONSISTENCY_CHECK_DATE TIMESTAMP_NTZ(9),
	CONSISTENCY_CHECK_STATUS VARCHAR(20),
	DATA_CREATION_DATE TIMESTAMP_NTZ(9),
	DATA_SOURCE_SYSTEM VARCHAR(255),
	DATA_RETENTION_PERIOD_DAYS NUMBER(10,0),
	DATA_DISPOSAL_DATE TIMESTAMP_NTZ(9),
	SENSITIVE_DATA_USAGE_COUNT NUMBER(10,0) DEFAULT 0,
	LAST_ACCESSED_DATE TIMESTAMP_NTZ(9),
	ACCESS_FREQUENCY VARCHAR(20),
	NUMBER_OF_CONSUMERS NUMBER(10,0),
	HAS_EXCEPTION BOOLEAN DEFAULT FALSE,
	EXCEPTION_TYPE VARCHAR(100),
	EXCEPTION_JUSTIFICATION VARCHAR(2000),
	EXCEPTION_APPROVED_BY VARCHAR(100),
	EXCEPTION_APPROVAL_DATE TIMESTAMP_NTZ(9),
	EXCEPTION_EXPIRY_DATE TIMESTAMP_NTZ(9),
	EXCEPTION_MITIGATION_MEASURES VARCHAR(2000),
	COMPLIANCE_STATUS VARCHAR(20),
	NON_COMPLIANCE_REASON VARCHAR(1000),
	CORRECTIVE_ACTION_REQUIRED BOOLEAN DEFAULT FALSE,
	CORRECTIVE_ACTION_DESCRIPTION VARCHAR(2000),
	CORRECTIVE_ACTION_DUE_DATE TIMESTAMP_NTZ(9),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100),
	LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LAST_MODIFIED_BY VARCHAR(100),
	RECORD_VERSION NUMBER(10,0) DEFAULT 1,
	ADDITIONAL_NOTES VARCHAR(4000),
	STAKEHOLDER_COMMENTS VARCHAR(4000),
	primary key (ASSET_ID)
);

create or replace TABLE CLASSIFICATION_HISTORY (
	HISTORY_ID VARCHAR(100) NOT NULL,
	ASSET_ID VARCHAR(100),
	PREVIOUS_CLASSIFICATION VARCHAR(20),
	NEW_CLASSIFICATION VARCHAR(20),
	PREVIOUS_CONFIDENTIALITY NUMBER(38,0),
	NEW_CONFIDENTIALITY NUMBER(38,0),
	PREVIOUS_INTEGRITY NUMBER(38,0),
	NEW_INTEGRITY NUMBER(38,0),
	PREVIOUS_AVAILABILITY NUMBER(38,0),
	NEW_AVAILABILITY NUMBER(38,0),
	CHANGED_BY VARCHAR(150),
	CHANGE_REASON VARCHAR(1000),
	CHANGE_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	APPROVAL_REQUIRED BOOLEAN,
	APPROVED_BY VARCHAR(150),
	APPROVAL_TIMESTAMP TIMESTAMP_NTZ(9),
	BUSINESS_JUSTIFICATION VARCHAR(1000),
	primary key (HISTORY_ID),
	foreign key (ASSET_ID) references ASSETS(ASSET_ID)
);

create or replace TABLE CLASSIFICATION_DECISIONS (
	ID VARCHAR(16777216),
	ASSET_FULL_NAME VARCHAR(16777216),
	USER_ID VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	CLASSIFICATION_LEVEL VARCHAR(16777216),
	CIA_CONF NUMBER(38,0),
	CIA_INT NUMBER(38,0),
	CIA_AVAIL NUMBER(38,0),
	RATIONALE VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	DETAILS VARIANT
);

create or replace TABLE CLASSIFICATION_AUDIT (
	ID VARCHAR(16777216) DEFAULT UUID_STRING(),
	RESOURCE_ID VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	DETAILS VARCHAR(16777216),
	CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE AI_ASSISTANT_SENSITIVE_ASSETS (
	RUN_ID VARCHAR(16777216),
	DATABASE_NAME VARCHAR(16777216) NOT NULL,
	SCHEMA_NAME VARCHAR(16777216) NOT NULL,
	TABLE_NAME VARCHAR(16777216) NOT NULL,
	COLUMN_NAME VARCHAR(16777216) NOT NULL,
	DETECTED_CATEGORY VARCHAR(16777216),
	DETECTED_TYPE VARCHAR(16777216),
	COMBINED_CONFIDENCE FLOAT,
	METHODS_USED ARRAY,
	COMPLIANCE_TAGS ARRAY,
	SAMPLE_METADATA VARIANT,
	DETECTION_REASON VARCHAR(16777216),
	LAST_SCAN_TS TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PREV_SHA256_HEX VARCHAR(16777216),
	CHAIN_SHA256_HEX VARCHAR(16777216),
	primary key (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME)
);
