-- 001_governance_schema.sql
-- Create core governance schema, inventory, audit, and compliance tables

USE DATABASE IDENTIFIER($DATABASE);

CREATE SCHEMA IF NOT EXISTS DATA_GOVERNANCE;

-- Asset inventory (Discovery service aligns to this)
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.ASSET_INVENTORY (
  FULL_NAME STRING PRIMARY KEY,
  OBJECT_DOMAIN STRING,
  ROW_COUNT NUMBER,
  LAST_DDL_TIME TIMESTAMP_NTZ,
  FIRST_DISCOVERED TIMESTAMP_NTZ,
  LAST_SEEN TIMESTAMP_NTZ,
  CLASSIFICATION_LEVEL STRING,
  CIA_CONF NUMBER,
  CIA_INT NUMBER,
  CIA_AVAIL NUMBER,
  QUEUE_PRIORITY NUMBER,
  CLASSIFIED BOOLEAN
);

-- Classification decisions & approvals
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.CLASSIFICATION_DECISIONS (
  ID STRING,
  ASSET_FULL_NAME STRING,
  USER_ID STRING,
  ACTION STRING,
  CLASSIFICATION_LEVEL STRING,
  CIA_CONF NUMBER,
  CIA_INT NUMBER,
  CIA_AVAIL NUMBER,
  RATIONALE STRING,
  CREATED_AT TIMESTAMP_NTZ,
  DETAILS VARIANT
);

-- Audit log (immutable-style)
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.AUDIT_LOG (
  TIMESTAMP TIMESTAMP_NTZ,
  USER_ID STRING,
  ACTION STRING,
  RESOURCE_TYPE STRING,
  RESOURCE_ID STRING,
  DETAILS VARIANT
);

-- Compliance artifacts
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.REVIEW_SCHEDULES (
  ID STRING,
  ASSET_FULL_NAME STRING,
  FREQUENCY STRING,
  NEXT_RUN TIMESTAMP_NTZ,
  LAST_RUN TIMESTAMP_NTZ,
  OWNER STRING,
  ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.COMPLIANCE_REPORTS (
  ID STRING,
  FRAMEWORK STRING,
  GENERATED_AT TIMESTAMP_NTZ,
  GENERATED_BY STRING,
  METRICS VARIANT,
  LOCATION STRING
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.VIOLATIONS (
  ID STRING,
  RULE_CODE STRING,
  SEVERITY STRING,
  DESCRIPTION STRING,
  ASSET_FULL_NAME STRING,
  DETECTED_AT TIMESTAMP_NTZ,
  STATUS STRING,
  DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.REMEDIATION_TASKS (
  ID STRING,
  VIOLATION_ID STRING,
  ASSIGNEE STRING,
  DUE_DATE DATE,
  STATUS STRING,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

-- View used by the app as queue for classification
CREATE OR REPLACE VIEW DATA_GOVERNANCE.CLASSIFICATION_QUEUE AS
SELECT *
FROM DATA_GOVERNANCE.ASSET_INVENTORY
WHERE COALESCE(CLASSIFIED, FALSE) = FALSE
ORDER BY QUEUE_PRIORITY DESC, ROW_COUNT DESC, LAST_SEEN DESC;
