-- 001_governance_schema.sql
-- Create core governance schema, inventory, audit, and compliance tables

set DB = coalesce($DATABASE, current_database(), 'DATA_CLASSIFICATION_DB');
use database identifier($DB);

CREATE SCHEMA IF NOT EXISTS DATA_GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE;

-- Asset inventory (Discovery service aligns to this)
CREATE TABLE IF NOT EXISTS DATA_CLASSIFICATION_GOVERNANCE.ASSETS (
	ASSET_ID VARCHAR(100) NOT NULL,
	ASSET_NAME VARCHAR(500) NOT NULL,
	ASSET_TYPE VARCHAR(50) NOT NULL,
	DATABASE_NAME VARCHAR(255),
	SCHEMA_NAME VARCHAR(255),
	OBJECT_NAME VARCHAR(255),
	FULLY_QUALIFIED_NAME VARCHAR(1000),
	BUSINESS_UNIT VARCHAR(100),
	DATA_OWNER VARCHAR(100) NOT NULL,
	DATA_OWNER_EMAIL VARCHAR(255),
	DATA_CUSTODIAN VARCHAR(100),
	DATA_CUSTODIAN_EMAIL VARCHAR(255),
	BUSINESS_PURPOSE VARCHAR(2000),
	DATA_DESCRIPTION VARCHAR(4000),
	CLASSIFICATION_LABEL VARCHAR(20),
	CLASSIFICATION_LABEL_COLOR VARCHAR(20),
	CONFIDENTIALITY_LEVEL VARCHAR(2),
	INTEGRITY_LEVEL VARCHAR(2),
	AVAILABILITY_LEVEL VARCHAR(2),
	OVERALL_RISK_CLASSIFICATION VARCHAR(20),
	CONTAINS_PII BOOLEAN DEFAULT FALSE,
	CONTAINS_FINANCIAL_DATA BOOLEAN DEFAULT FALSE,
	SOX_RELEVANT BOOLEAN DEFAULT FALSE,
	SOC_RELEVANT BOOLEAN DEFAULT FALSE,
	REGULATORY_DATA BOOLEAN DEFAULT FALSE,
	CLASSIFICATION_RATIONALE VARCHAR(4000),
	CONFIDENTIALITY_IMPACT_ASSESSMENT VARCHAR(2000),
	INTEGRITY_IMPACT_ASSESSMENT VARCHAR(2000),
	AVAILABILITY_IMPACT_ASSESSMENT VARCHAR(2000),
	CLASSIFICATION_DATE TIMESTAMP_NTZ(9),
	CLASSIFIED_BY VARCHAR(100),
	CLASSIFICATION_METHOD VARCHAR(50),
	CLASSIFICATION_REVIEWED_BY VARCHAR(100),
	CLASSIFICATION_REVIEW_DATE TIMESTAMP_NTZ(9),
	CLASSIFICATION_APPROVED_BY VARCHAR(100),
	CLASSIFICATION_APPROVAL_DATE TIMESTAMP_NTZ(9),
	LAST_RECLASSIFICATION_DATE TIMESTAMP_NTZ(9),
	RECLASSIFICATION_TRIGGER VARCHAR(500),
	RECLASSIFICATION_COUNT NUMBER(10,0) DEFAULT 0,
	PREVIOUS_CLASSIFICATION_LABEL VARCHAR(20),
	LAST_REVIEW_DATE TIMESTAMP_NTZ(9),
	NEXT_REVIEW_DATE TIMESTAMP_NTZ(9),
	REVIEW_FREQUENCY_DAYS NUMBER(10,0) DEFAULT 365,
	REVIEW_STATUS VARCHAR(20),
	PEER_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
	PEER_REVIEWER VARCHAR(100),
	MANAGEMENT_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
	MANAGEMENT_REVIEWER VARCHAR(100),
	TECHNICAL_REVIEW_COMPLETED BOOLEAN DEFAULT FALSE,
	TECHNICAL_REVIEWER VARCHAR(100),
	CONSISTENCY_CHECK_DATE TIMESTAMP_NTZ(9),
	CONSISTENCY_CHECK_STATUS VARCHAR(20),
	DATA_CREATION_DATE TIMESTAMP_NTZ(9),
	DATA_SOURCE_SYSTEM VARCHAR(255),
	DATA_RETENTION_PERIOD_DAYS NUMBER(10,0),
	DATA_DISPOSAL_DATE TIMESTAMP_NTZ(9),
	SENSITIVE_DATA_USAGE_COUNT NUMBER(10,0) DEFAULT 0,
	LAST_ACCESSED_DATE TIMESTAMP_NTZ(9),
	ACCESS_FREQUENCY VARCHAR(20),
	NUMBER_OF_CONSUMERS NUMBER(10,0),
	HAS_EXCEPTION BOOLEAN DEFAULT FALSE,
	EXCEPTION_TYPE VARCHAR(100),
	EXCEPTION_JUSTIFICATION VARCHAR(2000),
	EXCEPTION_APPROVED_BY VARCHAR(100),
	EXCEPTION_APPROVAL_DATE TIMESTAMP_NTZ(9),
	EXCEPTION_EXPIRY_DATE TIMESTAMP_NTZ(9),
	EXCEPTION_MITIGATION_MEASURES VARCHAR(2000),
	COMPLIANCE_STATUS VARCHAR(20),
	NON_COMPLIANCE_REASON VARCHAR(1000),
	CORRECTIVE_ACTION_REQUIRED BOOLEAN DEFAULT FALSE,
	CORRECTIVE_ACTION_DESCRIPTION VARCHAR(2000),
	CORRECTIVE_ACTION_DUE_DATE TIMESTAMP_NTZ(9),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100),
	LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LAST_MODIFIED_BY VARCHAR(100),
	RECORD_VERSION NUMBER(10,0) DEFAULT 1,
	ADDITIONAL_NOTES VARCHAR(4000),
	STAKEHOLDER_COMMENTS VARCHAR(4000),
	primary key (ASSET_ID)
);

-- Classification decisions & approvals
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.CLASSIFICATION_DECISIONS (
  ID STRING,
  ASSET_FULL_NAME STRING,
  USER_ID STRING,
  ACTION STRING,
  CLASSIFICATION_LEVEL STRING,
  CIA_CONF NUMBER,
  CIA_INT NUMBER,
  CIA_AVAIL NUMBER,
  RATIONALE STRING,
  CREATED_AT TIMESTAMP_NTZ,
  DETAILS VARIANT
);

-- Audit log (immutable-style)
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.AUDIT_LOG (
  TIMESTAMP TIMESTAMP_NTZ,
  USER_ID STRING,
  ACTION STRING,
  RESOURCE_TYPE STRING,
  RESOURCE_ID STRING,
  DETAILS VARIANT
);

-- Compliance artifacts
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.REVIEW_SCHEDULES (
  ID STRING,
  ASSET_FULL_NAME STRING,
  FREQUENCY STRING,
  NEXT_RUN TIMESTAMP_NTZ,
  LAST_RUN TIMESTAMP_NTZ,
  OWNER STRING,
  ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.COMPLIANCE_REPORTS (
  ID STRING,
  FRAMEWORK STRING,
  GENERATED_AT TIMESTAMP_NTZ,
  GENERATED_BY STRING,
  METRICS VARIANT,
  LOCATION STRING
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.VIOLATIONS (
  ID STRING,
  RULE_CODE STRING,
  SEVERITY STRING,
  DESCRIPTION STRING,
  ASSET_FULL_NAME STRING,
  DETECTED_AT TIMESTAMP_NTZ,
  STATUS STRING,
  DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.REMEDIATION_TASKS (
  ID STRING,
  VIOLATION_ID STRING,
  ASSIGNEE STRING,
  DUE_DATE DATE,
  STATUS STRING,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

-- View used by the app as queue for classification
CREATE OR REPLACE VIEW DATA_GOVERNANCE.CLASSIFICATION_QUEUE AS
SELECT *
FROM DATA_CLASSIFICATION_GOVERNANCE.ASSETS
WHERE COALESCE(CLASSIFICATION_LABEL, '') = ''
ORDER BY CREATED_TIMESTAMP DESC;
