-- 005_history_and_metadata.sql
-- Create history, metadata, and policy/framework scaffolding required by AI/ML-driven classification

USE DATABASE IDENTIFIER($DATABASE);

-- Schemas
CREATE SCHEMA IF NOT EXISTS CLASSIFICATION_HISTORY;
CREATE SCHEMA IF NOT EXISTS CLASSIFICATION_METADATA;
CREATE SCHEMA IF NOT EXISTS DATA_GOVERNANCE;

-- History of AI/Manual classifications
CREATE TABLE IF NOT EXISTS CLASSIFICATION_HISTORY.CLASSIFICATION_HISTORY (
  ID STRING,
  ASSET_FULL_NAME STRING,
  COLUMN_NAME STRING,
  SOURCE STRING,                 -- SYSTEM_CLASSIFY, AI_SNOWPARK, MANUAL
  DECISION_BY STRING,            -- user or system
  DECISION_AT TIMESTAMP_NTZ,
  LABEL STRING,                  -- Public/Internal/Restricted/Confidential
  C NUMBER,
  I NUMBER,
  A NUMBER,
  CONFIDENCE FLOAT,
  SENSITIVE_CATEGORIES ARRAY,    -- ['PII','PHI','Financial','Custom']
  DETAILS VARIANT
);

-- Review schedules mirror (for cross-schema updates)
CREATE TABLE IF NOT EXISTS CLASSIFICATION_HISTORY.REVIEW_SCHEDULES (
  ID STRING,
  ASSET_FULL_NAME STRING,
  FREQUENCY STRING,
  NEXT_RUN TIMESTAMP_NTZ,
  LAST_RUN TIMESTAMP_NTZ,
  OWNER STRING,
  ACTIVE BOOLEAN
);

-- Allowed tag values registry
CREATE TABLE IF NOT EXISTS CLASSIFICATION_METADATA.ALLOWED_TAG_VALUES (
  TAG_NAME STRING,
  ALLOWED_VALUE STRING,
  PRIMARY KEY (TAG_NAME, ALLOWED_VALUE)
);

-- Seed defaults if empty
INSERT INTO CLASSIFICATION_METADATA.ALLOWED_TAG_VALUES (TAG_NAME, ALLOWED_VALUE)
SELECT * FROM VALUES
  ('DATA_CLASSIFICATION','Public'),
  ('DATA_CLASSIFICATION','Internal'),
  ('DATA_CLASSIFICATION','Restricted'),
  ('DATA_CLASSIFICATION','Confidential'),
  ('CONFIDENTIALITY_LEVEL','0'),('CONFIDENTIALITY_LEVEL','1'),('CONFIDENTIALITY_LEVEL','2'),('CONFIDENTIALITY_LEVEL','3'),
  ('INTEGRITY_LEVEL','0'),('INTEGRITY_LEVEL','1'),('INTEGRITY_LEVEL','2'),('INTEGRITY_LEVEL','3'),
  ('AVAILABILITY_LEVEL','0'),('AVAILABILITY_LEVEL','1'),('AVAILABILITY_LEVEL','2'),('AVAILABILITY_LEVEL','3')
WHERE NOT EXISTS (
  SELECT 1 FROM CLASSIFICATION_METADATA.ALLOWED_TAG_VALUES
);

-- Governance tables not covered previously
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.FRAMEWORKS (
  ID STRING,
  NAME STRING,
  VERSION STRING,
  EFFECTIVE_DATE DATE,
  NEXT_REVIEW_DATE DATE,
  OWNER STRING,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.POLICIES (
  ID STRING,
  FRAMEWORK STRING,         -- references FRAMEWORKS.NAME
  RULE_CODE STRING,         -- short code
  RULE_TEXT STRING,         -- human-readable rule
  CATEGORY STRING,          -- PII/PHI/Financial/Auth/Other
  MIN_CONFIDENTIALITY NUMBER,
  REQUIRE_MASKING BOOLEAN,
  REQUIRE_ROW_ACCESS BOOLEAN,
  CREATED_AT TIMESTAMP_NTZ,
  SOURCE STRING,            -- AI_NLP, MANUAL, IMPORT
  DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.EXCEPTIONS (
  ID STRING,
  ASSET_FULL_NAME STRING,
  FRAMEWORK STRING,
  RULE_CODE STRING,
  REASON STRING,
  EXPIRES_AT DATE,
  CREATED_AT TIMESTAMP_NTZ,
  CREATED_BY STRING,
  DETAILS VARIANT
);

CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.RECLASSIFICATION_REQUESTS (
  ID STRING,
  ASSET_FULL_NAME STRING,
  REQUESTED_BY STRING,
  CURRENT_LABEL STRING,
  REQUESTED_LABEL STRING,
  RATIONALE STRING,
  STATUS STRING,            -- Submitted/Approved/Rejected/Applied
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ,
  DETAILS VARIANT
);

-- Optional queue table (in addition to existing VIEW)
CREATE TABLE IF NOT EXISTS DATA_GOVERNANCE.CLASSIFICATION_QUEUE (
  ID STRING,
  ASSET_FULL_NAME STRING,
  COLUMN_NAME STRING,
  REASON STRING,            -- UNCLASSIFIED / LOW_CONFIDENCE / CONFLICT
  SUGGESTED_LABEL STRING,
  CONFIDENCE FLOAT,
  SENSITIVE_CATEGORIES ARRAY,
  CREATED_AT TIMESTAMP_NTZ,
  DETAILS VARIANT
);
