-- ============================================================================
-- UNIFIED GOVERNANCE ARCHITECTURE
-- Enhancements to Existing Tables + New Strategic Tables
-- ============================================================================
-- Purpose: Create a complete data-driven classification system
-- Author: AI Classification System
-- Date: 2025-12-04
-- ============================================================================

USE DATABASE GOVERNANCE_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- ============================================================================
-- PART 1: ENHANCE EXISTING TABLES
-- ============================================================================

-- Enhance SENSITIVITY_CATEGORIES
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS CATEGORY_TYPE VARCHAR(50) DEFAULT 'PRIMARY' COMMENT 'PRIMARY, SUBCATEGORY, DERIVED';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS PARENT_CATEGORY_ID VARCHAR COMMENT 'For hierarchical categories';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS BOOST_FACTOR FLOAT DEFAULT 1.0 COMMENT 'Default boost when matched';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS REDUCE_FACTOR FLOAT DEFAULT 1.0 COMMENT 'Default reduce when not matched';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS PRIORITY INTEGER DEFAULT 100 COMMENT 'For rule ordering (lower = higher priority)';

-- Enhance SENSITIVE_KEYWORDS
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS KEYWORD_SCOPE VARCHAR(20) DEFAULT 'COLUMN' COMMENT 'COLUMN, TABLE, BOTH';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS EXCLUSION_KEYWORDS TEXT COMMENT 'JSON array of exclusion keywords';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS TIEBREAKER_WEIGHT FLOAT DEFAULT 1.0 COMMENT 'Weight for tiebreaking';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS CONTEXT_TYPE VARCHAR(50) COMMENT 'TABLE_CONTEXT, FIELD_TYPE, ID_CLASSIFICATION';

-- Enhance SENSITIVE_PATTERNS
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS PATTERN_SCOPE VARCHAR(20) DEFAULT 'COLUMN' COMMENT 'COLUMN, TABLE, DATA';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS VALIDATION_LOGIC TEXT COMMENT 'Additional validation rules (JSON)';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS FALSE_POSITIVE_KEYWORDS TEXT COMMENT 'JSON array to reduce false positives';

-- Enhance SENSITIVE_AUDIT
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS POLICY_GROUP VARCHAR(50) COMMENT 'PII, SOX, SOC2';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS DETECTION_METHOD VARCHAR(50) COMMENT 'KEYWORD, PATTERN, SEMANTIC, HYBRID';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS SEMANTIC_SCORE FLOAT COMMENT 'Semantic similarity score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS KEYWORD_SCORE FLOAT COMMENT 'Keyword match score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS PATTERN_SCORE FLOAT COMMENT 'Pattern match score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS CONTEXT_ADJUSTMENTS TEXT COMMENT 'JSON of applied context adjustments';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS TIEBREAKER_USED BOOLEAN DEFAULT FALSE COMMENT 'Whether tiebreaker was needed';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS RULE_IDS_APPLIED TEXT COMMENT 'JSON array of rule IDs that fired';

-- ============================================================================
-- PART 2: CREATE NEW STRATEGIC TABLES
-- ============================================================================

-- Table 1: CLASSIFICATION_RULES
CREATE OR REPLACE TABLE CLASSIFICATION_RULES (
    RULE_ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),
    RULE_NAME VARCHAR(255) NOT NULL,
    RULE_TYPE VARCHAR(50) NOT NULL,
    PRIORITY INTEGER DEFAULT 100,
    
    -- Matching Criteria
    MATCH_SCOPE VARCHAR(20),
    MATCH_KEYWORDS TEXT,
    MATCH_LOGIC VARCHAR(20),
    EXCLUDE_KEYWORDS TEXT,
    
    -- Actions
    TARGET_CATEGORY_ID VARCHAR,
    ACTION_TYPE VARCHAR(20),
    ACTION_FACTOR FLOAT,
    
    -- Secondary Actions
    SECONDARY_CATEGORY_ID VARCHAR,
    SECONDARY_ACTION_TYPE VARCHAR(20),
    SECONDARY_ACTION_FACTOR FLOAT,
    
    -- Metadata
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ,
    VERSION_NUMBER INTEGER DEFAULT 1,
    
    CONSTRAINT chk_rule_type CHECK (RULE_TYPE IN ('TABLE_CONTEXT', 'COLUMN_PATTERN', 'ID_CLASSIFICATION', 'FIELD_TYPE', 'EXCLUSION')),
    CONSTRAINT chk_match_scope CHECK (MATCH_SCOPE IN ('TABLE', 'COLUMN', 'BOTH')),
    CONSTRAINT chk_match_logic CHECK (MATCH_LOGIC IN ('ANY', 'ALL', 'EXACT', 'REGEX')),
    CONSTRAINT chk_action_type CHECK (ACTION_TYPE IN ('BOOST', 'REDUCE', 'REMOVE')),
    FOREIGN KEY (TARGET_CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SECONDARY_CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
);

CREATE INDEX idx_classification_rules_type ON CLASSIFICATION_RULES(RULE_TYPE);
CREATE INDEX idx_classification_rules_active ON CLASSIFICATION_RULES(IS_ACTIVE);
CREATE INDEX idx_classification_rules_priority ON CLASSIFICATION_RULES(PRIORITY);

COMMENT ON TABLE CLASSIFICATION_RULES IS 'Stores all context-aware classification rules for data-driven sensitivity detection';

-- Table 2: GENERIC_EXCLUSIONS
CREATE OR REPLACE TABLE GENERIC_EXCLUSIONS (
    EXCLUSION_ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),
    EXCLUSION_NAME VARCHAR(255),
    EXCLUSION_TYPE VARCHAR(50),
    KEYWORDS TEXT,
    EXCEPTION_KEYWORDS TEXT,
    
    REDUCE_PII_FACTOR FLOAT DEFAULT 0.1,
    REDUCE_SOX_FACTOR FLOAT DEFAULT 0.2,
    REDUCE_SOC2_FACTOR FLOAT DEFAULT 0.1,
    
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ,
    
    CONSTRAINT chk_exclusion_type CHECK (EXCLUSION_TYPE IN ('STATUS_FLAG', 'DATE_TIME', 'GENERIC_ID', 'DESCRIPTION', 'QUANTITY', 'VENDOR'))
);

CREATE INDEX idx_generic_exclusions_type ON GENERIC_EXCLUSIONS(EXCLUSION_TYPE);
CREATE INDEX idx_generic_exclusions_active ON GENERIC_EXCLUSIONS(IS_ACTIVE);

COMMENT ON TABLE GENERIC_EXCLUSIONS IS 'Patterns for identifying and reducing sensitivity scores for generic non-sensitive fields';

-- Table 3: ADDRESS_CONTEXT_REGISTRY
CREATE OR REPLACE TABLE ADDRESS_CONTEXT_REGISTRY (
    CONTEXT_ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),
    CONTEXT_TYPE VARCHAR(50) NOT NULL,
    INDICATOR_TYPE VARCHAR(20),
    INDICATOR_KEYWORD VARCHAR(255),
    
    BOOST_CATEGORY_ID VARCHAR,
    BOOST_FACTOR FLOAT,
    SUPPRESS_CATEGORY_ID VARCHAR,
    SUPPRESS_FACTOR FLOAT,
    
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ,
    
    CONSTRAINT chk_context_type CHECK (CONTEXT_TYPE IN ('PHYSICAL_ADDRESS', 'NETWORK_ADDRESS')),
    CONSTRAINT chk_indicator_type CHECK (INDICATOR_TYPE IN ('POSITIVE', 'NEGATIVE')),
    FOREIGN KEY (BOOST_CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SUPPRESS_CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
);

CREATE INDEX idx_address_context_type ON ADDRESS_CONTEXT_REGISTRY(CONTEXT_TYPE);
CREATE INDEX idx_address_indicator_type ON ADDRESS_CONTEXT_REGISTRY(INDICATOR_TYPE);

COMMENT ON TABLE ADDRESS_CONTEXT_REGISTRY IS 'Registry for distinguishing between physical addresses (PII) and network addresses (SOC2)';

-- Table 4: CATEGORY_RELATIONSHIPS
CREATE OR REPLACE TABLE CATEGORY_RELATIONSHIPS (
    RELATIONSHIP_ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),
    PARENT_CATEGORY_ID VARCHAR NOT NULL,
    CHILD_CATEGORY_ID VARCHAR NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(50),
    PRIORITY_RULE VARCHAR(20),
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ,
    
    CONSTRAINT chk_relationship_type CHECK (RELATIONSHIP_TYPE IN ('PARENT_CHILD', 'MUTUALLY_EXCLUSIVE', 'COMPLEMENTARY', 'CONFLICTING')),
    CONSTRAINT chk_priority_rule CHECK (PRIORITY_RULE IN ('PARENT_WINS', 'CHILD_WINS', 'HIGHEST_CONFIDENCE')),
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (CHILD_CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID),
    UNIQUE (PARENT_CATEGORY_ID, CHILD_CATEGORY_ID)
);

CREATE INDEX idx_category_rel_parent ON CATEGORY_RELATIONSHIPS(PARENT_CATEGORY_ID);
CREATE INDEX idx_category_rel_child ON CATEGORY_RELATIONSHIPS(CHILD_CATEGORY_ID);

COMMENT ON TABLE CATEGORY_RELATIONSHIPS IS 'Defines hierarchical and semantic relationships between sensitivity categories';

-- Table 5: DETECTION_THRESHOLDS
CREATE OR REPLACE TABLE DETECTION_THRESHOLDS (
    THRESHOLD_ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),
    CATEGORY_ID VARCHAR NOT NULL,
    CONTEXT_TYPE VARCHAR(50),
    MIN_CONFIDENCE FLOAT DEFAULT 0.50,
    RECOMMENDED_CONFIDENCE FLOAT DEFAULT 0.70,
    AUTO_APPROVE_CONFIDENCE FLOAT DEFAULT 0.90,
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ,
    
    CONSTRAINT chk_context_type_threshold CHECK (CONTEXT_TYPE IN ('DEFAULT', 'HIGH_RISK_TABLE', 'LOW_RISK_TABLE', 'FINANCIAL_TABLE', 'SECURITY_TABLE', 'CUSTOMER_TABLE')),
    FOREIGN KEY (CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
);

CREATE INDEX idx_detection_thresholds_category ON DETECTION_THRESHOLDS(CATEGORY_ID);
CREATE INDEX idx_detection_thresholds_context ON DETECTION_THRESHOLDS(CONTEXT_TYPE);

COMMENT ON TABLE DETECTION_THRESHOLDS IS 'Dynamic detection thresholds based on category and context';

-- Table 6: CLASSIFICATION_METADATA
CREATE OR REPLACE TABLE CLASSIFICATION_METADATA (
    METADATA_ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),
    RUN_ID VARCHAR(36) NOT NULL,
    DATABASE_NAME VARCHAR(255),
    SCHEMA_NAME VARCHAR(255),
    TABLE_NAME VARCHAR(255),
    
    -- Run Statistics
    TOTAL_COLUMNS INTEGER,
    SENSITIVE_COLUMNS_DETECTED INTEGER,
    CATEGORIES_DETECTED TEXT,
    AVERAGE_CONFIDENCE FLOAT,
    
    -- Performance Metrics
    PROCESSING_TIME_MS INTEGER,
    SEMANTIC_SEARCH_TIME_MS INTEGER,
    KEYWORD_SEARCH_TIME_MS INTEGER,
    PATTERN_SEARCH_TIME_MS INTEGER,
    
    -- Model Information
    MODEL_VERSION VARCHAR(50),
    EMBEDDING_MODEL VARCHAR(100),
    RULES_VERSION INTEGER,
    
    -- Results
    CLASSIFICATION_SUMMARY TEXT,
    ERRORS_ENCOUNTERED TEXT,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE INDEX idx_classification_metadata_run ON CLASSIFICATION_METADATA(RUN_ID);
CREATE INDEX idx_classification_metadata_table ON CLASSIFICATION_METADATA(DATABASE_NAME, SCHEMA_NAME, TABLE_NAME);
CREATE INDEX idx_classification_metadata_created ON CLASSIFICATION_METADATA(CREATED_AT);

COMMENT ON TABLE CLASSIFICATION_METADATA IS 'Stores metadata and performance metrics for classification runs';

-- ============================================================================
-- PART 3: CREATE VIEWS FOR EASY ACCESS
-- ============================================================================

-- View 1: Active Classification Rules
CREATE OR REPLACE VIEW V_ACTIVE_CLASSIFICATION_RULES AS
SELECT 
    r.RULE_ID,
    r.RULE_NAME,
    r.RULE_TYPE,
    r.PRIORITY,
    r.MATCH_SCOPE,
    r.MATCH_KEYWORDS,
    r.MATCH_LOGIC,
    r.EXCLUDE_KEYWORDS,
    c1.CATEGORY_NAME AS TARGET_CATEGORY,
    c1.POLICY_GROUP AS TARGET_POLICY_GROUP,
    r.ACTION_TYPE,
    r.ACTION_FACTOR,
    c2.CATEGORY_NAME AS SECONDARY_CATEGORY,
    c2.POLICY_GROUP AS SECONDARY_POLICY_GROUP,
    r.SECONDARY_ACTION_TYPE,
    r.SECONDARY_ACTION_FACTOR,
    r.DESCRIPTION
FROM CLASSIFICATION_RULES r
LEFT JOIN SENSITIVITY_CATEGORIES c1 ON r.TARGET_CATEGORY_ID = c1.CATEGORY_ID
LEFT JOIN SENSITIVITY_CATEGORIES c2 ON r.SECONDARY_CATEGORY_ID = c2.CATEGORY_ID
WHERE r.IS_ACTIVE = TRUE
ORDER BY r.PRIORITY, r.RULE_ID;

-- View 2: Category Hierarchy
CREATE OR REPLACE VIEW V_CATEGORY_HIERARCHY AS
SELECT 
    p.CATEGORY_NAME AS PARENT_CATEGORY,
    p.POLICY_GROUP AS PARENT_POLICY_GROUP,
    c.CATEGORY_NAME AS CHILD_CATEGORY,
    c.POLICY_GROUP AS CHILD_POLICY_GROUP,
    r.RELATIONSHIP_TYPE,
    r.PRIORITY_RULE
FROM CATEGORY_RELATIONSHIPS r
JOIN SENSITIVITY_CATEGORIES p ON r.PARENT_CATEGORY_ID = p.CATEGORY_ID
JOIN SENSITIVITY_CATEGORIES c ON r.CHILD_CATEGORY_ID = c.CATEGORY_ID
WHERE r.IS_ACTIVE = TRUE;

-- View 3: Classification Summary
CREATE OR REPLACE VIEW V_CLASSIFICATION_SUMMARY AS
SELECT 
    a.TABLE_NAME,
    a.COLUMN_NAME,
    a.CATEGORY,
    a.POLICY_GROUP,
    a.CONFIDENCE,
    a.DETECTION_METHOD,
    a.SEMANTIC_SCORE,
    a.KEYWORD_SCORE,
    a.PATTERN_SCORE,
    a.TIEBREAKER_USED,
    a.SCANNED_AT
FROM SENSITIVE_AUDIT a
WHERE a.SCANNED_AT >= DATEADD(day, -30, CURRENT_TIMESTAMP())
ORDER BY a.SCANNED_AT DESC;

-- ============================================================================
-- PART 4: GRANT PERMISSIONS
-- ============================================================================

GRANT SELECT ON TABLE CLASSIFICATION_RULES TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON TABLE GENERIC_EXCLUSIONS TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON TABLE ADDRESS_CONTEXT_REGISTRY TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON TABLE CATEGORY_RELATIONSHIPS TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON TABLE DETECTION_THRESHOLDS TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON TABLE CLASSIFICATION_METADATA TO ROLE DATA_GOVERNANCE_READER;

GRANT ALL ON TABLE CLASSIFICATION_RULES TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT ALL ON TABLE GENERIC_EXCLUSIONS TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT ALL ON TABLE ADDRESS_CONTEXT_REGISTRY TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT ALL ON TABLE CATEGORY_RELATIONSHIPS TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT ALL ON TABLE DETECTION_THRESHOLDS TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT ALL ON TABLE CLASSIFICATION_METADATA TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT ON VIEW V_ACTIVE_CLASSIFICATION_RULES TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON VIEW V_CATEGORY_HIERARCHY TO ROLE DATA_GOVERNANCE_READER;
GRANT SELECT ON VIEW V_CLASSIFICATION_SUMMARY TO ROLE DATA_GOVERNANCE_READER;

-- ============================================================================
-- PART 5: VERIFICATION
-- ============================================================================

-- Check table counts
SELECT 'EXISTING TABLES ENHANCED' AS STATUS;
SELECT 'SENSITIVITY_CATEGORIES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM SENSITIVITY_CATEGORIES
UNION ALL
SELECT 'SENSITIVE_KEYWORDS', COUNT(*) FROM SENSITIVE_KEYWORDS
UNION ALL
SELECT 'SENSITIVE_PATTERNS', COUNT(*) FROM SENSITIVE_PATTERNS
UNION ALL
SELECT 'SENSITIVE_AUDIT', COUNT(*) FROM SENSITIVE_AUDIT;

SELECT 'NEW TABLES CREATED' AS STATUS;
SELECT 'CLASSIFICATION_RULES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CLASSIFICATION_RULES
UNION ALL
SELECT 'GENERIC_EXCLUSIONS', COUNT(*) FROM GENERIC_EXCLUSIONS
UNION ALL
SELECT 'ADDRESS_CONTEXT_REGISTRY', COUNT(*) FROM ADDRESS_CONTEXT_REGISTRY
UNION ALL
SELECT 'CATEGORY_RELATIONSHIPS', COUNT(*) FROM CATEGORY_RELATIONSHIPS
UNION ALL
SELECT 'DETECTION_THRESHOLDS', COUNT(*) FROM DETECTION_THRESHOLDS
UNION ALL
SELECT 'CLASSIFICATION_METADATA', COUNT(*) FROM CLASSIFICATION_METADATA;

-- Show table structure
SHOW COLUMNS IN SENSITIVITY_CATEGORIES;
SHOW COLUMNS IN CLASSIFICATION_RULES;

SELECT '✅ Unified Governance Architecture Created Successfully!' AS STATUS;
