-- 006_views.sql
-- Views for dashboards & monitoring

USE DATABASE IDENTIFIER($DATABASE);

-- Classification coverage summary view
CREATE OR REPLACE VIEW DATA_GOVERNANCE.CLASSIFICATION_SUMMARY AS
WITH tags AS (
  SELECT 
    OBJECT_DATABASE||'.'||OBJECT_SCHEMA||'.'||OBJECT_NAME AS FULL_NAME,
    MAX(CASE WHEN TAG_NAME = 'DATA_CLASSIFICATION' THEN TAG_VALUE END) AS LABEL,
    TRY_TO_NUMBER(MAX(CASE WHEN TAG_NAME = 'CONFIDENTIALITY_LEVEL' THEN TAG_VALUE END)) AS C
  FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
  WHERE OBJECT_DATABASE = CURRENT_DATABASE()
  GROUP BY 1
)
SELECT 
  LABEL,
  C,
  COUNT(*) AS OBJECTS
FROM tags
GROUP BY LABEL, C
ORDER BY C DESC, LABEL DESC;

-- Compliance coverage by framework summary view (latest report per framework)
CREATE OR REPLACE VIEW DATA_GOVERNANCE.COMPLIANCE_COVERAGE AS
WITH latest AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY FRAMEWORK ORDER BY GENERATED_AT DESC) AS RN
  FROM DATA_GOVERNANCE.COMPLIANCE_REPORTS
)
SELECT FRAMEWORK, GENERATED_AT, METRICS
FROM latest
WHERE RN = 1;

-- Audit trail passthrough
CREATE OR REPLACE VIEW DATA_GOVERNANCE.AUDIT_LOGS AS
SELECT * FROM DATA_GOVERNANCE.AUDIT_LOG;
