-- ============================================================================
-- CONSOLIDATED 4-TABLE GOVERNANCE ARCHITECTURE
-- Enhance existing 4 core tables to handle ALL governance logic
-- ============================================================================
-- Purpose: Consolidate all classification logic into 4 core tables
-- Tables: SENSITIVITY_CATEGORIES, SENSITIVE_KEYWORDS, SENSITIVE_PATTERNS, SENSITIVE_AUDIT
-- Date: 2025-12-04
-- ============================================================================

USE DATABASE GOVERNANCE_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- ============================================================================
-- PART 1: ENHANCE SENSITIVITY_CATEGORIES
-- Purpose: Master table for categories, weights, thresholds, relationships
-- ============================================================================

ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS CATEGORY_TYPE VARCHAR(50) DEFAULT 'PRIMARY' COMMENT 'PRIMARY, SUBCATEGORY, DERIVED';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS PARENT_CATEGORY_ID VARCHAR COMMENT 'For hierarchical categories';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS CATEGORY_RELATIONSHIPS VARIANT COMMENT 'JSON: relationships with other categories';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS BOOST_FACTOR FLOAT DEFAULT 1.5 COMMENT 'Default boost when matched';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS REDUCE_FACTOR FLOAT DEFAULT 0.3 COMMENT 'Default reduce when not matched';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS PRIORITY INTEGER DEFAULT 100 COMMENT 'For rule ordering (lower = higher priority)';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS THRESHOLDS_BY_CONTEXT VARIANT COMMENT 'JSON: dynamic thresholds by context';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS EXCLUSION_KEYWORDS VARIANT COMMENT 'JSON: keywords that exclude this category';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS COMPLEMENTARY_CATEGORIES VARIANT COMMENT 'JSON: categories that can co-exist';
ALTER TABLE SENSITIVITY_CATEGORIES ADD COLUMN IF NOT EXISTS CONFLICTING_CATEGORIES VARIANT COMMENT 'JSON: mutually exclusive categories';

-- Add foreign key for hierarchy (if not exists)
-- Note: This may fail if constraint already exists, which is fine
BEGIN
    ALTER TABLE SENSITIVITY_CATEGORIES 
    ADD CONSTRAINT fk_parent_category 
    FOREIGN KEY (PARENT_CATEGORY_ID) 
    REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID);
EXCEPTION
    WHEN OTHERS THEN
        -- Constraint already exists, continue
        NULL;
END;

COMMENT ON COLUMN SENSITIVITY_CATEGORIES.CATEGORY_TYPE IS 'Type of category: PRIMARY, SUBCATEGORY, DERIVED';
COMMENT ON COLUMN SENSITIVITY_CATEGORIES.THRESHOLDS_BY_CONTEXT IS 'JSON object with context-specific thresholds: {"DEFAULT": 0.50, "FINANCIAL_TABLE": 0.70}';
COMMENT ON COLUMN SENSITIVITY_CATEGORIES.CATEGORY_RELATIONSHIPS IS 'JSON object defining relationships with other categories';

-- ============================================================================
-- PART 2: ENHANCE SENSITIVE_KEYWORDS
-- Purpose: All keyword-based rules (matching, context, tiebreakers, exclusions)
-- ============================================================================

ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS KEYWORD_SCOPE VARCHAR(20) DEFAULT 'COLUMN' COMMENT 'COLUMN, TABLE, BOTH';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS CONTEXT_TYPE VARCHAR(50) COMMENT 'TABLE_CONTEXT, FIELD_TYPE, ID_CLASSIFICATION, EXCLUSION, TIEBREAKER';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS RULE_TYPE VARCHAR(50) COMMENT 'BOOST, REDUCE, REMOVE, MATCH';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS RULE_CONFIG VARIANT COMMENT 'JSON: rule configuration including actions, exclusions, factors';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS TIEBREAKER_WEIGHT FLOAT DEFAULT 1.0 COMMENT 'Weight for intelligent tiebreaking';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS PRIORITY INTEGER DEFAULT 100 COMMENT 'Rule execution order (lower = higher priority)';
ALTER TABLE SENSITIVE_KEYWORDS ADD COLUMN IF NOT EXISTS DESCRIPTION TEXT COMMENT 'Human-readable explanation of the rule';

-- Add constraints
BEGIN
    ALTER TABLE SENSITIVE_KEYWORDS ADD CONSTRAINT chk_keyword_scope 
    CHECK (KEYWORD_SCOPE IN ('COLUMN', 'TABLE', 'BOTH'));
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    ALTER TABLE SENSITIVE_KEYWORDS ADD CONSTRAINT chk_context_type 
    CHECK (CONTEXT_TYPE IN ('TABLE_CONTEXT', 'FIELD_TYPE', 'ID_CLASSIFICATION', 'EXCLUSION', 'TIEBREAKER', NULL));
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    ALTER TABLE SENSITIVE_KEYWORDS ADD CONSTRAINT chk_rule_type 
    CHECK (RULE_TYPE IN ('BOOST', 'REDUCE', 'REMOVE', 'MATCH', NULL));
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

COMMENT ON COLUMN SENSITIVE_KEYWORDS.CONTEXT_TYPE IS 'Type of rule: TABLE_CONTEXT, FIELD_TYPE, ID_CLASSIFICATION, EXCLUSION, TIEBREAKER';
COMMENT ON COLUMN SENSITIVE_KEYWORDS.RULE_CONFIG IS 'JSON configuration: {"match_logic": "ANY", "action_factor": 1.5, "secondary_actions": [...]}';

-- ============================================================================
-- PART 3: ENHANCE SENSITIVE_PATTERNS
-- Purpose: All pattern-based rules (data patterns, address context)
-- ============================================================================

ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS PATTERN_SCOPE VARCHAR(20) DEFAULT 'DATA' COMMENT 'COLUMN, TABLE, DATA';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS CONTEXT_TYPE VARCHAR(50) COMMENT 'DATA_PATTERN, ADDRESS_CONTEXT, FIELD_TYPE';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS RULE_TYPE VARCHAR(50) COMMENT 'MATCH, BOOST, SUPPRESS';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS PATTERN_CONFIG VARIANT COMMENT 'JSON: pattern configuration including validation, false positives, actions';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS PRIORITY INTEGER DEFAULT 100 COMMENT 'Pattern execution order (lower = higher priority)';
ALTER TABLE SENSITIVE_PATTERNS ADD COLUMN IF NOT EXISTS DESCRIPTION TEXT COMMENT 'Human-readable explanation of the pattern';

-- Add constraints
BEGIN
    ALTER TABLE SENSITIVE_PATTERNS ADD CONSTRAINT chk_pattern_scope 
    CHECK (PATTERN_SCOPE IN ('COLUMN', 'TABLE', 'DATA'));
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    ALTER TABLE SENSITIVE_PATTERNS ADD CONSTRAINT chk_pattern_context 
    CHECK (CONTEXT_TYPE IN ('DATA_PATTERN', 'ADDRESS_CONTEXT', 'FIELD_TYPE', NULL));
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    ALTER TABLE SENSITIVE_PATTERNS ADD CONSTRAINT chk_pattern_rule_type 
    CHECK (RULE_TYPE IN ('MATCH', 'BOOST', 'SUPPRESS', NULL));
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

COMMENT ON COLUMN SENSITIVE_PATTERNS.CONTEXT_TYPE IS 'Type of pattern: DATA_PATTERN, ADDRESS_CONTEXT, FIELD_TYPE';
COMMENT ON COLUMN SENSITIVE_PATTERNS.PATTERN_CONFIG IS 'JSON configuration: {"boost_factor": 1.6, "suppress_category": "SOC2", "negative_indicators": [...]}';

-- ============================================================================
-- PART 4: ENHANCE SENSITIVE_AUDIT
-- Purpose: Complete audit trail with detailed scoring and metadata
-- ============================================================================

ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS POLICY_GROUP VARCHAR(50) COMMENT 'PII, SOX, SOC2';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS DETECTION_METHOD VARCHAR(50) COMMENT 'KEYWORD, PATTERN, SEMANTIC, HYBRID';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS SEMANTIC_SCORE FLOAT COMMENT 'Semantic similarity score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS KEYWORD_SCORE FLOAT COMMENT 'Keyword match score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS PATTERN_SCORE FLOAT COMMENT 'Pattern match score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS FINAL_SCORE FLOAT COMMENT 'Final combined score';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS RULES_APPLIED VARIANT COMMENT 'JSON: array of rules that fired';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS CONTEXT_DETECTED VARIANT COMMENT 'JSON: detected context (table type, field type, etc.)';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS SCORE_ADJUSTMENTS VARIANT COMMENT 'JSON: score adjustment history';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS TIEBREAKER_USED BOOLEAN DEFAULT FALSE COMMENT 'Whether tiebreaker was needed';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS TIED_CATEGORIES VARIANT COMMENT 'JSON: categories that were tied';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS TIEBREAKER_MATCHES VARIANT COMMENT 'JSON: tiebreaker keyword matches per category';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS PERFORMANCE_METRICS VARIANT COMMENT 'JSON: timing metrics for classification';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS RUN_ID VARCHAR(36) COMMENT 'Classification run identifier';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS MODEL_VERSION VARCHAR(50) COMMENT 'Embedding model version used';
ALTER TABLE SENSITIVE_AUDIT ADD COLUMN IF NOT EXISTS RULES_VERSION INTEGER COMMENT 'Version of rules used';

COMMENT ON COLUMN SENSITIVE_AUDIT.RULES_APPLIED IS 'JSON array: [{"rule_id": "KW_001", "rule_type": "BOOST", "factor": 1.3}]';
COMMENT ON COLUMN SENSITIVE_AUDIT.CONTEXT_DETECTED IS 'JSON object: {"table_context": "FINANCIAL_TABLE", "field_type": "PRICE_AMOUNT"}';
COMMENT ON COLUMN SENSITIVE_AUDIT.PERFORMANCE_METRICS IS 'JSON object: {"total_time_ms": 150, "semantic_time_ms": 80}';

-- ============================================================================
-- PART 5: CREATE INDEXES FOR PERFORMANCE
-- ============================================================================

-- SENSITIVITY_CATEGORIES indexes
CREATE INDEX IF NOT EXISTS idx_sensitivity_categories_policy ON SENSITIVITY_CATEGORIES(POLICY_GROUP);
CREATE INDEX IF NOT EXISTS idx_sensitivity_categories_type ON SENSITIVITY_CATEGORIES(CATEGORY_TYPE);
CREATE INDEX IF NOT EXISTS idx_sensitivity_categories_parent ON SENSITIVITY_CATEGORIES(PARENT_CATEGORY_ID);
CREATE INDEX IF NOT EXISTS idx_sensitivity_categories_priority ON SENSITIVITY_CATEGORIES(PRIORITY);

-- SENSITIVE_KEYWORDS indexes
CREATE INDEX IF NOT EXISTS idx_sensitive_keywords_scope ON SENSITIVE_KEYWORDS(KEYWORD_SCOPE);
CREATE INDEX IF NOT EXISTS idx_sensitive_keywords_context ON SENSITIVE_KEYWORDS(CONTEXT_TYPE);
CREATE INDEX IF NOT EXISTS idx_sensitive_keywords_rule_type ON SENSITIVE_KEYWORDS(RULE_TYPE);
CREATE INDEX IF NOT EXISTS idx_sensitive_keywords_priority ON SENSITIVE_KEYWORDS(PRIORITY);
CREATE INDEX IF NOT EXISTS idx_sensitive_keywords_active ON SENSITIVE_KEYWORDS(IS_ACTIVE);

-- SENSITIVE_PATTERNS indexes
CREATE INDEX IF NOT EXISTS idx_sensitive_patterns_scope ON SENSITIVE_PATTERNS(PATTERN_SCOPE);
CREATE INDEX IF NOT EXISTS idx_sensitive_patterns_context ON SENSITIVE_PATTERNS(CONTEXT_TYPE);
CREATE INDEX IF NOT EXISTS idx_sensitive_patterns_priority ON SENSITIVE_PATTERNS(PRIORITY);
CREATE INDEX IF NOT EXISTS idx_sensitive_patterns_active ON SENSITIVE_PATTERNS(IS_ACTIVE);

-- SENSITIVE_AUDIT indexes
CREATE INDEX IF NOT EXISTS idx_sensitive_audit_policy ON SENSITIVE_AUDIT(POLICY_GROUP);
CREATE INDEX IF NOT EXISTS idx_sensitive_audit_method ON SENSITIVE_AUDIT(DETECTION_METHOD);
CREATE INDEX IF NOT EXISTS idx_sensitive_audit_run ON SENSITIVE_AUDIT(RUN_ID);
CREATE INDEX IF NOT EXISTS idx_sensitive_audit_scanned ON SENSITIVE_AUDIT(SCANNED_AT);
CREATE INDEX IF NOT EXISTS idx_sensitive_audit_table ON SENSITIVE_AUDIT(TABLE_NAME);

-- ============================================================================
-- PART 6: CREATE HELPER VIEWS
-- ============================================================================

-- View 1: Active Table Context Rules
CREATE OR REPLACE VIEW V_TABLE_CONTEXT_RULES AS
SELECT 
    k.KEYWORD_ID,
    k.KEYWORD_STRING,
    c.CATEGORY_NAME,
    c.POLICY_GROUP,
    k.RULE_TYPE,
    k.RULE_CONFIG:action_factor::FLOAT AS ACTION_FACTOR,
    k.RULE_CONFIG:secondary_actions AS SECONDARY_ACTIONS,
    k.PRIORITY,
    k.DESCRIPTION
FROM SENSITIVE_KEYWORDS k
JOIN SENSITIVITY_CATEGORIES c ON k.CATEGORY_ID = c.CATEGORY_ID
WHERE k.CONTEXT_TYPE = 'TABLE_CONTEXT'
  AND k.IS_ACTIVE = TRUE
ORDER BY k.PRIORITY, k.KEYWORD_ID;

-- View 2: Tiebreaker Keywords
CREATE OR REPLACE VIEW V_TIEBREAKER_KEYWORDS AS
SELECT 
    c.POLICY_GROUP,
    k.KEYWORD_STRING,
    k.TIEBREAKER_WEIGHT,
    k.KEYWORD_SCOPE
FROM SENSITIVE_KEYWORDS k
JOIN SENSITIVITY_CATEGORIES c ON k.CATEGORY_ID = c.CATEGORY_ID
WHERE k.CONTEXT_TYPE = 'TIEBREAKER'
  AND k.IS_ACTIVE = TRUE
ORDER BY c.POLICY_GROUP, k.TIEBREAKER_WEIGHT DESC;

-- View 3: Address Context Patterns
CREATE OR REPLACE VIEW V_ADDRESS_CONTEXT_PATTERNS AS
SELECT 
    p.PATTERN_ID,
    p.PATTERN_NAME,
    c.POLICY_GROUP,
    p.SENSITIVITY_TYPE AS ADDRESS_TYPE,
    p.PATTERN_REGEX,
    p.PATTERN_CONFIG:boost_factor::FLOAT AS BOOST_FACTOR,
    p.PATTERN_CONFIG:suppress_category::STRING AS SUPPRESS_CATEGORY,
    p.PATTERN_CONFIG:suppress_factor::FLOAT AS SUPPRESS_FACTOR,
    p.PATTERN_CONFIG:negative_indicators AS NEGATIVE_INDICATORS
FROM SENSITIVE_PATTERNS p
JOIN SENSITIVITY_CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
WHERE p.CONTEXT_TYPE = 'ADDRESS_CONTEXT'
  AND p.IS_ACTIVE = TRUE;

-- View 4: Category Hierarchy
CREATE OR REPLACE VIEW V_CATEGORY_HIERARCHY AS
SELECT 
    p.CATEGORY_NAME AS PARENT_CATEGORY,
    p.POLICY_GROUP AS PARENT_POLICY_GROUP,
    c.CATEGORY_NAME AS CHILD_CATEGORY,
    c.POLICY_GROUP AS CHILD_POLICY_GROUP,
    c.CATEGORY_TYPE
FROM SENSITIVITY_CATEGORIES c
JOIN SENSITIVITY_CATEGORIES p ON c.PARENT_CATEGORY_ID = p.CATEGORY_ID
WHERE c.IS_ACTIVE = TRUE;

-- View 5: Generic Exclusions
CREATE OR REPLACE VIEW V_GENERIC_EXCLUSIONS AS
SELECT 
    k.KEYWORD_ID,
    k.KEYWORD_STRING AS EXCLUSION_KEYWORD,
    k.RULE_CONFIG:exception_keywords AS EXCEPTION_KEYWORDS,
    k.RULE_CONFIG:reduction_factors AS REDUCTION_FACTORS,
    k.PRIORITY,
    k.DESCRIPTION
FROM SENSITIVE_KEYWORDS k
WHERE k.CONTEXT_TYPE = 'EXCLUSION'
  AND k.IS_ACTIVE = TRUE
ORDER BY k.PRIORITY;

-- View 6: Recent Classification Summary
CREATE OR REPLACE VIEW V_RECENT_CLASSIFICATIONS AS
SELECT 
    a.TABLE_NAME,
    a.COLUMN_NAME,
    a.CATEGORY,
    a.POLICY_GROUP,
    a.CONFIDENCE,
    a.DETECTION_METHOD,
    a.SEMANTIC_SCORE,
    a.KEYWORD_SCORE,
    a.PATTERN_SCORE,
    a.FINAL_SCORE,
    a.TIEBREAKER_USED,
    a.TIED_CATEGORIES,
    a.RUN_ID,
    a.SCANNED_AT
FROM SENSITIVE_AUDIT a
WHERE a.SCANNED_AT >= DATEADD(day, -30, CURRENT_TIMESTAMP())
ORDER BY a.SCANNED_AT DESC;

-- ============================================================================
-- PART 7: VERIFICATION
-- ============================================================================

SELECT '✅ CONSOLIDATED 4-TABLE ARCHITECTURE CREATED' AS STATUS;

-- Check enhanced columns exist
SELECT 'SENSITIVITY_CATEGORIES columns:' AS INFO;
SHOW COLUMNS IN SENSITIVITY_CATEGORIES;

SELECT 'SENSITIVE_KEYWORDS columns:' AS INFO;
SHOW COLUMNS IN SENSITIVE_KEYWORDS;

SELECT 'SENSITIVE_PATTERNS columns:' AS INFO;
SHOW COLUMNS IN SENSITIVE_PATTERNS;

SELECT 'SENSITIVE_AUDIT columns:' AS INFO;
SHOW COLUMNS IN SENSITIVE_AUDIT;

-- Check views created
SELECT 'Helper views created:' AS INFO;
SHOW VIEWS LIKE 'V_%';

-- Summary
SELECT 'SUMMARY' AS INFO;
SELECT 'Core Tables Enhanced' AS ITEM, '4' AS COUNT
UNION ALL
SELECT 'Helper Views Created', '6'
UNION ALL
SELECT 'Indexes Created', '15+'
UNION ALL
SELECT 'Total Tables Needed', '4 (vs 10+ with separate tables)';

SELECT '✅ Ready to populate with governance data!' AS NEXT_STEP;
