-- 015_missing_canonical_views.sql
-- Create missing canonical views for AI sensitive detection service

USE DATABASE IDENTIFIER($DATABASE);
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- VW_COMPLIANCE_MAPPING_CANONICAL
-- Maps sensitivity categories to compliance frameworks
CREATE OR REPLACE VIEW VW_COMPLIANCE_MAPPING_CANONICAL AS
SELECT 
    sc.CATEGORY_NAME,
    cm.COMPLIANCE_STANDARD AS COMPLIANCE_TAG,
    cm.DESCRIPTION,
    TRUE AS IS_ACTIVE
FROM COMPLIANCE_MAPPING cm
JOIN SENSITIVITY_CATEGORIES sc ON cm.CATEGORY_ID = sc.CATEGORY_ID
WHERE sc.IS_ACTIVE = TRUE;

-- VW_SENSITIVITY_WEIGHTS_CANONICAL  
-- Provides weights for different detection sources
CREATE OR REPLACE VIEW VW_SENSITIVITY_WEIGHTS_CANONICAL AS
SELECT 
    'KEYWORD' AS SOURCE,
    0.7 AS WEIGHT,
    TRUE AS IS_ACTIVE
UNION ALL
SELECT 
    'PATTERN' AS SOURCE,
    0.8 AS WEIGHT,
    TRUE AS IS_ACTIVE
UNION ALL
SELECT 
    'AI_SEMANTIC' AS SOURCE,
    0.9 AS WEIGHT,
    TRUE AS IS_ACTIVE
UNION ALL
SELECT 
    'METADATA' AS SOURCE,
    0.5 AS WEIGHT,
    TRUE AS IS_ACTIVE;

-- VW_SENSITIVITY_THRESHOLDS_CANONICAL
-- Provides confidence thresholds for sensitivity levels
CREATE OR REPLACE VIEW VW_SENSITIVITY_THRESHOLDS_CANONICAL AS
SELECT 
    'HIGH_THRESHOLD' AS NAME,
    0.8 AS VALUE,
    TRUE AS IS_ACTIVE
UNION ALL
SELECT 
    'MEDIUM_THRESHOLD' AS NAME,
    0.6 AS VALUE,
    TRUE AS IS_ACTIVE
UNION ALL
SELECT 
    'LOW_THRESHOLD' AS NAME,
    0.4 AS VALUE,
    TRUE AS IS_ACTIVE
UNION ALL
SELECT 
    'MIN_CONFIDENCE' AS NAME,
    0.3 AS VALUE,
    TRUE AS IS_ACTIVE;

-- VW_SENSITIVE_KEYWORDS_CANONICAL
-- Provides active sensitive keywords for detection
CREATE OR REPLACE VIEW VW_SENSITIVE_KEYWORDS_CANONICAL AS
SELECT 
    sk.KEYWORD_ID,
    sk.KEYWORD,
    sc.CATEGORY_NAME,
    sk.SENSITIVITY_WEIGHT,
    sk.IS_ACTIVE,
    sk.CREATED_BY,
    sk.CREATED_AT
FROM SENSITIVE_KEYWORDS sk
JOIN SENSITIVITY_CATEGORIES sc ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sk.IS_ACTIVE = TRUE AND sc.IS_ACTIVE = TRUE;

-- VW_SENSITIVE_PATTERNS_CANONICAL
-- Provides active sensitive patterns for detection
CREATE OR REPLACE VIEW VW_SENSITIVE_PATTERNS_CANONICAL AS
SELECT 
    sp.PATTERN_ID,
    sp.PATTERN_NAME,
    sp.PATTERN_REGEX,
    sc.CATEGORY_NAME,
    sp.SENSITIVITY_WEIGHT,
    sp.IS_NEGATIVE,
    sp.IS_ACTIVE,
    sp.CREATED_BY,
    sp.CREATED_AT
FROM SENSITIVE_PATTERNS sp
JOIN SENSITIVITY_CATEGORIES sc ON sp.CATEGORY_ID = sc.CATEGORY_ID
WHERE sp.IS_ACTIVE = TRUE AND sc.IS_ACTIVE = TRUE;

-- VW_SENSITIVITY_CATEGORIES_CANONICAL
-- Provides active sensitivity categories with risk levels
CREATE OR REPLACE VIEW VW_SENSITIVITY_CATEGORIES_CANONICAL AS
SELECT 
    CATEGORY_ID,
    CATEGORY_NAME,
    DESCRIPTION,
    CASE 
        WHEN UPPER(CATEGORY_NAME) IN ('PII', 'PHI', 'FINANCIAL', 'AUTHENTICATION') THEN TRUE
        ELSE FALSE
    END AS IS_HIGH_RISK,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_AT
FROM SENSITIVITY_CATEGORIES
WHERE IS_ACTIVE = TRUE;

-- TAG_ALLOWED_VALUES table for tag validation
CREATE OR REPLACE TABLE TAG_ALLOWED_VALUES (
    TAG_NAME STRING NOT NULL,
    ALLOWED_VALUE STRING NOT NULL,
    DESCRIPTION STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TAG_NAME, ALLOWED_VALUE)
);

-- Insert default tag values
INSERT INTO TAG_ALLOWED_VALUES (TAG_NAME, ALLOWED_VALUE, DESCRIPTION) VALUES
('CLASSIFICATION', 'Public', 'Public data - no restrictions'),
('CLASSIFICATION', 'Internal', 'Internal company data'),
('CLASSIFICATION', 'Restricted', 'Restricted access data'),
('CLASSIFICATION', 'Confidential', 'Highly confidential data'),
('CIA_LEVEL', '0', 'No CIA requirement'),
('CIA_LEVEL', '1', 'Low CIA requirement'),
('CIA_LEVEL', '2', 'Medium CIA requirement'),
('CIA_LEVEL', '3', 'High CIA requirement'),
('SPECIAL_CATEGORY', 'PII', 'Personally Identifiable Information'),
('SPECIAL_CATEGORY', 'PHI', 'Protected Health Information'),
('SPECIAL_CATEGORY', 'FINANCIAL', 'Financial data'),
('COMPLIANCE_CATEGORY', 'GDPR', 'GDPR compliance required'),
('COMPLIANCE_CATEGORY', 'HIPAA', 'HIPAA compliance required'),
('COMPLIANCE_CATEGORY', 'PCI_DSS', 'PCI DSS compliance required'),
('REVIEW_STATUS', 'PENDING', 'Pending review'),
('REVIEW_STATUS', 'APPROVED', 'Approved'),
('REVIEW_STATUS', 'REJECTED', 'Rejected');

-- AI_ASSISTANT_SENSITIVE_ASSETS table for storing AI detection results
CREATE OR REPLACE TABLE AI_ASSISTANT_SENSITIVE_ASSETS (
    RUN_ID STRING,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    TABLE_NAME STRING,
    COLUMN_NAME STRING,
    DETECTED_CATEGORY STRING,
    DETECTED_TYPE STRING,
    COMBINED_CONFIDENCE FLOAT,
    METHODS_USED VARIANT,
    COMPLIANCE_TAGS VARIANT,
    SAMPLE_METADATA VARIANT,
    DETECTION_REASON STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- AI_ASSISTANT_SENSITIVE_ASSETS_HISTORY table for audit trail
CREATE OR REPLACE TABLE AI_ASSISTANT_SENSITIVE_ASSETS_HISTORY (
    RUN_ID STRING,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    TABLE_NAME STRING,
    COLUMN_NAME STRING,
    DETECTED_CATEGORY STRING,
    DETECTED_TYPE STRING,
    COMBINED_CONFIDENCE FLOAT,
    METHODS_USED VARIANT,
    COMPLIANCE_TAGS VARIANT,
    SAMPLE_METADATA VARIANT,
    DETECTION_REASON STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);
