-- Creates or replaces the policy compliance metrics view
-- Ensure your current role has privileges and the database exists

CREATE OR REPLACE VIEW DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.VW_POLICY_COMPLIANCE_METRICS AS
SELECT 
    COUNT(*) AS TOTAL_ASSETS,
    COUNT(CASE WHEN CLASSIFICATION_LABEL IS NOT NULL THEN 1 END) AS CLASSIFIED_ASSETS,
    ROUND((COUNT(CASE WHEN CLASSIFICATION_LABEL IS NOT NULL THEN 1 END) * 100.0 / COUNT(*)), 2) AS CLASSIFICATION_COVERAGE_PERCENT,
    ROUND(AVG(DATEDIFF('day', CLASSIFICATION_DATE, CURRENT_DATE())), 1) AS AVG_CLASSIFICATION_AGE_DAYS,
    ROUND(AVG(CASE WHEN CLASSIFICATION_DATE >= DATEADD('day', -5, CURRENT_DATE()) THEN 1 ELSE 0 END) * 100, 2) AS TIMELINESS_5DAY_RULE,
    ROUND(AVG(CASE WHEN CONFIDENTIALITY_LEVEL = PREVIOUS_CONFIDENTIALITY THEN 1 ELSE 0 END) * 100, 2) AS ACCURACY_SCORE
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.ASSETS
LEFT JOIN DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_HISTORY USING (ASSET_ID);
