-- =====================================================
-- COMPLETE GOVERNANCE SCHEMA SETUP FOR AUTOMATED CLASSIFICATION
-- Creates all missing tables and views for the AI assistant system
-- =====================================================

USE DATABASE DATA_CLASSIFICATION_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- =====================================================
-- 1. SAMPLING METADATA TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS SAMPLE_METADATA (
    TABLE_NAME STRING,
    SAMPLE_HASH STRING,
    SAMPLE_SIZE NUMBER,
    SAMPLING_METHOD STRING,
    STRATIFY_COLUMN STRING,
    WEIGHT_COLUMN STRING,
    SAMPLING_TIMESTAMP TIMESTAMP_NTZ,
    CONFIG_VERSION NUMBER,
    DETAILS VARIANT,
    SAMPLE_QUERY_TEXT STRING,
    SAMPLE_SEED NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SAMPLING_CONFIG (
    TABLE_NAME STRING,
    METHOD STRING,
    FRACTION FLOAT,
    STRATIFY_COLUMN STRING,
    WEIGHT_COLUMN STRING,
    CONFIG_VERSION STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY STRING DEFAULT CURRENT_USER()
);

-- =====================================================
-- 2. SENSITIVE DETECTION TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS SENSITIVE_PATTERNS (
    PATTERN_ID STRING PRIMARY KEY,
    CATEGORY_ID STRING,
    PATTERN_NAME STRING,
    PATTERN_STRING STRING,
    DESCRIPTION STRING,
    SENSITIVITY_WEIGHT FLOAT DEFAULT 0.5,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ,
    VERSION_NUMBER INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENSITIVE_KEYWORDS (
    KEYWORD_ID STRING PRIMARY KEY,
    CATEGORY_ID STRING,
    KEYWORD_STRING STRING,
    MATCH_TYPE STRING DEFAULT 'EXACT',
    SENSITIVITY_WEIGHT FLOAT DEFAULT 0.5,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ,
    VERSION_NUMBER INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENSITIVITY_CATEGORIES (
    CATEGORY_ID STRING PRIMARY KEY,
    CATEGORY_NAME STRING,
    DESCRIPTION STRING,
    CONFIDENTIALITY_LEVEL NUMBER(1,0) DEFAULT 1,
    INTEGRITY_LEVEL NUMBER(1,0) DEFAULT 1,
    AVAILABILITY_LEVEL NUMBER(1,0) DEFAULT 1,
    DETECTION_THRESHOLD DOUBLE DEFAULT 0.5,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY STRING,
    UPDATED_AT TIMESTAMP_NTZ,
    VERSION_NUMBER INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENSITIVE_BUNDLES (
    BUNDLE_ID STRING PRIMARY KEY,
    BUNDLE_NAME STRING,
    DESCRIPTION STRING,
    COLUMNS VARIANT,
    MIN_MATCH_COUNT INTEGER DEFAULT 1,
    CONFIDENCE_BOOST FLOAT DEFAULT 0.1,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ,
    VERSION_NUMBER INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENSITIVE_AUDIT (
    AUDIT_ID NUMBER AUTOINCREMENT,
    FULL_NAME STRING,
    TABLE_NAME STRING,
    COLUMN_NAME STRING,
    CATEGORY STRING,
    CONFIDENCE NUMBER,
    CIA STRING,
    BUNDLE_DETECTED BOOLEAN,
    SAMPLE_HASH STRING,
    SAMPLING_METHOD STRING,
    SAMPLE_FRACTION FLOAT,
    DETAILS VARIANT,
    SCANNED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (AUDIT_ID)
);

-- =====================================================
-- 3. WORKFLOW AND REVIEW TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS CLASSIFICATION_WORKFLOW_TASKS (
    TASK_ID NUMBER AUTOINCREMENT,
    ASSET_PATH STRING,
    TASK_DATA VARIANT,
    STATUS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DUE_AT TIMESTAMP_NTZ,
    PRIMARY KEY (TASK_ID)
);

CREATE TABLE IF NOT EXISTS REVIEWER_ASSIGNMENTS (
    ASSIGNMENT_ID NUMBER AUTOINCREMENT,
    REVIEWER_EMAIL STRING,
    CATEGORY STRING,
    ROUTING_TYPE STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSIGNMENT_ID)
);

-- =====================================================
-- 4. AUDIT AND LOGGING TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS CLASSIFICATION_AUDIT_LOG (
    EVENT_ID NUMBER AUTOINCREMENT,
    EVENT_TYPE STRING,
    ASSET_PATH STRING,
    DETAILS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS DASHBOARD_METRICS (
    METRIC_ID NUMBER AUTOINCREMENT,
    METRIC_NAME STRING,
    METRIC_VALUE VARIANT,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (METRIC_ID)
);

-- =====================================================
-- 5. SEED BASIC CONFIGURATION DATA
-- =====================================================

-- Seed sensitivity categories
MERGE INTO SENSITIVITY_CATEGORIES AS target
USING (
    SELECT * FROM VALUES
        ('PERSONAL_DATA', 'Personal Data', 'PII and personal identifiable information', 3, 3, 2, 0.8, TRUE, CURRENT_USER()),
        ('FINANCIAL_DATA', 'Financial Data', 'Financial and payment information', 3, 3, 2, 0.85, TRUE, CURRENT_USER()),
        ('PROPRIETARY_DATA', 'Proprietary Data', 'Proprietary business information', 2, 2, 1, 0.7, TRUE, CURRENT_USER()),
        ('REGULATORY_DATA', 'Regulatory Data', 'Regulatory compliance data', 3, 3, 2, 0.9, TRUE, CURRENT_USER()),
        ('INTERNAL', 'Internal Data', 'Internal operational data', 1, 1, 1, 0.3, TRUE, CURRENT_USER())
) AS source(CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, CONFIDENTIALITY_LEVEL, INTEGRITY_LEVEL, AVAILABILITY_LEVEL, DETECTION_THRESHOLD, IS_ACTIVE, CREATED_BY)
ON target.CATEGORY_ID = source.CATEGORY_ID
WHEN NOT MATCHED THEN INSERT (
    CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, CONFIDENTIALITY_LEVEL, INTEGRITY_LEVEL, AVAILABILITY_LEVEL,
    DETECTION_THRESHOLD, IS_ACTIVE, CREATED_BY
) VALUES (
    source.CATEGORY_ID, source.CATEGORY_NAME, source.DESCRIPTION, source.CONFIDENTIALITY_LEVEL,
    source.INTEGRITY_LEVEL, source.AVAILABILITY_LEVEL, source.DETECTION_THRESHOLD, source.IS_ACTIVE, source.CREATED_BY
);

-- Seed basic keywords
MERGE INTO SENSITIVE_KEYWORDS AS target
USING (
    SELECT * FROM VALUES
        (UUID_STRING(), 'PERSONAL_DATA', 'email', 'CONTAINS', 0.9, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'PERSONAL_DATA', 'phone', 'CONTAINS', 0.8, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'PERSONAL_DATA', 'ssn', 'CONTAINS', 1.0, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'PERSONAL_DATA', 'social_security', 'CONTAINS', 1.0, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'FINANCIAL_DATA', 'credit_card', 'CONTAINS', 1.0, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'FINANCIAL_DATA', 'account_number', 'CONTAINS', 0.9, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'FINANCIAL_DATA', 'iban', 'CONTAINS', 0.9, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'REGULATORY_DATA', 'audit', 'CONTAINS', 0.8, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1),
        (UUID_STRING(), 'REGULATORY_DATA', 'compliance', 'CONTAINS', 0.7, TRUE, CURRENT_USER(), CURRENT_TIMESTAMP(), 1)
) AS source(KEYWORD_ID, CATEGORY_ID, KEYWORD_STRING, MATCH_TYPE, SENSITIVITY_WEIGHT, IS_ACTIVE, CREATED_BY, CREATED_AT, VERSION_NUMBER)
ON target.KEYWORD_ID = source.KEYWORD_ID
WHEN NOT MATCHED THEN INSERT (
    KEYWORD_ID, CATEGORY_ID, KEYWORD_STRING, MATCH_TYPE, SENSITIVITY_WEIGHT, IS_ACTIVE, CREATED_BY, CREATED_AT, VERSION_NUMBER
) VALUES (
    source.KEYWORD_ID, source.CATEGORY_ID, source.KEYWORD_STRING, source.MATCH_TYPE, source.SENSITIVITY_WEIGHT,
    source.IS_ACTIVE, source.CREATED_BY, source.CREATED_AT, source.VERSION_NUMBER
);

-- Seed basic patterns
MERGE INTO SENSITIVE_PATTERNS AS target
USING (
    SELECT * FROM VALUES
        (UUID_STRING(), 'PERSONAL_DATA', 'Email Pattern', '\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b', 'Email address pattern', 0.9),
        (UUID_STRING(), 'PERSONAL_DATA', 'Phone Pattern', '\\b\\+?\\d{1,3}?[-.\\s]?\\(?\\d{1,3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}\\b', 'Phone number pattern', 0.8),
        (UUID_STRING(), 'PERSONAL_DATA', 'SSN Pattern', '\\b\\d{3}-\\d{2}-\\d{4}\\b', 'US Social Security Number', 1.0),
        (UUID_STRING(), 'FINANCIAL_DATA', 'Credit Card Pattern', '\\b(?:\\d[ -]*?){13,16}\\b', 'Credit card number pattern', 1.0),
        (UUID_STRING(), 'FINANCIAL_DATA', 'IBAN Pattern', '\\b[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}\\b', 'IBAN pattern', 0.9)
) AS source(PATTERN_ID, CATEGORY_ID, PATTERN_NAME, PATTERN_STRING, DESCRIPTION, SENSITIVITY_WEIGHT)
ON target.PATTERN_ID = source.PATTERN_ID
WHEN NOT MATCHED THEN INSERT (
    PATTERN_ID, CATEGORY_ID, PATTERN_NAME, PATTERN_STRING, DESCRIPTION, SENSITIVITY_WEIGHT
) VALUES (
    source.PATTERN_ID, source.CATEGORY_ID, source.PATTERN_NAME, source.PATTERN_STRING, source.DESCRIPTION, source.SENSITIVITY_WEIGHT
);

-- Seed reviewer assignments
MERGE INTO REVIEWER_ASSIGNMENTS AS target
USING (
    SELECT * FROM VALUES
        (1, 'compliance@avendra.com', 'PERSONAL_DATA', 'STANDARD_REVIEW', TRUE, CURRENT_TIMESTAMP()),
        (2, 'compliance@avendra.com', 'FINANCIAL_DATA', 'EXPEDITED_REVIEW', TRUE, CURRENT_TIMESTAMP()),
        (3, 'compliance@avendra.com', 'REGULATORY_DATA', 'ENHANCED_REVIEW', TRUE, CURRENT_TIMESTAMP()),
        (4, 'admin@avendra.com', 'ALL', 'AUTO_APPROVE', TRUE, CURRENT_TIMESTAMP())
) AS source(ASSIGNMENT_ID, REVIEWER_EMAIL, CATEGORY, ROUTING_TYPE, IS_ACTIVE, CREATED_AT)
ON target.ASSIGNMENT_ID = source.ASSIGNMENT_ID
WHEN NOT MATCHED THEN INSERT (
    ASSIGNMENT_ID, REVIEWER_EMAIL, CATEGORY, ROUTING_TYPE, IS_ACTIVE, CREATED_AT
) VALUES (
    source.ASSIGNMENT_ID, source.REVIEWER_EMAIL, source.CATEGORY, source.ROUTING_TYPE, source.IS_ACTIVE, source.CREATED_AT
);

-- =====================================================
-- 6. CREATE VIEWS FOR THE PIPELINE
-- =====================================================

-- View for asset discovery
CREATE OR REPLACE VIEW VW_ASSET_DISCOVERY AS
SELECT
    CONCAT(TABLE_CATALOG, '.', TABLE_SCHEMA, '.', TABLE_NAME) AS FULL_NAME,
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    CREATED,
    LAST_ALTERED,
    ROW_COUNT,
    BYTES AS SIZE_BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA', 'SNOWFLAKE')
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;

-- View for column metadata
CREATE OR REPLACE VIEW VW_COLUMN_METADATA AS
SELECT
    CONCAT(TABLE_CATALOG, '.', TABLE_SCHEMA, '.', TABLE_NAME) AS TABLE_FULL_NAME,
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA', 'SNOWFLAKE')
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;

-- View for governance enrichment
CREATE OR REPLACE VIEW VW_GOVERNANCE_ENRICHMENT AS
SELECT
    A.FULL_NAME,
    A.BUSINESS_UNIT,
    A.DATA_OWNER,
    A.DATA_STEWARD,
    A.CLASSIFICATION_TAG,
    A.CONFIDENTIALITY_LEVEL,
    A.INTEGRITY_LEVEL,
    A.AVAILABILITY_LEVEL,
    A.RISK_SCORE,
    A.DESCRIPTION,
    A.TAGS,
    A.IS_ACTIVE
FROM ASSETS A
WHERE A.IS_ACTIVE = TRUE;

-- =====================================================
-- 7. DASHBOARD METRICS INITIALIZATION
-- =====================================================

MERGE INTO DASHBOARD_METRICS AS target
USING (
    SELECT * FROM VALUES
        (1, 'DETECTION_ACCURACY', 0.0, CURRENT_TIMESTAMP()),
        (2, 'POLICY_COMPLIANCE_RATE', 0.0, CURRENT_TIMESTAMP()),
        (3, 'TOTAL_ASSETS_SCANNED', 0, CURRENT_TIMESTAMP()),
        (4, 'SLA_COMPLIANCE_RATE', 0.0, CURRENT_TIMESTAMP())
) AS source(METRIC_ID, METRIC_NAME, METRIC_VALUE, LAST_UPDATED)
ON target.METRIC_ID = source.METRIC_ID
WHEN NOT MATCHED THEN INSERT (
    METRIC_ID, METRIC_NAME, METRIC_VALUE, LAST_UPDATED
) VALUES (
    source.METRIC_ID, source.METRIC_NAME, source.METRIC_VALUE, source.LAST_UPDATED
);

-- =====================================================
-- 8. GRANT PERMISSIONS
-- =====================================================

-- Grant permissions to data classification role (if exists)
GRANT USAGE ON SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO ROLE DATA_CLASSIFICATION_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO ROLE DATA_CLASSIFICATION_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DATA_CLASSIFICATION_GOVERNANCE TO ROLE DATA_CLASSIFICATION_ROLE;

-- =====================================================
-- SETUP COMPLETE
-- =====================================================

SELECT 'Governance schema setup complete. All tables and views created.' AS STATUS, CURRENT_TIMESTAMP() AS COMPLETED_AT;