-- Add Missing Columns to SENSITIVE_KEYWORDS Table
-- This ensures all required columns exist for proper keyword management

USE DATABASE DATA_CLASSIFICATION_GOVERNANCE;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- Add CREATED_BY column if it doesn't exist
ALTER TABLE IF EXISTS SENSITIVE_KEYWORDS 
ADD COLUMN IF NOT EXISTS CREATED_BY STRING;

-- Add UPDATED_BY column if it doesn't exist
ALTER TABLE IF EXISTS SENSITIVE_KEYWORDS 
ADD COLUMN IF NOT EXISTS UPDATED_BY STRING;

-- Add SCORE column if it doesn't exist (duplicate of SENSITIVITY_WEIGHT for compatibility)
ALTER TABLE IF EXISTS SENSITIVE_KEYWORDS 
ADD COLUMN IF NOT EXISTS SCORE FLOAT;

-- Update existing rows to populate CREATED_BY if NULL
UPDATE SENSITIVE_KEYWORDS
SET CREATED_BY = CURRENT_USER()
WHERE CREATED_BY IS NULL;

-- Update existing rows to populate SCORE from SENSITIVITY_WEIGHT if NULL
UPDATE SENSITIVE_KEYWORDS
SET SCORE = SENSITIVITY_WEIGHT
WHERE SCORE IS NULL;

-- Verify the changes
SELECT 
    'Column Check' as STATUS,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_KEYWORDS'
ORDER BY ORDINAL_POSITION;

-- Show sample data with all columns
SELECT 
    'Sample Data' as STATUS,
    KEYWORD_STRING,
    MATCH_TYPE,
    SENSITIVITY_WEIGHT,
    SCORE,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    VERSION_NUMBER
FROM SENSITIVE_KEYWORDS
LIMIT 5;
