-- Quick Check: Where are my keywords saved?
-- This shows the exact table location and recent data

-- 1. Show database and schema
SELECT CURRENT_DATABASE() as CURRENT_DB, CURRENT_SCHEMA() as CURRENT_SCHEMA;

-- 2. Show table location
SELECT 
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME,
    ROW_COUNT,
    BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'SENSITIVE_KEYWORDS';

-- 3. Show recent keywords (last 10 updates)
SELECT 
    KEYWORD_STRING,
    MATCH_TYPE,
    SENSITIVITY_WEIGHT,
    SCORE,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    VERSION_NUMBER
FROM DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS
ORDER BY COALESCE(UPDATED_AT, CREATED_AT) DESC
LIMIT 10;

-- 4. Count keywords by category
SELECT 
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    COUNT(*) as KEYWORD_COUNT
FROM DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
    ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sk.IS_ACTIVE = TRUE
GROUP BY sc.CATEGORY_NAME, sc.POLICY_GROUP
ORDER BY KEYWORD_COUNT DESC;

-- 5. Check if SOCIAL_SECURITY_NUMBER is there
SELECT 
    'SOCIAL_SECURITY_NUMBER Check' as INFO,
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    sk.MATCH_TYPE,
    sk.SENSITIVITY_WEIGHT,
    sk.CREATED_BY,
    sk.CREATED_AT,
    sk.UPDATED_BY,
    sk.UPDATED_AT,
    sk.VERSION_NUMBER
FROM DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
    ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE LOWER(sk.KEYWORD_STRING) LIKE '%social%security%';
