-- ============================================================================
-- CHECK SOCIAL_SECURITY_NUMBER CATEGORIZATION
-- ============================================================================

USE DATABASE DATA_CLASSIFICATION_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- Check current categorization
SELECT 
    'CURRENT CATEGORIZATION' AS STATUS,
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.CATEGORY_ID,
    sk.SENSITIVITY_WEIGHT,
    sk.MATCH_TYPE,
    sk.IS_ACTIVE,
    sk.CREATED_AT,
    sk.UPDATED_AT
FROM SENSITIVE_KEYWORDS sk
JOIN SENSITIVITY_CATEGORIES sc ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sk.KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER';

-- Check if PII category exists
SELECT 
    'PII CATEGORY CHECK' AS STATUS,
    CATEGORY_ID,
    CATEGORY_NAME,
    POLICY_GROUP
FROM SENSITIVITY_CATEGORIES
WHERE CATEGORY_NAME = 'PII';

-- Check if SOC2 category exists
SELECT 
    'SOC2 CATEGORY CHECK' AS STATUS,
    CATEGORY_ID,
    CATEGORY_NAME,
    POLICY_GROUP
FROM SENSITIVITY_CATEGORIES
WHERE CATEGORY_NAME = 'SOC2';
