-- Check actual table structure in Snowflake
use database DATA_CLASSIFICATION_DB;

-- Check SENSITIVE_PATTERNS table structure
describe table DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_PATTERNS;

-- Check SENSITIVE_KEYWORDS table structure  
describe table DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS;

-- Check SENSITIVITY_CATEGORIES table structure
describe table DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES;

-- Check SENSITIVITY_THRESHOLDS table structure
describe table DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_THRESHOLDS;

-- Check SENSITIVITY_WEIGHTS table structure
describe table DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_WEIGHTS;
