-- Check if UPDATED_BY column exists in SENSITIVE_KEYWORDS table

USE DATABASE DATA_CLASSIFICATION_GOVERNANCE;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- Show all columns in the table
DESCRIBE TABLE SENSITIVE_KEYWORDS;

-- Check specifically for UPDATED_BY and SCORE columns
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_KEYWORDS'
  AND COLUMN_NAME IN ('UPDATED_BY', 'SCORE', 'SENSITIVITY_WEIGHT', 'VERSION_NUMBER')
ORDER BY COLUMN_NAME;

-- Count total keywords
SELECT COUNT(*) as TOTAL_KEYWORDS FROM SENSITIVE_KEYWORDS;

-- Show sample data
SELECT 
    KEYWORD_STRING,
    MATCH_TYPE,
    SENSITIVITY_WEIGHT,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_AT,
    VERSION_NUMBER
FROM SENSITIVE_KEYWORDS
ORDER BY CREATED_AT DESC
LIMIT 5;
