-- Create the RECLASSIFICATION_REQUESTS table if it doesn't exist
CREATE TABLE IF NOT EXISTS identifier($dbname)||'.'||identifier($sch)||'.RECLASSIFICATION_REQUESTS' (
    ID STRING PRIMARY KEY,
    ASSET_FULL_NAME STRING NOT NULL,
    REQUESTED_BY STRING NOT NULL,
    CURRENT_LABEL STRING,
    REQUESTED_LABEL STRING NOT NULL,
    STATUS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DETAILS VARIANT
);

-- Create or replace the VW_CLASSIFICATION_REVIEWS view
CREATE OR REPLACE VIEW identifier($dbname)||'.'||identifier($sch)||'.VW_CLASSIFICATION_REVIEWS' AS
SELECT 
    ID,
    ASSET_FULL_NAME,
    REQUESTED_BY AS CREATED_BY,
    CURRENT_LABEL,
    REQUESTED_LABEL,
    STATUS,
    CREATED_AT,
    UPDATED_AT,
    DETAILS
FROM identifier($dbname)||'.'||identifier($sch)||'.RECLASSIFICATION_REQUESTS'
WHERE UPPER(COALESCE(STATUS,'')) IN ('SUBMITTED');
