-- Diagnostic: Check if keywords are being saved to SENSITIVE_KEYWORDS table
-- Run this after trying to update a keyword in the UI

USE DATABASE DATA_CLASSIFICATION_GOVERNANCE;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- 1. Check if the table has the required columns
SELECT 
    'Table Structure' as CHECK_TYPE,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_KEYWORDS'
ORDER BY ORDINAL_POSITION;

-- 2. Check recent keywords (last 10)
SELECT 
    'Recent Keywords' as CHECK_TYPE,
    KEYWORD_STRING,
    MATCH_TYPE,
    SENSITIVITY_WEIGHT,
    SCORE,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_AT,
    UPDATED_BY,
    UPDATED_AT,
    VERSION_NUMBER
FROM SENSITIVE_KEYWORDS
ORDER BY COALESCE(UPDATED_AT, CREATED_AT) DESC
LIMIT 10;

-- 3. Check if SOCIAL_SECURITY_NUMBER exists
SELECT 
    'SOCIAL_SECURITY_NUMBER Check' as CHECK_TYPE,
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    sk.MATCH_TYPE,
    sk.SENSITIVITY_WEIGHT,
    sk.SCORE,
    sk.CREATED_BY,
    sk.CREATED_AT,
    sk.UPDATED_BY,
    sk.UPDATED_AT,
    sk.VERSION_NUMBER
FROM SENSITIVE_KEYWORDS sk
JOIN SENSITIVITY_CATEGORIES sc ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE LOWER(sk.KEYWORD_STRING) = 'social_security_number';

-- 4. Check if columns are missing (will show NULL if missing)
SELECT 
    'Missing Columns Check' as CHECK_TYPE,
    KEYWORD_STRING,
    CREATED_BY,
    UPDATED_BY,
    SCORE,
    VERSION_NUMBER
FROM SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER'
   OR KEYWORD_STRING = 'social_security_number';

-- 5. Count total keywords
SELECT 
    'Total Keywords' as CHECK_TYPE,
    COUNT(*) as TOTAL_COUNT,
    COUNT(DISTINCT CATEGORY_ID) as UNIQUE_CATEGORIES,
    COUNT(CASE WHEN UPDATED_BY IS NOT NULL THEN 1 END) as UPDATED_COUNT,
    COUNT(CASE WHEN SCORE IS NOT NULL THEN 1 END) as WITH_SCORE_COUNT
FROM SENSITIVE_KEYWORDS;

-- 6. Check if there are any errors in the audit log
SELECT 
    'Audit Log Check' as CHECK_TYPE,
    ACTION_TYPE,
    KEYWORD,
    CATEGORY,
    DESCRIPTION,
    CREATED_BY,
    CREATED_AT
FROM SENSITIVE_AUDIT
WHERE LOWER(KEYWORD) LIKE '%social%security%'
ORDER BY CREATED_AT DESC
LIMIT 5;
