-- Diagnostic Script: Check SOCIAL_SECURITY_NUMBER Keyword Mapping
-- This script checks why SOCIAL_SECURITY_NUMBER might be classified as SOC2 instead of PII

-- 1. Check all keywords related to 'social_security' in SENSITIVE_KEYWORDS table
SELECT 
    KEYWORD_STRING,
    CATEGORY_ID,
    MATCH_TYPE,
    SCORE,
    IS_ACTIVE
FROM DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS
WHERE LOWER(KEYWORD_STRING) LIKE '%social%security%'
   OR LOWER(KEYWORD_STRING) LIKE '%ssn%'
ORDER BY KEYWORD_STRING;

-- 2. Check which category these keywords map to
SELECT 
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    sk.MATCH_TYPE,
    sk.SCORE,
    sk.IS_ACTIVE
FROM DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
    ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE LOWER(sk.KEYWORD_STRING) LIKE '%social%security%'
   OR LOWER(sk.KEYWORD_STRING) LIKE '%ssn%'
ORDER BY sk.KEYWORD_STRING;

-- 3. Check if there are duplicate or conflicting entries
SELECT 
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    COUNT(*) as entry_count
FROM DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
    ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE LOWER(sk.KEYWORD_STRING) LIKE '%social%security%'
   OR LOWER(sk.KEYWORD_STRING) LIKE '%ssn%'
GROUP BY sk.KEYWORD_STRING, sc.CATEGORY_NAME, sc.POLICY_GROUP
HAVING COUNT(*) > 1;

-- 4. Check all PII keywords to ensure social_security is there
SELECT 
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP
FROM DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
    ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sc.POLICY_GROUP = 'PII'
  AND sk.IS_ACTIVE = TRUE
ORDER BY sk.KEYWORD_STRING
LIMIT 50;

-- 5. Check if there's a SOC2 category with 'social_security' keyword (this would be wrong)
SELECT 
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    sk.SCORE,
    sk.IS_ACTIVE
FROM DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
    ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sc.POLICY_GROUP = 'SOC2'
  AND (LOWER(sk.KEYWORD_STRING) LIKE '%social%security%' 
       OR LOWER(sk.KEYWORD_STRING) LIKE '%ssn%');
