-- ============================================================================
-- FIND SOCIAL_SECURITY_NUMBER - Search Everywhere
-- ============================================================================
-- This script searches for SOCIAL_SECURITY_NUMBER in ALL possible locations
-- ============================================================================

-- Method 1: Search in DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE
SELECT 
    'DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS' AS LOCATION,
    COUNT(*) AS SSN_FOUND
FROM DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER';

-- Method 2: Search in DATA_CLASSIFICATION_DB.GOVERNANCE  
SELECT 
    'DATA_CLASSIFICATION_DB.GOVERNANCE.SENSITIVE_KEYWORDS' AS LOCATION,
    COUNT(*) AS SSN_FOUND
FROM DATA_CLASSIFICATION_DB.GOVERNANCE.SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER';

-- Method 3: Show details if found in DATA_CLASSIFICATION_GOVERNANCE
SELECT 
    'FOUND IN DATA_CLASSIFICATION_GOVERNANCE' AS STATUS,
    *
FROM DATA_CLASSIFICATION_GOVERNANCE.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER';

-- Method 4: Show details if found in DATA_CLASSIFICATION_DB
SELECT 
    'FOUND IN DATA_CLASSIFICATION_DB' AS STATUS,
    *
FROM DATA_CLASSIFICATION_DB.GOVERNANCE.SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER';

-- Method 5: Check what's in your CURRENT context
SELECT CURRENT_DATABASE() || '.' || CURRENT_SCHEMA() AS CURRENT_CONTEXT;

SELECT 
    'FOUND IN CURRENT CONTEXT' AS STATUS,
    *
FROM SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER';

-- ============================================================================
-- DIAGNOSIS
-- ============================================================================
-- If Method 3 returns 1 row → Data is in DATA_CLASSIFICATION_GOVERNANCE
-- If Method 4 returns 1 row → Data is in DATA_CLASSIFICATION_DB
-- If both return 0 rows → SOCIAL_SECURITY_NUMBER was never inserted!
-- ============================================================================
