-- Fix: Add missing columns to SENSITIVE_KEYWORDS table
-- Run this first before updating the Python method

USE DATABASE DATA_CLASSIFICATION_GOVERNANCE;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- Check current columns
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_KEYWORDS'
ORDER BY ORDINAL_POSITION;

-- Add SCORE column if it doesn't exist
ALTER TABLE SENSITIVE_KEYWORDS 
ADD COLUMN IF NOT EXISTS SCORE FLOAT;

-- Add UPDATED_BY column if it doesn't exist
ALTER TABLE SENSITIVE_KEYWORDS 
ADD COLUMN IF NOT EXISTS UPDATED_BY STRING;

-- Update existing rows to populate SCORE from SENSITIVITY_WEIGHT
UPDATE SENSITIVE_KEYWORDS
SET SCORE = SENSITIVITY_WEIGHT
WHERE SCORE IS NULL;

-- Update existing rows to populate UPDATED_BY if NULL
UPDATE SENSITIVE_KEYWORDS
SET UPDATED_BY = CREATED_BY
WHERE UPDATED_BY IS NULL AND CREATED_BY IS NOT NULL;

-- Verify the changes
SELECT 
    'After Fix - Column Check' as STATUS,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_KEYWORDS'
ORDER BY ORDINAL_POSITION;

-- Test insert to verify it works
INSERT INTO SENSITIVE_KEYWORDS (
    KEYWORD_ID,
    CATEGORY_ID,
    KEYWORD_STRING,
    MATCH_TYPE,
    SENSITIVITY_WEIGHT,
    SCORE,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_AT,
    VERSION_NUMBER
)
SELECT 
    UUID_STRING(),
    (SELECT CATEGORY_ID FROM SENSITIVITY_CATEGORIES WHERE POLICY_GROUP = 'PII' LIMIT 1),
    'TEST_KEYWORD_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS'),
    'CONTAINS',
    0.8,
    0.8,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    1;

-- Verify test insert worked
SELECT 
    'Test Insert Verification' as STATUS,
    KEYWORD_STRING,
    MATCH_TYPE,
    SENSITIVITY_WEIGHT,
    SCORE,
    CREATED_BY,
    CREATED_AT
FROM SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING LIKE 'TEST_KEYWORD_%'
ORDER BY CREATED_AT DESC
LIMIT 1;

-- Clean up test data
DELETE FROM SENSITIVE_KEYWORDS
WHERE KEYWORD_STRING LIKE 'TEST_KEYWORD_%';

SELECT '✅ All fixes applied successfully!' as STATUS;
