-- ============================================================================
-- QUICK FIX: Update SOCIAL_SECURITY_NUMBER to PII (One Command)
-- ============================================================================

-- Your current data:
--   KEYWORD_ID: dc825979-d136-4076-bb75-30288c8ef6e5
--   CATEGORY_ID: 3e47f6fd-d870-41a8-b75f-e967bb839475 (probably SOC2)
--   KEYWORD_STRING: SOCIAL_SECURITY_NUMBER

-- This will change it to PII:

UPDATE DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS
SET 
    CATEGORY_ID = (
        SELECT CATEGORY_ID 
        FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES 
        WHERE CATEGORY_NAME = 'PII'
    ),
    UPDATED_BY = CURRENT_USER(),
    UPDATED_AT = CURRENT_TIMESTAMP(),
    VERSION_NUMBER = VERSION_NUMBER + 1
WHERE KEYWORD_ID = 'dc825979-d136-4076-bb75-30288c8ef6e5';

-- Verify:
SELECT 
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME AS NEW_CATEGORY
FROM DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVE_KEYWORDS sk
JOIN DATA_CLASSIFICATION_DB.DATA_CLASSIFICATION_GOVERNANCE.SENSITIVITY_CATEGORIES sc
  ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sk.KEYWORD_ID = 'dc825979-d136-4076-bb75-30288c8ef6e5';

-- Expected: NEW_CATEGORY = 'PII'
