-- ============================================================================
-- IMMEDIATE FIX: Change SOCIAL_SECURITY_NUMBER to PII
-- ============================================================================

USE DATABASE DATA_CLASSIFICATION_DB;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- Show the problem
SELECT 
    '❌ CURRENT STATE (WRONG)' AS STATUS,
    sk.KEYWORD_ID,
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME AS WRONG_CATEGORY,
    sk.CATEGORY_ID
FROM SENSITIVE_KEYWORDS sk
JOIN SENSITIVITY_CATEGORIES sc ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sk.KEYWORD_ID = 'dc825979-d136-4076-bb75-30288c8ef6e5';

-- Get PII category ID
SELECT 
    '✅ PII CATEGORY ID' AS INFO,
    CATEGORY_ID,
    CATEGORY_NAME
FROM SENSITIVITY_CATEGORIES
WHERE CATEGORY_NAME = 'PII';

-- Fix it
UPDATE SENSITIVE_KEYWORDS
SET 
    CATEGORY_ID = (SELECT CATEGORY_ID FROM SENSITIVITY_CATEGORIES WHERE CATEGORY_NAME = 'PII'),
    KEYWORD_STRING = 'SOCIAL_SECURITY_NUMBER',  -- Also normalize to uppercase
    UPDATED_BY = CURRENT_USER(),
    UPDATED_AT = CURRENT_TIMESTAMP(),
    VERSION_NUMBER = COALESCE(VERSION_NUMBER, 1) + 1
WHERE KEYWORD_ID = 'dc825979-d136-4076-bb75-30288c8ef6e5';

-- Verify
SELECT 
    '✅ FIXED STATE (CORRECT)' AS STATUS,
    sk.KEYWORD_ID,
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME AS CORRECT_CATEGORY,
    sk.CATEGORY_ID,
    sk.VERSION_NUMBER
FROM SENSITIVE_KEYWORDS sk
JOIN SENSITIVITY_CATEGORIES sc ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE sk.KEYWORD_ID = 'dc825979-d136-4076-bb75-30288c8ef6e5';

-- Expected: CATEGORY_NAME = 'PII'
