-- ============================================================================
-- TEST_CUSTOMER_MASTER Category Classification Fix
-- ============================================================================
-- This script adds specific keywords to the SENSITIVE_KEYWORDS table to ensure
-- accurate classification of the TEST_CUSTOMER_MASTER table columns.
-- 
-- Run this script in your Snowflake worksheet to update the governance database.
-- ============================================================================

USE DATABASE DATA_CLASSIFICATION_DB;
USE SCHEMA GOVERNANCE;

-- ============================================================================
-- STEP 1: Add PII Keywords (23 columns)
-- ============================================================================
-- These columns contain personal identity, biometric, demographic, or location data

INSERT INTO SENSITIVE_KEYWORDS (KEYWORD, CATEGORY, MATCH_TYPE, CREATED_BY, UPDATED_BY)
SELECT * FROM (
    SELECT 'CUSTOMER_ID' AS KEYWORD, 'PII' AS CATEGORY, 'EXACT' AS MATCH_TYPE, CURRENT_USER() AS CREATED_BY, CURRENT_USER() AS UPDATED_BY
    UNION ALL SELECT 'SOCIAL_SECURITY_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'TAX_IDENTIFICATION_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'NATIONAL_ID_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'DRIVERS_LICENSE_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'PASSPORT_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'VOTER_ID_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'MILITARY_ID_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'ALIEN_REGISTRATION_NUMBER', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'BIOMETRIC_HASH', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'VOICE_PRINT_ID', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'FINGERPRINT_HASH', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'HEALTH_CONDITION', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'ETHNICITY', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'RELIGION', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'DISABILITY_STATUS', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'GPS_COORDINATES', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'LAST_KNOWN_LOCATION', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'DEVICE_LOCATION_HISTORY', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'TWO_FACTOR_PHONE', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'TWO_FACTOR_EMAIL', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'VOIP_CALL_RECORDS', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'VIDEO_CALL_SIGNATURE', 'PII', 'EXACT', CURRENT_USER(), CURRENT_USER()
) AS new_keywords
WHERE NOT EXISTS (
    SELECT 1 FROM SENSITIVE_KEYWORDS sk 
    WHERE sk.KEYWORD = new_keywords.KEYWORD 
    AND sk.CATEGORY = new_keywords.CATEGORY
);

-- ============================================================================
-- STEP 2: Add SOX Keywords (13 columns)
-- ============================================================================
-- These columns contain financial, banking, payment, or business registration data

INSERT INTO SENSITIVE_KEYWORDS (KEYWORD, CATEGORY, MATCH_TYPE, CREATED_BY, UPDATED_BY)
SELECT * FROM (
    SELECT 'BANK_ACCOUNT_NUMBER' AS KEYWORD, 'SOX' AS CATEGORY, 'EXACT' AS MATCH_TYPE, CURRENT_USER() AS CREATED_BY, CURRENT_USER() AS UPDATED_BY
    UNION ALL SELECT 'BANK_ROUTING_NUMBER', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'BANK_IBAN', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'BANK_SWIFT_CODE', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'CREDIT_CARD_NUMBER', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'CREDIT_CARD_EXPIRY_DATE', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'CREDIT_CARD_CVV', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'CREDIT_CARD_HOLDER_NAME', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'ANNUAL_INCOME', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'CREDIT_SCORE', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'TAX_RETURN_ID', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'PAYMENT_HISTORY', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'BUSINESS_REGISTRATION_NUMBER', 'SOX', 'EXACT', CURRENT_USER(), CURRENT_USER()
) AS new_keywords
WHERE NOT EXISTS (
    SELECT 1 FROM SENSITIVE_KEYWORDS sk 
    WHERE sk.KEYWORD = new_keywords.KEYWORD 
    AND sk.CATEGORY = new_keywords.CATEGORY
);

-- ============================================================================
-- STEP 3: Add SOC2 Keywords (14 columns)
-- ============================================================================
-- These columns contain authentication, authorization, encryption, or confidential business data

INSERT INTO SENSITIVE_KEYWORDS (KEYWORD, CATEGORY, MATCH_TYPE, CREATED_BY, UPDATED_BY)
SELECT * FROM (
    SELECT 'USER_PASSWORD_HASH' AS KEYWORD, 'SOC2' AS CATEGORY, 'EXACT' AS MATCH_TYPE, CURRENT_USER() AS CREATED_BY, CURRENT_USER() AS UPDATED_BY
    UNION ALL SELECT 'API_KEY', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'API_SECRET', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'OAUTH_TOKEN', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'OAUTH_REFRESH_TOKEN', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'SECURITY_QUESTION_1', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'SECURITY_ANSWER_1_HASH', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'SECURITY_QUESTION_2', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'SECURITY_ANSWER_2_HASH', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'IP_ADDRESS', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'LOGIN_DEVICE_ID', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'TRADE_SECRET_KEY', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'CONFIDENTIAL_AGREEMENT_ID', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
    UNION ALL SELECT 'ENCRYPTED_MESSAGES', 'SOC2', 'EXACT', CURRENT_USER(), CURRENT_USER()
) AS new_keywords
WHERE NOT EXISTS (
    SELECT 1 FROM SENSITIVE_KEYWORDS sk 
    WHERE sk.KEYWORD = new_keywords.KEYWORD 
    AND sk.CATEGORY = new_keywords.CATEGORY
);

-- ============================================================================
-- STEP 4: Verify the keywords were added
-- ============================================================================

SELECT 
    CATEGORY,
    COUNT(*) AS KEYWORD_COUNT
FROM SENSITIVE_KEYWORDS
WHERE KEYWORD IN (
    'CUSTOMER_ID', 'SOCIAL_SECURITY_NUMBER', 'TAX_IDENTIFICATION_NUMBER', 'NATIONAL_ID_NUMBER',
    'DRIVERS_LICENSE_NUMBER', 'PASSPORT_NUMBER', 'VOTER_ID_NUMBER', 'MILITARY_ID_NUMBER',
    'ALIEN_REGISTRATION_NUMBER', 'BIOMETRIC_HASH', 'VOICE_PRINT_ID', 'FINGERPRINT_HASH',
    'HEALTH_CONDITION', 'ETHNICITY', 'RELIGION', 'DISABILITY_STATUS', 'GPS_COORDINATES',
    'LAST_KNOWN_LOCATION', 'DEVICE_LOCATION_HISTORY', 'TWO_FACTOR_PHONE', 'TWO_FACTOR_EMAIL',
    'VOIP_CALL_RECORDS', 'VIDEO_CALL_SIGNATURE',
    'BANK_ACCOUNT_NUMBER', 'BANK_ROUTING_NUMBER', 'BANK_IBAN', 'BANK_SWIFT_CODE',
    'CREDIT_CARD_NUMBER', 'CREDIT_CARD_EXPIRY_DATE', 'CREDIT_CARD_CVV', 'CREDIT_CARD_HOLDER_NAME',
    'ANNUAL_INCOME', 'CREDIT_SCORE', 'TAX_RETURN_ID', 'PAYMENT_HISTORY', 'BUSINESS_REGISTRATION_NUMBER',
    'USER_PASSWORD_HASH', 'API_KEY', 'API_SECRET', 'OAUTH_TOKEN', 'OAUTH_REFRESH_TOKEN',
    'SECURITY_QUESTION_1', 'SECURITY_ANSWER_1_HASH', 'SECURITY_QUESTION_2', 'SECURITY_ANSWER_2_HASH',
    'IP_ADDRESS', 'LOGIN_DEVICE_ID', 'TRADE_SECRET_KEY', 'CONFIDENTIAL_AGREEMENT_ID', 'ENCRYPTED_MESSAGES'
)
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- Expected Results:
-- PII: 23 keywords
-- SOC2: 14 keywords
-- SOX: 13 keywords
-- Total: 50 keywords

-- ============================================================================
-- STEP 5: View all added keywords
-- ============================================================================

SELECT 
    KEYWORD,
    CATEGORY,
    MATCH_TYPE,
    CREATED_BY,
    CREATED_AT
FROM SENSITIVE_KEYWORDS
WHERE KEYWORD IN (
    'CUSTOMER_ID', 'SOCIAL_SECURITY_NUMBER', 'TAX_IDENTIFICATION_NUMBER', 'NATIONAL_ID_NUMBER',
    'DRIVERS_LICENSE_NUMBER', 'PASSPORT_NUMBER', 'VOTER_ID_NUMBER', 'MILITARY_ID_NUMBER',
    'ALIEN_REGISTRATION_NUMBER', 'BIOMETRIC_HASH', 'VOICE_PRINT_ID', 'FINGERPRINT_HASH',
    'HEALTH_CONDITION', 'ETHNICITY', 'RELIGION', 'DISABILITY_STATUS', 'GPS_COORDINATES',
    'LAST_KNOWN_LOCATION', 'DEVICE_LOCATION_HISTORY', 'TWO_FACTOR_PHONE', 'TWO_FACTOR_EMAIL',
    'VOIP_CALL_RECORDS', 'VIDEO_CALL_SIGNATURE',
    'BANK_ACCOUNT_NUMBER', 'BANK_ROUTING_NUMBER', 'BANK_IBAN', 'BANK_SWIFT_CODE',
    'CREDIT_CARD_NUMBER', 'CREDIT_CARD_EXPIRY_DATE', 'CREDIT_CARD_CVV', 'CREDIT_CARD_HOLDER_NAME',
    'ANNUAL_INCOME', 'CREDIT_SCORE', 'TAX_RETURN_ID', 'PAYMENT_HISTORY', 'BUSINESS_REGISTRATION_NUMBER',
    'USER_PASSWORD_HASH', 'API_KEY', 'API_SECRET', 'OAUTH_TOKEN', 'OAUTH_REFRESH_TOKEN',
    'SECURITY_QUESTION_1', 'SECURITY_ANSWER_1_HASH', 'SECURITY_QUESTION_2', 'SECURITY_ANSWER_2_HASH',
    'IP_ADDRESS', 'LOGIN_DEVICE_ID', 'TRADE_SECRET_KEY', 'CONFIDENTIAL_AGREEMENT_ID', 'ENCRYPTED_MESSAGES'
)
ORDER BY CATEGORY, KEYWORD;

-- ============================================================================
-- NEXT STEPS
-- ============================================================================
-- 1. Run this script in Snowflake to add the keywords
-- 2. Go to the AI Classification Pipeline in the dashboard
-- 3. Click "🚀 Run New Scan" to re-classify the TEST_CUSTOMER_MASTER table
-- 4. Verify that all 50 columns are correctly categorized:
--    - 23 PII columns
--    - 13 SOX columns
--    - 14 SOC2 columns
--    - 2 Non-Sensitive columns (CREATED_AT, UPDATED_AT) should be excluded
-- ============================================================================
