-- Quick diagnostic: Check what's actually in SENSITIVE_KEYWORDS for social_security
-- Run this to see the current state

USE DATABASE DATA_CLASSIFICATION_GOVERNANCE;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- Check all social_security related keywords
SELECT 
    sk.KEYWORD_STRING,
    sc.CATEGORY_NAME,
    sc.POLICY_GROUP,
    sk.MATCH_TYPE,
    sk.SCORE,
    sk.IS_ACTIVE,
    sk.CREATED_BY,
    sk.CREATED_AT
FROM SENSITIVE_KEYWORDS sk
JOIN SENSITIVITY_CATEGORIES sc ON sk.CATEGORY_ID = sc.CATEGORY_ID
WHERE LOWER(sk.KEYWORD_STRING) LIKE '%social%'
   OR LOWER(sk.KEYWORD_STRING) LIKE '%ssn%'
   OR LOWER(sk.KEYWORD_STRING) = 'security'
ORDER BY sc.POLICY_GROUP, LENGTH(sk.KEYWORD_STRING) DESC, sk.KEYWORD_STRING;
