-- ============================================================================
-- CRITICAL FIX: Governance Table Schema Corrections
-- ============================================================================
-- Run this in Snowflake to fix all schema mismatches causing SQL errors

USE DATABASE CLASSIFIED_DATA;
USE SCHEMA DATA_CLASSIFICATION_GOVERNANCE;

-- ============================================================================
-- FIX #1: SENSITIVE_PATTERNS table - rename PATTERN_VALUE to PATTERN_STRING
-- ============================================================================

-- Check if column exists before renaming
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME = 'SENSITIVE_PATTERNS';

-- If you see PATTERN_VALUE but not PATTERN_STRING, rename it:
ALTER TABLE SENSITIVE_PATTERNS 
RENAME COLUMN PATTERN_VALUE TO PATTERN_STRING;

-- OR if schema is different, recreate with correct schema:
-- DROP TABLE IF EXISTS SENSITIVE_PATTERNS;
-- CREATE TABLE SENSITIVE_PATTERNS (
--     PATTERN_ID NUMBER AUTOINCREMENT PRIMARY KEY,
--     CATEGORY_ID NUMBER NOT NULL,
--     PATTERN_STRING VARCHAR(500) NOT NULL,  -- FIXED: was PATTERN_VALUE
--     PATTERN_TYPE VARCHAR(50) DEFAULT 'REGEX',
--     IS_ACTIVE BOOLEAN DEFAULT TRUE,
--     CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
--     FOREIGN KEY (CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
-- );

-- ============================================================================
-- FIX #2: Add missing columns to existing tables
-- ============================================================================

-- Add HIGH_RISK column to SENSITIVITY_CATEGORIES if missing
ALTER TABLE SENSITIVITY_CATEGORIES 
ADD COLUMN IF NOT EXISTS IS_HIGH_RISK BOOLEAN DEFAULT FALSE;

-- OR use HIGH_RISK instead (check which name you want)
-- ALTER TABLE SENSITIVITY_CATEGORIES 
-- ADD COLUMN IF NOT EXISTS HIGH_RISK BOOLEAN DEFAULT FALSE;

-- Add DATABASE_NAME to CLASSIFICATION_RESULTS if missing
ALTER TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_RESULTS
ADD COLUMN IF NOT EXISTS DATABASE_NAME VARCHAR(255);

-- Add CLASSIFICATION_TAG if missing
ALTER TABLE DATA_CLASSIFICATION_GOVERNANCE.CLASSIFICATION_RESULTS
ADD COLUMN IF NOT EXISTS CLASSIFICATION_TAG VARCHAR(255);

-- ============================================================================
-- FIX #3: Remove duplicate columns if they already exist
-- ============================================================================

-- Check for duplicates (run this to see current schema)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'DATA_CLASSIFICATION_GOVERNANCE'
  AND TABLE_NAME IN ('CLASSIFICATION_RESULTS', 'SENSITIVE_PATTERNS', 'SENSITIVITY_CATEGORIES')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- If PREV_SHA256_HEX or CHAIN_SHA256_HEX already exist, no need to add them
-- The error means ALTER TABLE ADD COLUMN is being called on existing columns

-- ============================================================================
-- FIX #4: Verify all governance tables have correct schema
-- ============================================================================

-- Expected schema for SENSITIVITY_CATEGORIES:
/*
CATEGORY_ID NUMBER AUTOINCREMENT PRIMARY KEY
CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE
DESCRIPTION TEXT
DETECTION_THRESHOLD NUMBER(3,2) DEFAULT 0.65
IS_ACTIVE BOOLEAN DEFAULT TRUE
IS_HIGH_RISK BOOLEAN DEFAULT FALSE
CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
UPDATED_DATE TIMESTAMP_NTZ
*/

-- Expected schema for SENSITIVE_KEYWORDS:
/*
KEYWORD_ID NUMBER AUTOINCREMENT PRIMARY KEY
CATEGORY_ID NUMBER NOT NULL
KEYWORD_STRING VARCHAR(100) NOT NULL
MATCH_TYPE VARCHAR(20) DEFAULT 'EXACT'
SENSITIVITY_WEIGHT NUMBER(3,2) DEFAULT 1.0
IS_ACTIVE BOOLEAN DEFAULT TRUE
CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
FOREIGN KEY (CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
*/

-- Expected schema for SENSITIVE_PATTERNS:
/*
PATTERN_ID NUMBER AUTOINCREMENT PRIMARY KEY
CATEGORY_ID NUMBER NOT NULL
PATTERN_STRING VARCHAR(500) NOT NULL   -- CRITICAL: Must be PATTERN_STRING, not PATTERN_VALUE
PATTERN_TYPE VARCHAR(50) DEFAULT 'REGEX'
IS_ACTIVE BOOLEAN DEFAULT TRUE
CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
FOREIGN KEY (CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
*/

-- ============================================================================
-- FIX #5: Drop and recreate SENSITIVE_PATTERNS if schema is wrong
-- ============================================================================

-- BACKUP first!
CREATE TABLE SENSITIVE_PATTERNS_BACKUP AS 
SELECT * FROM SENSITIVE_PATTERNS;

-- Drop and recreate with correct schema
DROP TABLE SENSITIVE_PATTERNS;

CREATE TABLE SENSITIVE_PATTERNS (
    PATTERN_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_ID NUMBER NOT NULL,
    PATTERN_STRING VARCHAR(500) NOT NULL,  -- FIXED
    PATTERN_TYPE VARCHAR(50) DEFAULT 'REGEX',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CATEGORY_ID) REFERENCES SENSITIVITY_CATEGORIES(CATEGORY_ID)
);

-- Restore data (adjust column name if needed)
INSERT INTO SENSITIVE_PATTERNS (CATEGORY_ID, PATTERN_STRING, PATTERN_TYPE, IS_ACTIVE)
SELECT CATEGORY_ID, 
       PATTERN_VALUE AS PATTERN_STRING,  -- Or whatever the old column was called
       PATTERN_TYPE, 
       IS_ACTIVE
FROM SENSITIVE_PATTERNS_BACKUP;

-- ============================================================================  
-- VERIFICATION QUERIES
-- ============================================================================

-- Verify SENSITIVE_PATTERNS has PATTERN_STRING column
SELECT COUNT(*) AS PATTERN_COUNT, 
       MIN(LENGTH(PATTERN_STRING)) AS MIN_LEN,
       MAX(LENGTH(PATTERN_STRING)) AS MAX_LEN
FROM SENSITIVE_PATTERNS 
WHERE IS_ACTIVE = TRUE;

-- Verify SENSITIVITY_CATEGORIES has IS_HIGH_RISK
SELECT CATEGORY_NAME, IS_HIGH_RISK 
FROM SENSITIVITY_CATEGORIES 
WHERE IS_ACTIVE = TRUE
LIMIT 5;

-- Verify no errors
SELECT 'Schema fix complete!' AS STATUS;
